Adding calibration parameters to qibocal
qiboteam/qibocal pull request #1021
Opened 2024-10-22 07:59 UTC by andrea-pasquale

This PR will restore the `characterization` section of the platform runcards that was removed during the update to `0.2` by introducing a `calibration.json` file.

Checklist:
- [ ] Reviewers confirm new code works as expected.
- [ ] Tests are passing.
- [ ] Coverage does not decrease.
- [ ] Documentation is updated.
- [ ] Compatibility with Qibo modules (Please edit this section if the current pull request is not compatible with the following branches).
    - [ ] Qibo: `master`
    - [ ] Qibolab: `main`
    - [ ] Qibolab_platforms_qrc: `main`

2024-10-22 08:36 UTC, alecandido commented
Which is the reason why you eventually decided to base this on https://github.com/qiboteam/qibocal/tree/0.2? (just to be aware)

2024-10-22 08:41 UTC, andrea-pasquale commented
> Which is the reason why you eventually decided to base this on https://github.com/qiboteam/qibocal/tree/0.2? (just to be aware)

Given that this is required for 0.2 I thought that it could be more useful to start from the `0.2` branch. I know that before I said to you that I would have started from `main` :) Eventually I could rebase to main or another branch when necessary.

2024-10-25 17:40 UTC, andrea-pasquale commented
I manage to restore the update for the parameters in calibration section for all protocols which have been ported to 0.2 in #990. As more protocols are added there I will update them also here.
This could be a good time to start discussing about the interface which is currently being implemented in this PR. 
If there are important changes I suggest to them now, otherwise we can always fine tune the implementation thanks to the fact that now the calibration parameters are disentangled from qibolab.

2024-10-25 17:57 UTC, alecandido commented on src/qibocal/calibration/platform.py
> +            path = Path(os.getenv("QIBOLAB_PLATFORMS")) / name
In principle, you could get this value from
https://github.com/qiboteam/qibolab/blob/946a04f21f522cd05f898de91270153af7cdceff/src/qibolab/_core/platform/load.py#L13

It's not exposed, but not going to change anytime soon.

In any case, even the current solution is good enough (not even the value is going to change).

2024-10-25 17:59 UTC, alecandido commented
@andrea-pasquale actually I took a look, and to me, we could even merge this to #996, to avoid maintaining two branches, one on top of the other.

Of course, I'd wait even for the others to take a look as well, since it is a good chance to do this with the isolated diff (rather than mixed together with the rest of the 0.2 update).

2024-10-27 11:52 UTC, alecandido approved these changes

2024-10-28 07:54 UTC, andrea-pasquale commented
@stavros11 as soon as you approve these changes we can decide where to merge this PR. Currently it is pointing to #990 but we could even merge it to #996. Let me know how you prefer to proceed.

2024-10-28 08:42 UTC, alecandido commented
I'd personally go for #990, as this is more final than #996 itself. But I'm open to different opinions

2024-10-28 08:43 UTC, stavros11 reviewed
Thanks @andrea-pasquale. I had a quick look and some comments, but I would also like to test something on hardware before merging. Have you tried to do so and check if the updates are dumped properly?

Other than that, my main comment is that this is reintroducing some of the repetition we had in qibolab 0.1, as some values appear in both the calibration and the parameters file. For example `frequency_01` will be the same as the drive config frequency, `sweetspot` will be the same as the flux config offset, etc.. This is not necessarily bad, as it provides flexibility (eg. we may not want to operate the qubits at the sweetspot, etc.), however it will complicate the update process, both in the qibocal `_update` rules and the manual copy-pasting (if fitting fails) since we will again need to put the same value in multiple places. Personally, I don't have a strong opinion against, just mentioning it for discussion.

> @stavros11 as soon as you approve these changes we can decide where to merge this PR. Currently it is pointing to #990 but we could even merge it to #996. Let me know how you prefer to proceed.

Another option, since this seems to be more advanced than #996, is to merge directly to #990 and I will rebase #996 on top of it. Note that #996 will change completely anyway to follow the idea of https://github.com/qiboteam/qibolab/pull/1061, so I would avoid putting anything on top of it right now.

2024-10-28 08:43 UTC, stavros11 commented on src/qibocal/calibration/calibration.py
> +    model_config = ConfigDict(extra="forbid")
In qibolab the base `Model` is frozen. I guess here you are not doing this to make the updates easier, which makes sense to me.

2024-10-28 08:43 UTC, stavros11 commented on src/qibocal/calibration/platform.py
> +from qibolab._core.platform.load import PLATFORMS
I think this should be avoided since `_core` is not part of the public interface. In principle, in qibolab we are free to change the structure of `_core` at any point, which could break this, while if you stick to public objects it should be safer, as we have agreed to (hopefully) not break them.

Now the issue is that, unless I am missing something, this is probably not available in qibolab public API. In that case we would have to release it in 0.2.1 (this would be a new feature, so not breaking change, but then qibocal should have `>=0.2.1` requirement).

There are different ways we could do that, such as export `PLATFORMS` directly, or through a function, or have a property in `Platform` to access its path.

2024-10-28 08:43 UTC, stavros11 commented on src/qibocal/calibration/platform.py
> +from qibolab._core.platform.load import PLATFORMS
Following up on this, I have not tested but it may actually be possible to get the path of a `Platform` with the current public API using something like:
```py
from qibolab import locate_platform

path = locate_platform(platform.name)
```
If this is sufficient, we won't need to release a new qibolab.

2024-10-28 08:43 UTC, stavros11 commented on src/qibocal/calibration/platform.py
> +            path = Path(os.getenv(PLATFORMS)) / name
Looking at the functions in https://github.com/qiboteam/qibolab/blob/main/src/qibolab/_core/platform/load.py and in particuar: https://github.com/qiboteam/qibolab/blob/946a04f21f522cd05f898de91270153af7cdceff/src/qibolab/_core/platform/load.py#L25 
I believe in qibolab we support storing multiple paths (with a separator) in the environment variable. I think this is not supported here, but again, I have not tested. This is also why it is safer to get the platform path using qibolab functions, instead of manually processing the environment variable here.

2024-10-28 09:07 UTC, alecandido commented
> Other than that, my main comment is that this is reintroducing some of the repetition we had in qibolab 0.1, as some values appear in both the calibration and the parameters file. For example `frequency_01` will be the same as the drive config frequency, `sweetspot` will be the same as the flux config offset, etc.. This is not necessarily bad, as it provides flexibility (eg. we may not want to operate the qubits at the sweetspot, etc.), however it will complicate the update process, both in the qibocal `_update` rules and the manual copy-pasting (if fitting fails) since we will again need to put the same value in multiple places. Personally, I don't have a strong opinion against, just mentioning it for discussion.

Nice catch @stavros11!

Actually, I didn't investigate in depth the content of the calibration parameters, but just the structure of the implementation.
I'm a more opinionated than @stavros11: we should really avoid repetition.
Though my motivation is slightly different: for sure updating twice is more annoying, but what is worse is what happens when something goes wrong, and you do **not** update twice, but only in a single place, leading to an inconsistent configuration.
Let's rule out the room for inconsistencies as much as possible.

2024-10-28 09:58 UTC, andrea-pasquale commented
> Thanks @andrea-pasquale. I had a quick look and some comments, but I would also like to test something on hardware before merging. Have you tried to do so and check if the updates are dumped properly?

Thanks for the review @stavros11.
Yes, I already checked with https://github.com/qiboteam/qibolab_platforms_qrc/pull/192 and the updates seems to work as expected.

> 
> Other than that, my main comment is that this is reintroducing some of the repetition we had in qibolab 0.1, as some values appear in both the calibration and the parameters file. For example `frequency_01` will be the same as the drive config frequency, `sweetspot` will be the same as the flux config offset, etc.. This is not necessarily bad, as it provides flexibility (eg. we may not want to operate the qubits at the sweetspot, etc.), however it will complicate the update process, both in the qibocal `_update` rules and the manual copy-pasting (if fitting fails) since we will again need to put the same value in multiple places. Personally, I don't have a strong opinion against, just mentioning it for discussion.

As you said, I know that in theory we are repeating some parameters, but the idea is that you don't necessarily want to operate the qubit at the "calibration parameters". You already mentioned the sweetspot, but also for the drive frequency some papers are showing that you might get better performances by not driving the qubit at its 0->1 frequency but a slight detuning might help, especially when using DRAG. See for example Sect. IV C 3 [here](https://arxiv.org/pdf/1904.06560). The same goes for the readout frequency. I know that up to know we were talking about frequencies in a very generic way but I believe that if we are able to distinguish between the physical frequencies (resonator frequency or qubit frequency) and the frequencies at which we operate our devices this could be beneficial. Moreover, we can come up with protocols in qibocal that are targerting only some of those.
> 
> > @stavros11 as soon as you approve these changes we can decide where to merge this PR. Currently it is pointing to #990 but we could even merge it to #996. Let me know how you prefer to proceed.
> 
> Another option, since this seems to be more advanced than #996, is to merge directly to #990 and I will rebase #996 on top of it. Note that #996 will change completely anyway to follow the idea of [qiboteam/qibolab#1061](https://github.com/qiboteam/qibolab/pull/1061), so I would avoid putting anything on top of it right now.

Sure, originally I pointed to 0.2 since with #996 I was getting some import errors.
Since this branch is already poiting to #990, it would be easier given that I don't have to rebase.

2024-10-28 10:09 UTC, andrea-pasquale commented on src/qibocal/calibration/calibration.py
> +    model_config = ConfigDict(extra="forbid")
Indeed, after discussing with @alecandido we decided to not have a `frozen` given that the update right now is quite cumbersome. If in qibolab we are able to find a suitable solution which is not too complicated we might go for a frozen model here as well.

2024-10-28 10:09 UTC, andrea-pasquale commented on src/qibocal/calibration/platform.py
> +from qibolab._core.platform.load import PLATFORMS
`locate_platform` seems to work correctly I didn't know about this function. Thanks!

2024-10-28 10:13 UTC, andrea-pasquale commented on src/qibocal/calibration/calibration.py
> +from qibolab._core.serialize import NdArray
Concerning the fact that it would be better to not import anything from `_core` also here I am importing a few things. I remember that there were some discussions in the past about exposing `QubitId` or `QubitPairId`. In this particular case `QubitPairId` is useful because I don't need to do anything to make sure that the pair is serialized correctly as a string. Eventually we could re-write some of these stuff in qibocal since we don't need to follow the exact serialization scheme of qibolab.

2024-10-28 13:16 UTC, stavros11 commented on src/qibocal/calibration/calibration.py
> +from qibolab._core.serialize import NdArray
Thanks for pointing this out, I did not check in detail all changes.

I believe the initial idea for `QubitId` and `QubitPairId` was to not expose them from qibolab and therefore I had to redefine them in qibocal: https://github.com/qiboteam/qibocal/blob/d35ab6b2d707031520927a9325b62b9b95a60c62/src/qibocal/auto/operation.py#L18-L19

After merging this we will be following two different approaches, the (private) import here and the redefinition everywhere else in qibocal, which is not optimal. If the deserialization of `QubitPairId` is really needed, we should consider if it's worth exposing it to public qibolab. I think qibocal will require a 0.2.1 anyway, in order to properly do parameter updates, so we could also include the `QubitPairId` there.

2024-10-28 13:31 UTC, stavros11 approved these changes
Thanks for the updates @andrea-pasquale. I also did a quick test and it seems to work, so it should be fine to merge in the 0.2 branch.

> EDIT: I take it back: the parameters in Qibolab are the operational ones, but they do not necessarily correspond to the physical values of the system (e.g. you can decide to operate a qubit out of its sweetspot, for some reason, or to apply a certain detuning) - I don't see them as redundant any longer. What do you think @stavros11?

Indeed, these parameters are not strictly equivalent, we just happen to use the same values, that's why I said it's mostly for discussion.

However, in that case I would propose to go a step further and have different operations for updating each part. Qibocal's default `_update` (and `qq update`) should only update the calibration part and we provide a separate command or script that ports the changes to parameters (if the user wishes to do so). This new command will just copy some values from `Calibration` to `Parameters` (eg. `frequency_01` will go do the drive configs, sweetspot to offset, etc.) which is the way we are operating right now.

Obviously this will add some overhead to usage (one more command), however I find it cleaner than the current approach, where we are duplicating the updates and essentially force using the qubits at their sweetspot.

EDIT: This suggestion is for another PR, not here. Actually #996 would be a good candidate to do this if you agree.

2024-10-28 13:39 UTC, alecandido commented
@stavros11 what you say makes sense, but I wonder whether it is really a convenient approach.

In general, we may have some routines which are just characterizing the chip (finding things like `frequency_01`) and some other which may instead calibrate the operational parameters (to improve gates' fidelity, or other relevant metrics).
While the physical parameters will only populate the calibration part, the operational ones are those which are by definition stored in `parameters.json`. If we decide to always apply the two-steps approach, we may need to go beyond what is being done here, and double also the operational ones (e.g. the operational frequency), on top of those that are usually copied to them (e.g. the qubit frequency).

I.e., the two-steps approach requires:
```yaml
parameters.json:
  RX.frequency: ...

calibration.json:
  RX.frequency: ...
  frequency_01: ...
```
otherwise it would be impossible to operate the qubit out of its frequency (or, conversely, to store its characterized frequency, if operated out of it).

2024-10-28 13:51 UTC, andrea-pasquale commented
Thanks for the proposal @stavros11.
I tend to agree with @alecandido on this one.
I think that it should be ok to have "double updates" at least at the beginning of the characterization process, where the operational frequencies are the same as the physical frequencies. Moreover, I would say that especially later on when we perform advanced operations such readout optimization we should only modify the readout frequency in the parameters.json.
To avoid confusion we could also try to classify the protocols in characterization protocols where we are going to modify both the parameters.json and the calibration.json and the calibration protocols where we are only going to modify the parameters.json file (if I finally understood correclty the difference between calibration and characterization).

Eventually we could add a command to update the `parameters.json` starting from the `calibration.json`, assuming that all operational frequencies will be set to the physical frequencies and the offset will be set to the sweetspot.

2024-10-28 15:00 UTC, Edoardo-Pedicillo requested changes
Thanks @andrea-pasquale ,  I have left some comments. Could you please have a look to the tests ?

2024-10-28 15:06 UTC, alecandido commented on src/qibocal/calibration/calibration.py
> +class Qubit(Model):
Is it possible to measure the charging energy independently of the anharmonicity? (i.e. not measured as the frequencies' difference)

2024-10-28 15:08 UTC, alecandido commented on src/qibocal/calibration/calibration.py
> +    rb_fidelity: Optional[float] = None
Maybe I misunderstood: in which way is it different from a renaming proposal?

2024-10-28 18:34 UTC, andrea-pasquale commented on src/qibocal/calibration/calibration.py
> +class Qubit(Model):
There is already a parameter for Ec, it is called [`charging_energy`](https://github.com/qiboteam/qibocal/blob/124c01b9a486fd16c77ad3b0eff1a6ac47f43c17/src/qibocal/calibration/calibration.py#L50).
I could add also `Ej` I decided not to included immediately since we have no protocols which can compute `Ej`.
We can add some parameters later as soon as we have the corresponding protocols to evaluate them.

2024-10-28 18:35 UTC, andrea-pasquale commented on src/qibocal/calibration/calibration.py
> +class Coherence(Model):
Sure, I can add errors for these parameters. I can also move them inside the `Qubit` class.

2024-10-28 18:37 UTC, andrea-pasquale commented on src/qibocal/calibration/calibration.py
> +    rb_fidelity: Optional[float] = None
Even if we create a Benchmark class containg all fidelities we will still need to have a `TwoQubitCalibration` object given that at least there should a class for each qubit or qubit pair.

2024-10-28 18:38 UTC, andrea-pasquale commented on src/qibocal/calibration/calibration.py
> +    """Dict with qubit pairs calibration."""
See https://github.com/qiboteam/qibocal/pull/1021#discussion_r1819566037

2024-10-28 18:39 UTC, andrea-pasquale commented
> Could you please have a look to the tests ?

There is not much that I can do about tests given that this PR is pointing at a branch where they are failing given that not all protocols have been updated to `0.2`. I thought about adding some tests but given that these are just data structures they would be quite naive.

2024-10-28 20:03 UTC, alecandido commented on src/qibocal/calibration/calibration.py
> +class Qubit(Model):
> There is already a parameter for Ec, it is called [`charging_energy`](https://github.com/qiboteam/qibocal/blob/124c01b9a486fd16c77ad3b0eff1a6ac47f43c17/src/qibocal/calibration/calibration.py#L50).

Correct, but my understanding was that @Edoardo-Pedicillo acknowledged that, but he was proposing to have it an actual attribute (instead of a property) such that it can have a value that is different from `-anharmonicity`.

And that's why I was asking whether it is possible to compute it independently.

2024-10-28 20:04 UTC, alecandido commented on src/qibocal/calibration/calibration.py
> +class Coherence(Model):
You could even define a type for:
```py
Measure = tuple[float, float]
"""Measured central value and associated uncertainty."""
```
(that's just a rough sketch, pick the name and description you find more suitable)

2024-10-28 20:06 UTC, alecandido commented
> There is not much that I can do about tests given that this PR is pointing at a branch where they are failing given that not all protocols have been updated to `0.2`. I thought about adding some tests but given that these are just data structures they would be quite naive.

@andrea-pasquale you could test serialization and deserialization. E.g. making a closed loop, and checking the value is still consistent (that would be meaningful, because you would check for regressions in case of changes in some types).

2024-10-29 05:10 UTC, Edoardo-Pedicillo commented on src/qibocal/calibration/calibration.py
> +class Qubit(Model):
> Is it possible to measure the charging energy independently of the anharmonicity? (i.e. not measured as the frequencies' difference)

Yes, from the qubit flux dependecy protocol (https://qibo.science/qibocal/stable/protocols/flux/single.html), in theory also $E_J$ can be evaluated from there.

2024-10-29 05:45 UTC, Edoardo-Pedicillo commented on src/qibocal/calibration/calibration.py
> +    rb_fidelity: Optional[float] = None
> Maybe I misunderstood: in which way is it different from a renaming proposal?

It was not proposing a renaming but a reordering, I was suggesting collecting all the fidelities together in a single class, since they are used for the same purpose, validation of the calibration.

> Even if we create a Benchmark class containg all fidelities we will still need to have a `TwoQubitCalibration` object given that at least there should a class for each qubit or qubit pair.

Ok, I see your point, thanks.

2024-10-29 08:17 UTC, andrea-pasquale commented on src/qibocal/calibration/calibration.py
> +class Qubit(Model):
> > Is it possible to measure the charging energy independently of the anharmonicity? (i.e. not measured as the frequencies' difference)
> 
> Yes, from the qubit flux dependecy protocol (https://qibo.science/qibocal/stable/protocols/flux/single.html), in theory also E J can be evaluated from there.

Yes, but actually given that the fit is already quite complicated $E_C$ is not fitted there, but it is fixed.
Regarding $E_J$ I agree with you, I can compute it there as a function of the charging energy and the maximum frequency.

2024-10-29 14:51 UTC, stavros11 commented
> There is not much that I can do about tests given that this PR is pointing at a branch where they are failing given that not all protocols have been updated to `0.2`. I thought about adding some tests but given that these are just data structures they would be quite naive.

About this, there is also the option to skip tests of not updated routines in the `0.2` branch, however since pylint will also be failing due to the changes in qibolab interface (`PulseSequence` no longer has `add`, `Platform` no longer has `sweep`, etc.), the effort of fixing this is almost equivalent to fully updating the routines, so I would rather do the latter first.

2024-11-05 16:01 UTC, Edoardo-Pedicillo approved these changes
Thanks @andrea-pasquale ! LGTM

2024-11-07 08:43 UTC, alecandido commented
Now that we arrived to 3 approvals, i.e. almost everyone saw the diff, and we have some consensus, shall we merge?

2024-11-07 11:06 UTC, merged