implement tree
qiboteam/qibocal pull request #237
Opened 2023-02-07 14:02 UTC by Edoardo-Pedicillo

This PR implements the tree executor described by #233 .
Checklist:
- [ ] Reviewers confirm new code works as expected.
- [ ] Tests are passing.
- [ ] Coverage does not decrease.
- [ ] Documentation is updated.

2023-02-07 14:15 UTC, AleCandido commented on src/qibocal/tree/operation.py
> +    command_3 = command_3
```suggestion
from dataclasses import dataclass
from typing import Callable

@dataclass
class Routine:
    name: str
    routine: Callable

def _command_1():
    print("command 1")

command_1 = Routine("1", routine=_command_1)

def _command_2():
    print("command 2")

command_2 = Routine("2", routine=_command_2)

def _command_3():
    print("command 3")

command_3 = Routine("3", routine=_command_3)

class Operation(Enum):
    command_1 = command_1
    command_2 = command_2
    command_3 = command_3
```

Let's start like this, test if it's working :)

2023-02-07 14:15 UTC, AleCandido commented on src/qibocal/tree/operation.py
> +    command_3 = command_3
In principle, we could use one element tuples. But let's use immediately something that looks closer to what I have in mind for the final product.

2023-02-07 14:18 UTC, AleCandido commented on src/qibocal/tree/operation.py
> +    command_3 = command_3
`Operation.command_1.routine()` should invoke your function.

If you have a string for the name of the element (the LHS inside the class, not the attribute) you can use it as `Operation['command_1']`, obtaining the same object as `Operation.command_1`.
However, whenever you can avoid the string.

2023-02-07 17:26 UTC, AleCandido requested changes

2023-02-07 17:26 UTC, AleCandido commented on src/qibocal/tree/test.py
> +def test_Task():
```suggestion
def test_task():
```
Please, respect Python conventions on identifiers case
https://peps.python.org/pep-0008/

2023-02-07 17:26 UTC, AleCandido commented on src/qibocal/tree/task.py
> +        return self._requirements
These properties are actually aliases, why do you need them?

2023-02-07 17:26 UTC, AleCandido commented on src/qibocal/tree/task.py
> +        return self._ready
Actually, this is fine to be a property, but it should be:
```suggestion
    @property
    def ready(self):
        return all(self.requirements.values())
```

2023-02-07 17:26 UTC, AleCandido commented on src/qibocal/tree/task.py
> +    _requirements: dict
```suggestion
    _requirements: Dict[str, bool]
```

2023-02-07 17:26 UTC, AleCandido commented on src/qibocal/tree/task.py
> +    _ready: bool
Drop this attribute in favor of the property

2023-02-08 18:49 UTC, AleCandido commented on src/qibocal/tree/task.py
> +class Output:  # TODO: write Output as abstract class
https://stackoverflow.com/a/60669138/8653979

But maybe we should do something simpler, let me think about it

2023-02-10 08:17 UTC, Edoardo-Pedicillo commented
About the method `time_travel', it will be deployed in the next step, right ?

2023-02-10 08:51 UTC, AleCandido commented
> About the method `time_travel', it will be deployed in the next step, right ?

The name is almost a joke (not completely: [time travel debugging](https://en.wikipedia.org/wiki/Time_travel_debugging) is the technical name for a similar concept, but we are not writing a debugger).

However, all the ingredients we'll be implemented here, that are:
- the history
- the outputs in the history

But in order to actually implement the time travel feature with need to know which object we want to make travelling, and at the moment we're not adding any ingredient related to the platform/runcard.
What we can do, it's to define a protocol: we assume that we can "step" any object that is capable to consume an `Output` object, with an `.update()` or `.forward()` method. At that point we could also implement `History.time_travel(traveler)`, by repeated call to `traveler.forward()`.

2023-03-04 18:39 UTC, AleCandido commented
Actually, the "normal flow" should be completed, apart from the docstrings and Sphinx description (e.g. it is nowhere written what "normal" and "exceptional flow" mean).
I will complete those, and split the implementation of the exceptional flow to a further PR.

Hooking the actual autocalibration routines can be done before or after the exceptional flow implementation, but without it, they would not be incredibly useful. However, in the end all elements mentioned will be required, even for a minimal product.

In any case, I'd merge after #262

2023-03-07 11:50 UTC, AleCandido commented
I would suggest you to have a look at the example runcards https://github.com/qiboteam/qibocal/tree/tree/tests/runcards and docs https://github.com/qiboteam/qibocal/blob/tree/doc/source/getting-started/autoruncard.rst

In particular, it should be possible to reproduce both @igres26 diagram for single qubit, but also with all the black and purple lines (no pink, grey, and green).
Dynamic conditions are not implemented (this is the *Exceptional flow*, it will be implemented last with #264), and routines are not yet accessible from the runcards (they will be implemented in a separate PR, following #265).

If you are fine with the current layout, I'd propose merging, and then directly starting with #265 to make an actual automated Normal Flow.

2023-03-09 08:04 UTC, andrea-pasquale reviewed
Thanks @AleCandido.
It looks very good to me.
You can find below some comments.

2023-03-09 08:04 UTC, andrea-pasquale commented on src/qibocal/auto/execute.py
> +        candidates.sort(key=lambda t: t.priority)
Here we are sorting in ascending order of priority.
Maybe it is just me but I was expecting that the nodes should be ordered in descending order of priority.
If a node has a higher priority value compared to another one I would expect that it should be executed first.

2023-03-09 10:43 UTC, AleCandido commented on src/qibocal/auto/draw.py
> +    """Draw a graph according to its priority."""
This was a nice-to-have but still rather incomplete...

I implemented mainly for debugging, but I know that eventually we want to use it.
I was considering to make it graphviz independent, but it might be a certain amount of work and I'm not sure it's worth.

For the time being, I just made sure that if you don't use it nothing breaks

2023-03-09 10:49 UTC, AleCandido commented on src/qibocal/auto/execute.py
> +        candidates.sort(key=lambda t: t.priority)
I have not been able to find a nice solution, so I kept one of the least bad ones...

Suggestions are welcome.

2023-03-09 12:00 UTC, andrea-pasquale commented on src/qibocal/auto/execute.py
> +        candidates.sort(key=lambda t: t.priority)
Perhaps we can use something like `wait_time`?
So that the nodes with the with the lower `wait_time` are executed first.

2023-03-09 18:29 UTC, AleCandido commented on src/qibocal/auto/execute.py
> +        candidates.sort(key=lambda t: t.priority)
Let's try to involve other people and get more proposals: @igres26 @stavros11 @Edoardo-Pedicillo  @Jacfomg @rodolfocarobene we need some brainstorming!

In the end, it is just a UI problem, but definitely a relevant one :)

2023-03-13 06:45 UTC, igres26 approved these changes
All looks good on my end. 
As for the "priority" naming issue, I agree that it can be a bit misleading but I don't think it's that strange. I will think of alternatives. Is this something we want to consolidate in this pull request?

2023-03-13 10:26 UTC, AleCandido commented
> Is this something we want to consolidate in this pull request?

Unless right after this PR will have tons of runcards with that name, I'd say we can consider the naming issue not urgent (but better not to forget, otherwise we will have to motivate the weird name over and over).

2023-03-14 07:20 UTC, andrea-pasquale approved these changes

2023-03-15 09:53 UTC, merged