non interactive gate set characterization + action builder
qiboteam/qibocal pull request #239
Opened 2023-02-08 05:53 UTC by wilkensJ

Checklist:
- [ ] Reviewers confirm new code works as expected.
- [ ] Tests are passing.
- [ ] Coverage does not decrease.
- [ ] Documentation is updated.

2023-02-13 13:45 UTC, andrea-pasquale requested changes
Thanks for implementing this @wilkensJ.
Overall this PR looks ok. There are a few things that needs to be modified (I've put everything in the comments). I still need to have a look at tests. Probably I will do that tomorrow.

I think that there a few ouput directories of qq in this branch, make sure to remove them before we merge this PR.

2023-02-13 13:45 UTC, andrea-pasquale commented on src/qibocal/cli/builders.py
> +            results = self.func(platform, self.runcard["qubits"], **self.params)
```suggestion
        results = self.func(platform, self.runcard["qubits"], **self.params)
```

2023-02-13 13:45 UTC, andrea-pasquale commented on src/qibocal/cli/builders.py
> +                getattr(data, f"to_{data_format}")(self.path)
After accepting the above suggestion this block needs to be indented correctly.

2023-02-13 13:45 UTC, andrea-pasquale commented on src/qibocal/cli/builders.py
> +        from qibocal.calibrations.niGSC.basics.plot import plot_qq
It should be better to have the plotting functions inside the plots folder, however this is not a big issue for now.

2023-02-13 13:45 UTC, andrea-pasquale commented on src/qibocal/cli/builders.py
> +        from qibocal.calibrations.niGSC.basics.plot import plot_qq
Also,  I think that it could be useful to split this method in two method. A first one that creates the folder if necessary and load the module. And a second one which should only load the plotting function, in this way the `ReportBuilder` could call directly that method instead of calling direclty `build`. In this way we avoid to import the all module also for the `RepiortBuilder`.

2023-02-13 13:45 UTC, andrea-pasquale commented on src/qibocal/cli/builders.py
> +                routine.build()
This could be replaced by the method that loads just the plotting function. See comment above about the `ReportBuilder`.

2023-02-13 13:45 UTC, andrea-pasquale commented on src/qibocal/calibrations/niGSC/basics/experiment.py
> +            self.path = experiment_directory("rb")
I think that you can simply raise an error if `path` is `None`. You can also remove the function `experiment_directory` if it is not used in other parts of the code. In this way we can avoid code duplication given that the `ActionBuilder` already does a similar thing.

2023-02-13 13:45 UTC, andrea-pasquale commented on src/qibocal/calibrations/niGSC/basics/fitting.py
> +
Are all these fitting functions used in this branch? If not I would suggest to keep only the fitting functions that are relevant to this PR. The other ones can be added later.

Moreover, I would suggest to add those inside the global fitting module of qibocal.

2023-02-14 04:55 UTC, wilkensJ commented on src/qibocal/calibrations/protocols/test.py
> -
I cannot find it in my local repository. How do I push deleted files and folders?

2023-02-14 05:06 UTC, wilkensJ commented on doc/source/getting-started/niGSC/niGSC_and_standardrb.rst
> +=========================================
I think it makes a difference, right now the 'Non-Interactive Gate Set Characterization' Font is bigger than the 'Standard Randomized Benchmarking' which only has the underline of ======. And if it does not matter, if both outcomes are the same, the over and underline is not wrong.
<img width="500" alt="Bildschirm­foto 2023-02-14 um 09 05 50" src="https://user-images.githubusercontent.com/70592365/218644350-6964e713-7187-4415-b41e-26edb35fe45b.png">

2023-02-14 05:06 UTC, wilkensJ commented on doc/source/api-reference/qibocal.rst
> +---------------------------------
Why extend it by three characters?

2023-02-14 05:09 UTC, wilkensJ commented on src/qibocal/web/templates/template.html
> +            </li>
When the report was not build we played around with the template. I have no idea what these lines did.

2023-02-14 05:11 UTC, wilkensJ commented on src/qibocal/cli/builders.py
> +class singleActionParser:
That's your class, I suggest that you write the docstring.

2023-02-14 05:12 UTC, wilkensJ commented on src/qibocal/cli/builders.py
> +class niGSCactionParser(singleActionParser):
I don't like: ``noninteractiveGateSetCharacterizationActionParser``, it is too long. ``niGSCactionParser`` looks better.

2023-02-14 05:34 UTC, wilkensJ commented on doc/source/conf.py
> +    "sphinx.ext.autosectionlabel",
I am not 100% sure but I use it to refer to a section with its title. If there is another way I am open to used that.

![Bildschirm­foto 2023-02-14 um 09 15 00](https://user-images.githubusercontent.com/70592365/218645592-9989bdad-77c4-4a56-896a-d94b7c64eec3.png)

2023-02-14 05:38 UTC, wilkensJ commented on src/qibocal/cli/builders.py
> +            self.single_qubit = False
Again, I did not write this, just modified some parts such that they work. I have no idea what they are doing. Do whatever you think it right here.

2023-02-14 05:38 UTC, wilkensJ commented on src/qibocal/cli/builders.py
> +            results = self.func(platform, self.runcard["qubits"], **self.params)
Same as above.

2023-02-14 05:39 UTC, wilkensJ commented on src/qibocal/cli/builders.py
> +                getattr(data, f"to_{data_format}")(self.path)
Same as above.

2023-02-14 05:41 UTC, wilkensJ commented on src/qibocal/cli/builders.py
> +        from qibocal.calibrations.niGSC.basics.plot import plot_qq
I am lost in your structure, I just adopted it and made it work. Happy to make changes here, but I don't understand it well. Now it works. Also, I think for the plotting and fitting functions to be in the niGSC part is not wrong.

2023-02-14 05:41 UTC, wilkensJ commented on src/qibocal/cli/builders.py
> +                routine.build()
See comments above.

2023-02-14 05:42 UTC, wilkensJ commented on src/qibocal/calibrations/niGSC/basics/experiment.py
> +            self.path = experiment_directory("rb")
I want the saving and loading methods to be independent from ``qq``.

2023-02-14 05:44 UTC, wilkensJ commented on src/qibocal/calibrations/niGSC/basics/fitting.py
> +
They are all used by the three modules. For now, I think them being in the niGSC part or the global part doesn't matter so much. Your methods are not using it, only mine. And now you can see everything bunched together in the niGSC folder. If they are used by different characterizations I would say we make it global. But this is not the case yet.

2023-02-14 05:50 UTC, wilkensJ commented on runcards/actions_qq_1q.yml
> +  resonator_spectroscopy:
I added the path to .gitignore file, don't know why it still shows up here.

2023-02-14 06:51 UTC, andrea-pasquale commented on src/qibocal/calibrations/protocols/test.py
> -
Even if you don't see the folder you should be able to do `git rm -r protocols`

2023-02-14 06:56 UTC, andrea-pasquale commented on src/qibocal/cli/builders.py
> +class niGSCactionParser(singleActionParser):
I know that `noninteractiveGateSetCharacterizationActionParser` is too long. Since this is merely a parser and not the protocols itself we can change it something more light such as `ExperimentParser` or even `protocolParser`. 
Let me know what you think.

2023-02-14 06:58 UTC, andrea-pasquale commented on runcards/actions_qq_1q.yml
> +  resonator_spectroscopy:
Sorry I didn't mean to add this path to gitignore. I was suggesting to not push this particular modification on the code given that it is not relevant for the scope of this PR.

2023-02-14 07:01 UTC, andrea-pasquale commented on src/qibocal/cli/builders.py
> +                self._execute_single_action(routine, args, path)
Fine I will open a separate PR to address these issues.

2023-02-14 07:03 UTC, andrea-pasquale commented
@wilkensJ in the meantime could you have a look at why tests are failing? Let me know if you need any help.

2023-02-14 07:33 UTC, wilkensJ commented on runcards/actions_qq_1q.yml
> +  resonator_spectroscopy:
I ran ``git rm --cached runcards/actions_qq_1q.yml``, will that do the job?

2023-02-14 07:34 UTC, wilkensJ commented on src/qibocal/calibrations/protocols/test.py
> -
No, it did not work, ``fatal: pathspec 'src/qibocal/calibrations/protocols' did not match any files``

2023-02-14 07:42 UTC, wilkensJ commented on src/qibocal/cli/builders.py
> +class niGSCactionParser(singleActionParser):
The folder were all the protocols are stored is called niGSC, the parser is building a niGSC protocol. But methods like ``qubit_spectroscopy`` is a protocol too, it is just not named like it. So just ``protocolParser`` is too general. That would actually include everything. And ``ExperimentParser`` would be misleading because it is not just parsing the ``experiment`` class/object, but a whole non-interactive gate set characterization protocol. So I think ``niGSCactionParser`` is a good name.

2023-02-14 07:46 UTC, wilkensJ commented
The tests are failing due to a Permission error:
<img width="947" alt="Bildschirm­foto 2023-02-14 um 11 43 38" src="https://user-images.githubusercontent.com/70592365/218671586-381dbdd9-f28d-452a-b21a-9a42f7fdc538.png">
In testing the qq command / the action builder, I am writing a report and delete it immediately. This is apparently not possible with the testing environment in GitHub.
But then I don't know how to test the storage of the experiment/the qq command?

2023-02-14 07:50 UTC, andrea-pasquale commented on runcards/actions_qq_1q.yml
> -platform: tii1q_b1
This file needs to stay in the repo.

2023-02-14 07:50 UTC, andrea-pasquale commented on src/qibocal/cli/builders.py
> +class niGSCactionParser(singleActionParser):
> The tests are failing due to a Permission error: <img alt="Bildschirm­foto 2023-02-14 um 11 43 38" width="947" src="https://user-images.githubusercontent.com/70592365/218671586-381dbdd9-f28d-452a-b21a-9a42f7fdc538.png"> In testing the qq command / the action builder, I am writing a report and delete it immediately. This is apparently not possible with the testing environment in GitHub. For the ubuntu system the tests went through.
> 
> But then I don't know how to test the storage of the experiment/the qq command? Do you have an idea, @andrea-pasquale?

I will have a look at tests now, we should be able to find a way around this error.

2023-02-14 07:52 UTC, andrea-pasquale commented on runcards/actions_qq_1q.yml
> +  resonator_spectroscopy:
No because now the file as been removed. We need to keep it.

2023-02-14 07:53 UTC, andrea-pasquale commented on runcards/actions_qq_1q.yml
> +  resonator_spectroscopy:
I suggest to copy and paste the file from main directly in this branch. That should do the trick.

2023-02-14 07:53 UTC, andrea-pasquale commented on src/qibocal/calibrations/protocols/test.py
> -
I also don't see anymore the `protocols` folder so we should be good.

2023-02-14 07:54 UTC, andrea-pasquale commented on src/qibocal/web/templates/template.html
> +            </li>
I see that you remove it and everything seems to work as expected.

2023-02-15 05:24 UTC, wilkensJ commented
Now I have another problem with the documentation: When creating the html via 'make html' in the doc folder, following error message is displayed:

```txt
Sphinx v6.1.3 in Verwendung
loading pickled environment... failed
Fehlgeschlagen: Can't get attribute '_stable_repr_object' on <sphinx.deprecation._ModuleWrapper object at 0x15c8ce0a0>

Exception occurred:
  File "/opt/homebrew/Caskroom/miniforge/base/envs/qibocalenv/lib/python3.8/site-packages/sphinx/theming.py", line 192, in load_external_theme
    theme_entry_points = entry_points(group='sphinx.html_themes')
TypeError: entry_points() got an unexpected keyword argument 'group'
The full traceback has been saved in /var/folders/rq/rskls74x3rv0tnx5bqhg93bh0000gn/T/sphinx-err-d2pag55i.log, if you want to report the issue to the developers.
Please also report this if it was a user error, so that a better error message can be provided next time.
A bug report can be filed in the tracker at <https://github.com/sphinx-doc/sphinx/issues>. Thanks!
make: *** [html] Error 2
```

2023-02-15 05:55 UTC, andrea-pasquale commented
> Now I have another problem with the documentation: When creating the html via 'make html' in the doc folder, following error message is displayed:

For me the command is working. Also CI doesn't complain. Give it a try with a clean env to check if this error is still there.

2023-02-15 10:22 UTC, stavros11 reviewed
Thanks for implementing this. A couple of quick comments regarding code style, I will have a more detailed look later.

The docs are indeed nice, particularly the figures. Would be great to use this in other parts of qibo docs. One thing I find weird is that the circuits drawings are inverted (measurements are on the left) compared to the common notation, however I am guessing you did that so the gate order matches the mathematical representation of the circuit (as product of operators).

2023-02-15 10:22 UTC, stavros11 commented on src/qibocal/calibrations/niGSC/basics/experiment.py
> +        )
Is there any case where `circuitfactory` can be an arbitrary iterable or does it always need to be a `Circuitfactory` object? If it is the latter, why you don't check for `Circuitfactory` type directly instead of `Iterable`?

2023-02-15 10:22 UTC, stavros11 commented on src/qibocal/calibrations/niGSC/XIdrb.py
> +class moduleFactory(Circuitfactory):
Same comment about PEP 8 class naming here and in the other classes in this file.

2023-02-15 10:22 UTC, andrea-pasquale commented on doc/source/api-reference/qibocal.rst
> +---------------------------------
This suggestion should be ready to commit @wilkensJ

2023-02-15 10:28 UTC, andrea-pasquale commented on src/qibocal/calibrations/niGSC/basics/experiment.py
> +            self.path = experiment_directory("rb")
I understand your point. However, I still think that it will be sufficient to specify the path given by the user without having to serialize the output folder given that this functionality is provided by qq. Let's say also what the other reviewers think.

2023-02-15 14:02 UTC, wilkensJ commented on src/qibocal/calibrations/niGSC/basics/experiment.py
> +        )
I can be a list, or even another generator/iterator. The important thing is that is it iterable.
I can change the error handling.

2023-02-17 07:26 UTC, scarrazza commented
I believe this is good to go, could you please confirm?

2023-02-17 07:29 UTC, wilkensJ commented
The only open question from @andrea-pasquale is how to organize the files, else everything was cleared I think.

2023-02-17 07:36 UTC, andrea-pasquale commented
@wilkensJ I would like to have these points solved before merging:

- https://github.com/qiboteam/qibocal/pull/239#discussion_r1104408416_
- https://github.com/qiboteam/qibocal/pull/239#discussion_r1104431654_
           
The other two about re-organizing folders and `experiment_directory` could be addressed after the merge if necessary.

2023-02-17 09:14 UTC, stavros11 reviewed
Even though I did not test this, so far I did not see any blocking issues at least in the code. Below are some mostly cosmetic comments which are not very important but also relatively easy to implement.

2023-02-17 09:14 UTC, stavros11 commented on src/qibocal/calibrations/niGSC/basics/circuitfactory.py
> +        self, nqubits: int, depths: list | np.ndarray | int, qubits: list = []
Using lists (and generally mutable objects) as default arguments may lead to [unexpected behavior](https://stackoverflow.com/questions/1132941/least-astonishment-and-the-mutable-default-argument). I believe this is not relevant here because you are not manipulating `qubits` in the function, so no change required, just letting you know in case you encounter this somewhere else.

2023-02-17 09:21 UTC, stavros11 commented on src/qibocal/calibrations/niGSC/basics/experiment.py
> +            self.path = experiment_directory("rb")
If I understand correctly @andrea-pasquale means the `_generate_output_folder` function of the `ActionBuilder`. I would agree to reuse this method here to avoid code repetition, however if you do this, I would suggest to move this method outside the `ActionBuilder` (it is a `@staticmethod` anyway) and remove the underscore so that it can be used in other parts.

> I think that you can simply raise an error if `path` is `None`.

If you go with this approach, I think it is simpler to just remove the default `None` argument and make `path` required, instead of raising an error if `None`.

2023-02-17 11:32 UTC, scarrazza commented
@wilkensJ @andrea-pasquale if you can please implement Stavros suggestions so we can merge later today and include in the first release.

2023-02-17 13:38 UTC, andrea-pasquale approved these changes

2023-02-17 13:46 UTC, scarrazza commented
I believe there is something wrong with one or more tests in this PR.

2023-02-17 13:47 UTC, andrea-pasquale commented
> I believe there is something wrong with one or more tests in this PR.

Yes I know. I've approved it too soon. I will have a look now.

2023-02-17 15:12 UTC, andrea-pasquale commented
Now it is ready to merge @scarrazza.
The other points can be fixed later.

2023-02-17 15:41 UTC, scarrazza commented
Perfect, thank you.

2023-02-17 15:41 UTC, merged