optimizing data agroupation with numpy arrays
qiboteam/qibocal pull request #243
Opened 2023-02-14 18:16 UTC by DavidSarlle

This PR optimizes the plotting functions reducing the computational cost of generating calibration plots whith big sets of data. 
The function "groupby()" and the application of any math over the whole data set (like mean()) over a pandas data frame was the bottleneck. When the number of agrupations and the number of stored data increases, the computational cost increases exponentially.

The new function calculates the same output using numpy arrays. Also the data sets has been reduced to the minimal expression needed en each case before making any calculation with them, reducing the execution time.

The new method is 50% faster for big datasets and agruppations made by 1 or 2 columns.

Checklist:
- [ ] Reviewers confirm new code works as expected.
- [ ] Tests are passing.
- [ ] Coverage does not decrease.
- [ ] Documentation is updated.

2023-02-17 13:52 UTC, DavidSarlle commented
@scarrazza @andrea-pasquale can you take a look into this PR? From my side is ready to be merged into main. As described, it implements a way of groupping data frames and afterthat, calculate the mean, avoiding the use of "dataFrame.groupby" method that was causing a bottleneck when loading large sets of data. 

It would be interesting on merging it before the first release of qibocal because, the user will not have live plotting and, when the dataSset is large and we operate over it, the computational cost is to high with the current version of the plotting functions, and the user impression is that the plotting is not working.

Also, when the computational cost is too high, the dash callback enters in an infinite loop where the callback is called before it finish. For that, I have set an initial refreseh time quite hight that gives the callback time to calculate the optimal refresh rate avoiding the eternal loop. 

Now also the dropdown menu for setting the refresh rate has only "auto" and "no refresh" options to avoid the user setting a wrong refresh rate that may cause a eternal loop.

2023-02-21 05:32 UTC, andrea-pasquale requested changes
Thanks for implementing this @DavidSarlle.
I have a few suggestions in the comments, in particular regarding the `grouped_by_mean` function. Let me know if you agree.

2023-02-21 05:32 UTC, andrea-pasquale commented on src/qibocal/plots/rabi.py
> +                    y=mean_phases,  # pylint: disable=E1101
I think that pylint should not complain so probably you can remove it from this line.

2023-02-21 05:32 UTC, andrea-pasquale commented on src/qibocal/plots/spectroscopies.py
> +                    y=mean_measurements * 1e6,  # pylint: disable=E1101
Remove pylint

2023-02-21 05:32 UTC, andrea-pasquale commented on src/qibocal/plots/spectroscopies.py
> +                    y=mean_phases,  # pylint: disable=E1101
Remove pylint

2023-02-21 05:32 UTC, andrea-pasquale commented on src/qibocal/plots/spectroscopies.py
> +        # biass = data.df["bias"].pint.to("V").pint.magnitude.unique()
Remove commented line

2023-02-21 05:32 UTC, andrea-pasquale commented on src/qibocal/plots/spectroscopies.py
> +# Not modified or checked
I understand that you didn't modify this particular plotting method.
I'm guessing that we can remove the comment, right?
Otherwise, you can open an issue to remember to do this in a later stage if needed.

2023-02-21 05:32 UTC, andrea-pasquale commented on src/qibocal/plots/utils.py
> +    and calculates the mean of the given columns m_column1 and m_column2.
This function looks good, however I would suggest to change the arguments from numbers to the column names to increase code readability and maintenance. If I understood correctly in the plotting methods you progressively remove the columns that are no longer needed and then you apply this function passing specific indices which can vary from 0 to 4.  If you use directly column names I think that it will be easier to avoid side effects. Let me know what you think.

2023-02-21 05:33 UTC, andrea-pasquale commented
I forgot to mention that also `pylint` is failing. Please have a look when you have time.

2023-02-21 07:01 UTC, DavidSarlle commented on src/qibocal/web/app.py
> +            interval=160 * 1000,
@andrea-pasquale. The initial value has been increased to a large enough time, to avoid calling the callback method for the second time before the firts call has finished. Right after the end of the callback, in the first call, the refresh rate is calculate, modied and adjusted automatically to the time needed by each function, so the code never waits that long

2023-02-21 07:02 UTC, DavidSarlle commented on src/qibocal/plots/utils.py
> +import numpy as np
Done

2023-02-21 07:03 UTC, DavidSarlle commented on src/qibocal/plots/rabi.py
> +                    y=mean_phases,  # pylint: disable=E1101
Removed

2023-02-21 07:03 UTC, DavidSarlle commented on src/qibocal/plots/spectroscopies.py
> +                    y=mean_measurements * 1e6,  # pylint: disable=E1101
Removed

2023-02-21 07:04 UTC, DavidSarlle commented on src/qibocal/plots/spectroscopies.py
> +        # biass = data.df["bias"].pint.to("V").pint.magnitude.unique()
Removed

2023-02-21 07:05 UTC, DavidSarlle commented on src/qibocal/plots/spectroscopies.py
> +# Not modified or checked
Sorry. It was a personal note. I was adding notes to each routine when I tested the optimization. 
Comment removed.

2023-02-21 07:05 UTC, andrea-pasquale commented on src/qibocal/web/app.py
> +            interval=160 * 1000,
Oh I see. Thank you very much for the explanation.

2023-02-21 07:53 UTC, DavidSarlle commented on src/qibocal/plots/utils.py
> +    and calculates the mean of the given columns m_column1 and m_column2.
@andrea-pasquale change suggested implemented. I totally agree with your comment. Please take a look

2023-02-21 08:49 UTC, andrea-pasquale commented on src/qibocal/plots/utils.py
> +    and calculates the mean of the given columns m_column1 and m_column2.
Thanks @DavidSarlle. Looks good to me.

2023-02-24 07:52 UTC, andrea-pasquale commented
I had a look, this issue has been already reported to pylint PyCQA/pylint#4577.
These errors are false positives generated by the fact that when reading from file it is assume that the object is a `TextFileReader` and not a pandas dataframe.
A possible workaround could to introduce a configuration file for pylint, see for example [here](https://github.com/PyCQA/pylint/issues/4577#issuecomment-1000245962_), otherwise we can manually suppress these error as we were doing before in the code.
What do you suggest @scarrazza?

2023-02-24 10:15 UTC, DavidSarlle commented
@andrea-pasquale @scarrazza we have detected that the computational bottleneck in plotting functions was the agroupation of data where the data in each column of the data frames were quantified using pint. Using pint, all the calculations with a pandas data frame columns were extremely slow. 

After some tests, we have decided to remove the custom "group_by" function using numpy arrays and use the pandas function removing pint. That give us a more flaxible method for agroupations without increasing too much the computational time (compared with the custom fuction using numpy arrays).

For that, the data load uses an auxiliar funcion "load_data" located at plots/utils.py where the df of DataUnits is not quantified, instead of using the data.py --> load_data() function.

I have modified all the plotting methods accordinly, in order to show the correct magnituds that was taking care "pint"

It can be consedered as a first step to remove completly pint from qibocal.

I have tested all the methods and results. From my side is ready to merge as soon as we fix the tests.

2023-02-24 10:15 UTC, DavidSarlle commented
@andrea-pasquale @scarrazza we have detected that the computational bottleneck in plotting functions was the agroupation of data where the data in each column of the data frames were quantified using pint. Using pint, all the calculations with a pandas data frame columns were extremely slow. 

After some tests, we have decided to remove the custom "group_by" function using numpy arrays and use the pandas function removing pint. That give us a more flaxible method for agroupations without increasing too much the computational time (compared with the custom fuction using numpy arrays).

For that, the data load uses an auxiliar funcion "load_data" located at plots/utils.py where the df of DataUnits is not quantified, instead of using the data.py --> load_data() function.

I have modified all the plotting methods accordinly, in order to show the correct magnituds that was taking care "pint"

It can be consedered as a first step to remove completly pint from qibocal.

I have tested all the methods and results. From my side is ready to merge as soon as we fix the tests.

2023-02-24 10:56 UTC, DavidSarlle commented
> I had a look, this issue has been already reported to pylint [PyCQA/pylint#4577](https://github.com/PyCQA/pylint/issues/4577). These errors are false positives generated by the fact that when reading from file it is assume that the object is a `TextFileReader` and not a pandas dataframe. A possible workaround could to introduce a configuration file for pylint, see for example [here](https://github.com/PyCQA/pylint/issues/4577#issuecomment-1000245962_), otherwise we can manually suppress these error as we were doing before in the code. What do you suggest @scarrazza?

@andrea-pasquale  I have been googleling the error "Instance of 'TextFileReader' has no 'xxxx' member" and it indicates that the instance used does not have a 'xxxx' method. In our case, even though you're using a Pandas DataFrame, PyLint is interpreting it as an object of the TextFileReader class. 

Seems that this error is common in PyLint, as it can sometimes have trouble inferring the type of object being used. 

We are sure that the object used is a Pandas DataFrame and not a TextFileReader, so I think we can ignore this PyLint error by using the comment # pylint: disable=E1101 before the line that's giving the error (as we did it before), and in parallel, explore the possibilty of introducing a configuration file for pylint.

2023-02-24 13:21 UTC, andrea-pasquale commented
> @andrea-pasquale @scarrazza we have detected that the computational bottleneck in plotting functions was the agroupation of data where the data in each column of the data frames were quantified using pint. Using pint, all the calculations with a pandas data frame columns were extremely slow.
> 
> After some tests, we have decided to remove the custom "group_by" function using numpy arrays and use the pandas function removing pint. That give us a more flaxible method for agroupations without increasing too much the computational time (compared with the custom fuction using numpy arrays).
> 
> For that, the data load uses an auxiliar funcion "load_data" located at plots/utils.py where the df of DataUnits is not quantified, instead of using the data.py --> load_data() function.
> 
> I have modified all the plotting methods accordingly, in order to show the correct magnituds that was taking care "pint"
> 
> It can be consedered as a first step to remove completly pint from qibocal.
> 
> I have tested all the methods and results. From my side is ready to merge as soon as we fix the tests.

Thanks for the update @DavidSarlle! I'm happy to hear that you were able to found the bottleneck. I'm not surprised that it was `pint`. I will have a closer look later at this PR, but, as you said, I think that this is a first step to remove pint from qibocal.

2023-03-01 08:04 UTC, DavidSarlle commented
@andrea-pasquale @scarrazza have you decided how to fix the false positive errors of pylint? Temporary, I have fixed inserting comments to ignore the errors in the lines causing the errors (as we didi it some time ago).

The last commit also fixes the issue #247.

2023-03-01 08:06 UTC, scarrazza commented
Please disable for those lines.

2023-03-01 09:46 UTC, andrea-pasquale reviewed
Thanks @DavidSarlle.
I'll review the fix for #247 and then we can merge this.

2023-03-01 12:50 UTC, andrea-pasquale commented
Generally the fix for #247 looks good to me.
I've noticed that this branch introduces a bug for `drag_pulse_tuning`. The report is not generated.
Could you please have a look @DavidSarlle ?

2023-03-01 13:43 UTC, DavidSarlle commented
> Generally the fix for #247 looks good to me. I've noticed that this branch introduces a bug for `drag_pulse_tuning`. The report is not generated. Could you please have a look @DavidSarlle ?

thanks @andrea-pasquale for pointing this out. I have fixed the problem. There was a mistake constructing the fitting_report. Now it works.

2023-03-01 14:22 UTC, andrea-pasquale commented
Thanks @DavidSarlle. I've tested it and I can confirm that it works.

2023-03-01 14:22 UTC, andrea-pasquale approved these changes

2023-03-03 11:09 UTC, DavidSarlle commented on src/qibocal/web/app.py
> +        print(int(et - st))
nope! Sorry. I was printing the elapsed time to check the improvements during the plotting in qq-live.
Print removed

2023-03-07 05:08 UTC, andrea-pasquale commented
I think that we can merge this now.
Tests are not passing only for coverage which is fine.

2023-03-07 05:08 UTC, merged