Add workflow for poetry deployment
qiboteam/qibocal pull request #252
Opened 2023-02-20 08:15 UTC by andrea-pasquale

This PR is related to qiboteam/workflows#36 and #249 (second point).
I'm not an expert in workflows so I'm open to suggestions (especially from @AleCandido :) ). 

Checklist:
- [ ] Reviewers confirm new code works as expected.
- [ ] Tests are passing.
- [ ] Coverage does not decrease.
- [ ] Documentation is updated.

2023-02-20 08:43 UTC, Edoardo-Pedicillo requested changes

2023-02-20 08:43 UTC, Edoardo-Pedicillo commented on .github/workflows/deploy.yml
> +  workflow_call:
It does not seem a reusable workflow (otherwise I suggest you move it in the `workflow` repository). You can choose the right trigger [here](https://docs.github.com/en/actions/using-workflows/events-that-trigger-workflows).

2023-02-20 08:50 UTC, andrea-pasquale commented on .github/workflows/deploy.yml
> +  workflow_call:
I was not so sure about this first part. Btw, the workflow is already in `workflows` repository.
Maybe the trigger should be `workflow_dispatch`?

2023-02-20 09:01 UTC, andrea-pasquale commented on .github/workflows/deploy.yml
> +  workflow_call:
I think that something like this should work:
```yaml
on:
  push:
  release:
    types:
      - published
```
which is currently what we have in qibo.

2023-02-20 11:35 UTC, AleCandido commented
https://github.com/NNPDF/eko/blob/master/.github/workflows/pypi.yml
https://github.com/NNPDF/workflows/blob/v2/.github/workflows/python-poetry-pypi.yml

2023-02-20 11:41 UTC, AleCandido approved these changes
Wait to merge until https://github.com/qiboteam/workflows/pull/36 is merged. Fine for the rest :)

2023-02-20 11:58 UTC, andrea-pasquale commented
Thanks. I've already took inspiration from those :) 

> https://github.com/NNPDF/eko/blob/master/.github/workflows/pypi.yml https://github.com/NNPDF/workflows/blob/v2/.github/workflows/python-poetry-pypi.yml

2023-02-21 08:28 UTC, scarrazza commented on .github/workflows/deploy.yml
> +        python-version: [3.8, 3.9, '3.10']
```suggestion
        python-version: [3.8, 3.9, '3.10']
        publish: ${{ github.event_name == 'release' && github.event.action == 'published' && matrix.os == 'ubuntu-latest' && matrix.python-version == '3.9' }}
```

@AleCandido @andrea-pasquale, are we missing this, right?

2023-02-21 08:42 UTC, andrea-pasquale commented on .github/workflows/deploy.yml
> +    uses: qiboteam/workflows/.github/workflows/deploy-pip-poetry.yml@main
```suggestion
    uses: qiboteam/workflows/.github/workflows/deploy-pip-poetry.yml@main
    with:
      os: ${{ matrix.os }}
      python-version: ${{ matrix.python-version }}
      publish: ${{ github.event_name == 'release' && github.event.action == 'published' && matrix.os == 'ubuntu-latest' && matrix.python-version == '3.9' }}
    secrets: inherit
```
This is how it is currently done in Qibo.

2023-02-21 08:42 UTC, andrea-pasquale commented on .github/workflows/deploy.yml
> +        python-version: [3.8, 3.9, '3.10']
Yes, I think so. Although maybe this line should be added below line 16 (see my comment) (?)

2023-02-21 08:42 UTC, AleCandido commented on .github/workflows/deploy.yml
> +        python-version: [3.8, 3.9, '3.10']
Ah, right: for me, every time this workflow is run is just to actually deploy, so I usually do not put such a key.

But if you want to build wheels on `push:` as well you definitely need to filter out this run (you do not want to deploy a version at each push).
And since it is a pure Python package, you'd be building OS independent wheels, so deploying from more than one OS would cause a clash and a workflow failure (even though the wheel would be actually deployed).

2023-02-21 08:48 UTC, andrea-pasquale commented on .github/workflows/deploy.yml
> +    uses: qiboteam/workflows/.github/workflows/deploy-pip-poetry.yml@main
@scarrazza maybe you should add those lines here (if I understood correctly).

2023-02-21 08:50 UTC, scarrazza commented on .github/workflows/deploy.yml
> +    uses: qiboteam/workflows/.github/workflows/deploy-pip-poetry.yml@main
Yes, indeed, but we are missing the filtering key in the workflow, @Edoardo-Pedicillo could you please have a look?

2023-02-21 11:52 UTC, Edoardo-Pedicillo commented on .github/workflows/deploy.yml
> +    uses: qiboteam/workflows/.github/workflows/deploy-pip-poetry.yml@main
After merging qiboteam/workflow#37 we can submit @andrea-pasquale suggested change.

2023-02-21 12:17 UTC, andrea-pasquale commented
My suggestion was not fully correct. Now it should be fine.

2023-02-21 12:56 UTC, merged