Improvements to `ActionBuilder`
qiboteam/qibocal pull request #271
Opened 2023-03-08 09:32 UTC by andrea-pasquale

This PR adds some improvements to the `ActionBuilder` including
> - [ ] @andrea-pasquale  Move the function outside of the `ActionBuilder` (from Stavros comment https://github.com/qiboteam/qibocal/pull/239#discussion_r1109506630): 
 from #257.

I'm keeping this PR as draft for the moment since I also want to fix #267 here.

Checklist:
- [ ] Reviewers confirm new code works as expected.
- [ ] Tests are passing.
- [ ] Coverage does not decrease.
- [ ] Documentation is updated.

2023-04-07 09:26 UTC, andrea-pasquale commented
@wilkensJ when you have time could you please check this PR?

2023-04-10 13:33 UTC, wilkensJ reviewed
So in general multiple things will happen in the next PR, which @vodovozovaliza and me are working on right now, this will also influence this PR:

1. Use a global function for aggregate action function, because many module are sharing the same structure and functions, we will put them in the folder `basics`
2. The amount of fitting parameters will be flexible
3. The plotly figure generation will be a bit different

2023-04-11 08:13 UTC, andrea-pasquale commented on src/qibocal/calibrations/niGSC/XIdrb.py
> +    ] = f"{df_aggr['popt_real'][0]['p2']:.3f} +/- {df_aggr['perr'][0]['p2_err']:.3f}"
![image](https://user-images.githubusercontent.com/49183315/231094154-8fa23cb8-159b-41d3-8287-48c3b673a484.png)

With this adjustment you are able to see the results more clearly and makes the `niGSC` compatible with the other routines.

2023-04-11 08:13 UTC, andrea-pasquale commented on src/qibocal/calibrations/niGSC/basics/plot.py
> +    for subfolder in subfolders:
> Also, `qq` only stores the data from the given actions in `folder/data/` right? Or will that be more flexible in the future? If the data will only be stored in `.../data`, then it could be removed as this is adding more complexity. If it will be more flexible ignore the last comment please.

We could make `qq` more flexible in the future. However you need to keep in mind that in order to create the report the `ActionBuilder` should look for files in certain directories.

2023-04-11 08:13 UTC, andrea-pasquale commented
> So in general multiple things will happen in the next PR, which @vodovozovaliza and me are working on right now, this will also influenSo in general multiple things will happen in the next PR, which @vodovozovaliza and me are working on right now, this will also influence this PR:
> 1. Use a global function for aggregate action function, because many module are sharing the same structure and functions, we will put them in the folder `basics`
> 2. The amount of fitting parameters will be flexible
> 3. The plotly figure generation will be a bit different

Thanks for the feedback @wilkensJ.
I understand that there is a PR that will change multiple things.
I think that this PR should be merged before given that it fixes some annoying issues including #267 and also some other minor problems to improve the compatibility between the rb routines and the rest of the code as you can see in the top comments.
If the fixes proposed in this PR work I suggest to proceed with the merge than we can have a review of the other PR related to the niGSC.

2023-04-11 17:59 UTC, wilkensJ commented
As I see it, one of the main features added to the `niGSC` is the fitting parameter table. I think it is great. Also, moving the method of generating an output folder outside of the `ActionBuilder` class and using it for the `Experiment` class is great.

Regarding the adjustments to the `niGSC` branch, I appreciate your ideas and will definitely take them into consideration, however, I think that it would be more sustainable to align them with the current state or make slight changes from the main branch as Liza and I have some ideas on where the ‘niGSC’ part will go and are currently working on a new PR related to RB modules.

2023-04-12 07:40 UTC, andrea-pasquale commented
> Regarding the adjustments to the `niGSC` branch, I appreciate your ideas and will definitely take them into consideration, however, I think that it would be more sustainable to align them with the current state or make slight changes from the main branch as Liza and I have some ideas on where the ‘niGSC’ part will go and are currently working on a new PR related to RB modules.

If you and @vodovozovaliza are going to modify a few things, to me it is fine.
Regarding this PR, I would like to keep the things which are not included in #293, especially the fix for #267. Let me know what you don't like and I will remove it from this PR.

2023-04-26 10:39 UTC, wilkensJ commented
Hello Andrea,

I would like to ask if you had a chance to look at the comments in the PR as they are still marked as pending. I am sorry if any of the comments lead to misunderstanding, if something is not helpful or confusing in any way, I will be glad to clarify it. Please let us know what we (@vodovozovaliza and me) can do such that we can merge this PR, sorry again for any confusion.

2023-04-27 10:55 UTC, andrea-pasquale commented
Hi @wilkensJ, 
following today's discussion some of the things in this PR may become outdated.
With this PR I only attempted to make the RB part in qibocal more compatible with the rest of the code which is currently in main. I think that this should more or less what we will happen soon when the RB is coded using the autocalibration layout.
I know that several things may not be the best for now since we are still underdevelopment.
If you think that there are some critical changes here that you don't like feel free to open a PR on top of this one to remove those changes and add me as a reviewer. Otherwise we could either merge or close directly this PR.
Let me know what you prefer to do.

2023-04-28 15:29 UTC, vodovozovaliza commented
> Hi @wilkensJ,
> following today's discussion some of the things in this PR may become outdated.
> With this PR I only attempted to make the RB part in qibocal more compatible with the rest of the code which is currently in main. I think that this should more or less what we will happen soon when the RB is coded using the autocalibration layout.
> I know that several things may not be the best for now since we are still underdevelopment.
> If you think that there are some critical changes here that you don't like feel free to open a PR on top of this one to remove those changes and add me as a reviewer. Otherwise we could either merge or close directly this PR.
> Let me know what you prefer to do.

Hello @andrea-pasquale, thank you very much for the improvements to the `ActionBuilder`. There are a few modifications that are important for the current protocols, so @wilkensJ and I think it would be best to create a PR on top of this one to combine the necessary changes and add them to `main`.  I was wondering if it would be possible for you to merge the `main` branch into `simplify_builder` so that we can create a PR on top of it.

2023-05-03 12:06 UTC, andrea-pasquale commented
@wilkensJ @vodovozovaliza after the fixes from #318 this should be ready to merge, right?

2023-05-03 21:27 UTC, vodovozovaliza approved these changes
Thank you very much @andrea-pasquale, everything looks good to me here

2023-05-04 08:19 UTC, wilkensJ commented on src/qibocal/calibrations/niGSC/simulfilteredrb.py
> +        figdict["subplot_title"] = f"Irrep {l[0]}"
I think that this is still not right, sorry I did not see that in the previous PR.

2023-05-04 08:31 UTC, wilkensJ commented
Hello @andrea-pasquale, I hope I did not mess up my review, I resolved the comment which are outdated, was that okay? Or is it making things complicated? There are two comments I did not resolve. It would be great if you could implement them.
Also, if it is not too much work and maybe unnecessary because I oversaw something, could the plotting per qubit be disabled our handled differently? Maybe this is already possible, I am sorry if this is solved already, in this PR it is still not.

For example if this runcard is run:
```yml
backend: numpy

qubits: [0,1,2]

actions:
  simulfilteredrb:
    nqubits: 3
    depths: [1,3,5,7,10]
    runs: 2
    nshots: 1024
    noise_model: PauliErrorOnAll
    noise_params: [0.01, 0.01, 0.01]
```
There will be three reports of the same plots.
Again, sorry if that is fixed already.

2023-05-05 06:40 UTC, vodovozovaliza requested changes

2023-05-05 06:40 UTC, vodovozovaliza commented on src/qibocal/calibrations/niGSC/simulfilteredrb.py
> +        figdict["subplot_title"] = f"Irrep {l[0]}"
```suggestion
        figdict["subplot_title"] = f"Irrep {l}"
```

2023-05-05 06:40 UTC, vodovozovaliza commented on src/qibocal/calibrations/niGSC/basics/fitting.py
> +    Args:
```suggestion

    Args:
```

2023-05-05 06:40 UTC, vodovozovaliza commented on src/qibocal/cli/utils.py
> +    Args:
```suggestion

    Args:
```

2023-05-08 21:40 UTC, andrea-pasquale commented on src/qibocal/calibrations/niGSC/basics/utils.py
> -def experiment_directory(name: str):
This is exactly what I've done in this PR.

2023-05-08 21:44 UTC, andrea-pasquale commented
> Hello @andrea-pasquale, I hope I did not mess up my review, I resolved the comment which are outdated, was that okay? Or is it making things complicated? There are two comments I did not resolve. It would be great if you could implement them. Also, if it is not too much work and maybe unnecessary because I oversaw something, could the plotting per qubit be disabled our handled differently? Maybe this is already possible, I am sorry if this is solved already, in this PR it is still not.
> 
> For example if this runcard is run:
> 
> ```yaml
> backend: numpy
> 
> qubits: [0,1,2]
> 
> actions:
>   simulfilteredrb:
>     nqubits: 3
>     depths: [1,3,5,7,10]
>     runs: 2
>     nshots: 1024
>     noise_model: PauliErrorOnAll
>     noise_params: [0.01, 0.01, 0.01]
> ```
> 
> There will be three reports of the same plots. Again, sorry if that is fixed already.

Thanks for the review @wilkensJ and @vodovozovaliza.
This feature is already implemented within the autocalibration layout and it will require some work to add it in the old layout. Since all routines will eventually move to the new layout I think that we could avoid to implement this feature here. Let me know if you agree.

2023-05-10 05:10 UTC, vodovozovaliza approved these changes

2023-05-10 05:12 UTC, vodovozovaliza approved these changes

2023-05-10 10:38 UTC, vodovozovaliza commented
The examples in the documentation will be outdated once the branch is merged. Is it okay if I create a separate PR for them when we merge this PR?

2023-05-15 09:45 UTC, wilkensJ approved these changes

2023-05-16 06:44 UTC, merged