ponchout fitting
qiboteam/qibocal pull request #272
Opened 2023-03-09 18:01 UTC by DavidSarlle

This Pr implemnets the data fitting for resonator punchout, returning the resonator frequency / attenuation  at high and low power

Checklist:
- [ ] Reviewers confirm new code works as expected.
- [ ] Tests are passing.
- [ ] Coverage does not decrease.
- [ ] Documentation is updated.

2023-03-09 18:03 UTC, DavidSarlle commented
More fitting tests with real data on qubits should be done.

2023-03-23 08:45 UTC, DavidSarlle commented
@andrea-pasquale the PR ius ready to be reviewed. Yo can test it with real data that I collected last week. It is in my server data folder:

/home/users/david.fuentes/20230321_qw25q_punchout_A1A2A3A4A5A6

Only one comment for your information. When the fitting point obtained is in the limit of the plot, plotly auto resizes the plot with a void data row or column. It is not possible to fix it but it is something more asthetics than funcional. 

![image](https://user-images.githubusercontent.com/39095664/227147465-7e9da7cb-4c3a-4eb8-818f-f60dd02a65ab.png)

2023-03-24 08:09 UTC, DavidSarlle commented
@andrea-pasquale now that i can test the fitting in qq-live, I can see that there is a bug. Do not review until I fix it.

2023-03-31 13:54 UTC, andrea-pasquale commented
> After fixing some bugs in Qibolab driver and in the routine itself, the PR is now working and tested with the qibolab PR #356. As soon as we merge qibolab PR #356 it into main, it is ready to be reviewed and merged.

Thanks @DavidSarlle.
I've moved the fix to qiboteam/qibolab#335 which should be merged sooner.

2023-04-03 15:42 UTC, DavidSarlle commented
@andrea-pasquale @aorgazf hte PR is ready to be reviwed. I have also include the fitting for the "punchout amplitude".

2023-04-04 14:00 UTC, andrea-pasquale reviewed
Thanks @DavidSarlle.
I've tested the code and it seems to work as expected.

I will double check exactly how the fitting for the punchout is working.

2023-04-10 12:37 UTC, andrea-pasquale requested changes
I had a closer look at this PR and there some things which could be improved (see comments) let me know if you agree @DavidSarlle.

2023-04-10 12:37 UTC, andrea-pasquale commented on src/qibocal/fitting/utils.py
> +    return (x_mags - np.min(x_mags)) / (np.max(x_mags) - np.min(x_mags))
I believe that this function is also defined in the punchout plotting [function](https://github.com/qiboteam/qibocal/blob/9a27c90074150cec3106010a16b2c104011ca451/src/qibocal/plots/spectroscopies.py#L217).
To avoid code duplication could you please remove it and call directly this function?

2023-04-11 09:31 UTC, DavidSarlle commented on runcards/actions_qq_1q.yml
All actions commented

2023-04-11 09:32 UTC, DavidSarlle commented on runcards/actions_qq_5q.yml
All actions commented

2023-04-11 09:32 UTC, DavidSarlle commented on src/qibocal/fitting/methods.py
> +            log.warning("spin_echo_fit: the fitting was not succesful")
Done.

2023-04-11 09:44 UTC, DavidSarlle commented on src/qibocal/fitting/methods.py
> +            y = [point[1] for point in min_points]
This code is not going to work. Depending on the resonator type we should find max or mins. I also prefer to put the code in a separate routine that can be reused to find mins or max in any heatmap. Let me know if you are agree.

2023-04-11 09:45 UTC, DavidSarlle commented on src/qibocal/fitting/methods.py
> +            middle_y = abs(y[np.argmax(y)] - y[np.argmin(y)]) / 2
Removed middle_y var

2023-04-11 09:48 UTC, DavidSarlle commented on src/qibocal/fitting/utils.py
> +    max_freq = statistics.mode(freqs)
I have tried also with mean, and the best option is to obtain the most repeated frequency in all the mins or max obtained.

2023-04-11 09:50 UTC, DavidSarlle commented on src/qibocal/fitting/methods.py
> +            hp_points, lp_points = split_list_by_threshold(min_points, middle_x)
You are right.  Done

2023-04-11 09:55 UTC, DavidSarlle commented on src/qibocal/fitting/utils.py
> +    return (x_mags - np.min(x_mags)) / (np.max(x_mags) - np.min(x_mags))
Right. Done

2023-04-11 09:58 UTC, DavidSarlle commented on src/qibocal/plots/spectroscopies.py
> +                    f"q{qubit}/r{report_n} | Freq@Lp: {params['freq_lp']} Hz.<br>"
Modified to:

                title_text += (
                    f"q{qubit}/r{report_n} | Resonator Frequency at Low Power: {params['freq_lp']} Hz.<br>"
                )
                title_text += f"q{qubit}/r{report_n} | Low Power Attenuation Range: {params['lp_max_att']} - {params['lp_min_att']} db.<br>"
                title_text += (
                    f"q{qubit}/r{report_n} | Resonator Frequency at High Power: {params['freq_hp']} Hz.<br>"
                )
                title_text += f"q{qubit}/r{report_n} | High Power Attenuation Range: {params['hp_max_att']} - {params['hp_min_att']} db.<br>"

2023-04-11 19:46 UTC, Edoardo-Pedicillo reviewed
Thank @DavidSarlle.
Please find below a few comments.

2023-04-11 19:46 UTC, Edoardo-Pedicillo commented on src/qibocal/fitting/methods.py
> +            min_x = x[np.argmin(x)]
```suggestion
            max_x = np.amax(x)
            min_x = np.amin(x)
```

2023-04-11 19:46 UTC, Edoardo-Pedicillo commented on src/qibocal/fitting/methods.py
> +            min_points = [[q.magnitude for q in tupla] for tupla in min_points]
I don't know if it will works, if `min_points` is a numpy array/matrix, you can try [vectorize](https://numpy.org/doc/stable/reference/generated/numpy.vectorize.html)

2023-04-11 19:46 UTC, Edoardo-Pedicillo commented on src/qibocal/fitting/methods.py
> +            y = [point[1] for point in min_points]
if `min_points` is a np matrix you can use this syntax
```suggestion
            x = min_points[: ,0]
            y = min_points[:, 1]
```

2023-04-19 07:16 UTC, DavidSarlle commented
@andrea-pasquale @Edoardo-Pedicillo @scarrazza @aorgazf  all the changes proposed by @Edoardo-Pedicillo has been implemented in PR #290 for the automation of the calibration. shall we add the fitting for the actions executed with the ActionBuilder? The qblox sweepers are almost ready so, probably the qq-live is going to be deprecated soon. That means that we will use tree executor to characterize qubits. Please let me know if I have to introduce the changes here or I can close the PR.

2023-04-20 13:15 UTC, andrea-pasquale commented
Thanks @DavidSarlle.
I think that probably we can close this PR.

2023-04-21 07:32 UTC, DavidSarlle commented
Implemented in PR #290

2023-04-21 07:32 UTC, closed without merging