David/fixes split data fit
qiboteam/qibocal pull request #324
Opened 2023-05-05 10:53 UTC by DavidSarlle

This branch contins some fixes for PR #279. 

Mostly fixes:
- Lorentzian fit failures
- Flipping fit
- Drag tunning fit
- some minor changes in plotting

Checklist:
- [ ] Reviewers confirm new code works as expected.
- [ ] Tests are passing.
- [ ] Coverage does not decrease.
- [ ] Documentation is updated.

2023-05-08 09:24 UTC, Edoardo-Pedicillo approved these changes

2023-05-08 19:27 UTC, andrea-pasquale requested changes
Thanks @DavidSarlle for implementing this.
Please find below a few comments, nothing critical just some minor changes.

2023-05-08 19:27 UTC, andrea-pasquale commented on src/qibocal/protocols/characterization/allxy/allxy.py
> +            count += 1
`count` can be removed I think

2023-05-08 19:27 UTC, andrea-pasquale commented on src/qibocal/protocols/characterization/allxy/allxy.py
> +                data.add(r)
Here I believe that the indentation was corrected before. Did you test it?

2023-05-08 19:27 UTC, andrea-pasquale commented on src/qibocal/protocols/characterization/utils.py
> +        }
I think that this part is not needed.
It should already be in `_fit` of `resonator_spectroscopy`.

2023-05-08 19:27 UTC, andrea-pasquale requested changes
Thanks @DavidSarlle for implementing this.
Please find below a few comments, nothing critical just some minor changes.

2023-05-09 08:36 UTC, DavidSarlle commented on runcards/actions_qq.yml
Done

2023-05-09 08:37 UTC, DavidSarlle commented on runcards/autocalibration_qblox.yml
Done

2023-05-09 08:38 UTC, DavidSarlle commented on src/qibocal/protocols/characterization/allxy/allxy_drag_pulse_tuning.py
> +    # repeat the experiment as many times as defined by software_averages
Done

2023-05-09 08:42 UTC, DavidSarlle commented on src/qibocal/protocols/characterization/classification.py
> +                "nshots": [params.nshots] * params.nshots,
removed

2023-05-09 08:42 UTC, DavidSarlle commented on src/qibocal/protocols/characterization/classification.py
> +                "nshots": [params.nshots] * params.nshots,
removed

2023-05-09 08:43 UTC, DavidSarlle commented on src/qibocal/protocols/characterization/classification.py
> +            columns=["qubit", "MSR", "phase", "nshots"]
removed

2023-05-09 08:43 UTC, DavidSarlle commented on src/qibocal/protocols/characterization/classification.py
> +        + f"q{qubit} | assignment fidelity: {fit.assignment_fidelity[qubit]:.3f} <br>"
Done

2023-05-09 08:45 UTC, DavidSarlle commented on src/qibocal/protocols/characterization/flipping.py
> +            + f"q{qubit} | corrected_amplitude: {fit.amplitudes[qubit][0]:.4f}<br><br>"
Done

2023-05-09 09:09 UTC, DavidSarlle commented on src/qibocal/protocols/characterization/classification.py
> +        rotation_angles[qubit] = rotation_angle
I removed from here and changed in the driver on update the runcard. But better to do it here.

2023-05-09 09:10 UTC, DavidSarlle commented on src/qibocal/protocols/characterization/classification.py
> +        rotation_angles[qubit] = rotation_angle
Fixed

2023-05-09 09:25 UTC, DavidSarlle commented on src/qibocal/protocols/characterization/utils.py
> +        }
At the very beggining was in inside the lorentzian_fit. Sorry, I did not update after someone change it. 
Fixed

2023-05-10 10:13 UTC, merged