Add execution parameters, new results and new sweep routines to autocalibration routines
qiboteam/qibocal pull request #326
Opened 2023-05-08 08:47 UTC by Jacfomg

Checklist:
- [ ] Reviewers confirm new code works as expected.
- [ ] Tests are passing.
- [ ] Coverage does not decrease.
- [ ] Documentation is updated.

2023-05-16 11:18 UTC, maxhant requested changes

2023-05-16 11:18 UTC, maxhant commented on src/qibocal/protocols/characterization/classification.py
> +        ),
```suggestion
        ExecutionParameters(
            nshots=params.nshots,
            acquisition_type=AcquisitionType.INTEGRATION,
        ),
```

2023-05-16 11:18 UTC, maxhant commented on src/qibocal/protocols/characterization/classification.py
> +        acquisition_type=AcquisitionType.INTEGRATION,
```suggestion
  ExecutionParameters(
              nshots=params.nshots,
              acquisition_type=AcquisitionType.INTEGRATION,
          ),
```

2023-05-16 11:18 UTC, maxhant commented on src/qibocal/protocols/characterization/allxy/allxy.py
> +            ),
```suggestion
            ExecutionParameters(
                averaging_mode=AveragingMode.CYCLIC,
            ),
```

2023-05-16 11:24 UTC, Jacfomg commented on src/qibocal/protocols/characterization/classification.py
> +        ),
Fixed the routine to take relaxation time

2023-05-16 11:25 UTC, Jacfomg commented on src/qibocal/protocols/characterization/allxy/allxy.py
> +            ),
same as above, fixed ExecutionParameters missing

2023-05-16 11:25 UTC, Jacfomg commented on src/qibocal/protocols/characterization/classification.py
> +        acquisition_type=AcquisitionType.INTEGRATION,
same as above, fixed ExecutionParameters missing

2023-05-19 06:41 UTC, andrea-pasquale commented
@Jacfomg I will review this PR soon.
In the meantime could you do the following please:

1. merge main
2. update the lock file to point to the qiboteam/qibolab#400 so that we can see if tests are passing here or not.
Here is an example of what I did in #342
https://github.com/qiboteam/qibocal/blob/ef23eedbfe471c302e219fd4d2fe456a4ec5a6f6/pyproject.toml#L19
in your case you just need to replace the branch with `execute_branch` then run `poetry lock` and push both the pyproject.toml and the poetry.lock file.
If you have any problem with that I can also do it.

2023-05-19 09:50 UTC, Jacfomg commented
It seems like all the tests are failing because of pint or something

2023-05-19 09:52 UTC, andrea-pasquale commented
This is also what I saw locally. I had a chat with @Edoardo-Pedicillo   yesterday about it. We will open a PR to fix this issue.

2023-05-19 14:33 UTC, Jacfomg commented
Tests are a bit slow I may did something not right on the dummy, maybe revise it

2023-05-22 07:45 UTC, rodolfocarobene commented on src/qibocal/protocols/characterization/allxy/allxy.py
> +                averaging_mode=AveragingMode.CYCLIC,
```suggestion
                averaging_mode=AveragingMode.SINGLESHOT,
```
This should be singleshot right? Otherwise probabilities do not really make sense (also for other allxy routines)

2023-05-22 08:07 UTC, Jacfomg commented on src/qibocal/protocols/characterization/allxy/allxy.py
> +                averaging_mode=AveragingMode.CYCLIC,
You will get a value between 0 and 1 from the averaging. I don't see a problem with that.

2023-05-22 08:14 UTC, rodolfocarobene commented on src/qibocal/protocols/characterization/allxy/allxy.py
> +                averaging_mode=AveragingMode.CYCLIC,
Here we are averaging and classifying, maybe the problem is that I first average and than classify while you first classify and then average...
But then in the StateResult there will be something that is not 0-1 (if you average after classification) and I thought that this is not wanted

2023-05-22 08:31 UTC, Jacfomg commented on src/qibocal/protocols/characterization/allxy/allxy.py
> +                averaging_mode=AveragingMode.CYCLIC,
Yes, I do first classification and the average. And also, the AveragedStateResults are expected not to be 0 or 1. Just a value in between so the results are the same as the old AllXY

2023-05-23 14:30 UTC, andrea-pasquale commented on tests/runcards/single_routines.yml
> +      relaxation_time:
Could we make these arguments optional?

2023-05-25 08:59 UTC, andrea-pasquale approved these changes

2023-05-25 08:59 UTC, merged