Add optional local qubits parameter
qiboteam/qibocal pull request #351
Opened 2023-05-23 14:06 UTC by andrea-pasquale

Closes #301 and this point
> - [ ] qubits argument (see first presentation of new layout)

from #336.

This PR adds a local `qubits` parameter for each routine.
If this parameter is not provided it will be used the global parameter `qubits`, if provided it will overwrite the global parameter.
Probably this is not enough for supporting two qubit gates routines.
We could address this in another PR once we port two qubit gates to the new layout.

Checklist:
- [ ] Reviewers confirm new code works as expected.
- [ ] Tests are passing.
- [ ] Coverage does not decrease.
- [ ] Documentation is updated.

2023-06-05 14:23 UTC, stavros11 approved these changes
It looks good to me, thanks. I did a quick test using the resonator spectroscopy routines and the `qubits` parameter seems to work as expected. A real test for this would be to port the two-qubit gate routines and try to use the local qubits parameter for them but I guess this can be done in a separate PR (ideally using this).

2023-06-05 14:40 UTC, andrea-pasquale commented on src/qibocal/protocols/characterization/allxy/drag_pulse_tuning.py
> +    qubits: Optional[list] = field(default_factory=list)
Thanks @stavros11.
Yes, you are right. I believe that it can be dropped.

2023-06-05 14:46 UTC, andrea-pasquale commented on src/qibocal/cli/auto_builder.py
> +        return local_qubits if local_qubits else self.qubits
I think that this should be `>0`, right?

2023-06-05 14:55 UTC, stavros11 commented on src/qibocal/cli/auto_builder.py
> +        return local_qubits if local_qubits else self.qubits
Yes, sorry, you are right, it should be `>0`.

2023-06-05 15:08 UTC, AleCandido commented on src/qibocal/cli/utils.py
> +        return qubit_ids
```suggestion
    return qubit_ids
```

2023-06-05 15:08 UTC, AleCandido commented on src/qibocal/protocols/characterization/allxy/allxy.py
> +    ] = False  # False because this routine does not update the runcard
Is this really an `Optional[bool]`?

An `Optional[bool]` is a variable that can be `False`, `True`, or `None`.
If this is *optional* in the sense that has a default, the type should just be `bool`.

2023-06-05 15:08 UTC, AleCandido commented on src/qibocal/protocols/characterization/allxy/allxy_drag_pulse_tuning.py
> +    ] = False  # False because this routine does not update the runcard
Same as above.

2023-06-05 15:08 UTC, AleCandido commented on src/qibocal/cli/utils.py
> +        return qubit_ids
And since you're actually defining now, definitely place somewhere else...

2023-06-05 15:08 UTC, AleCandido commented on src/qibocal/protocols/characterization/allxy/drag_pulse_tuning.py
> +    update: Optional[bool] = None
Are you sure that it shouldn't be:
```suggestion
    update: bool = False
```
as for the others?

2023-06-05 15:08 UTC, AleCandido commented on src/qibocal/protocols/characterization/classification.py
> +    update: Optional[bool] = None
As above

2023-06-05 15:08 UTC, AleCandido commented on src/qibocal/protocols/characterization/resonator_spectroscopy.py
> +    update: Optional[bool] = None
If you are actually adding to all parameters, then we need a better mechanism them parameters.

Let's pull the `update` key out of them.

2023-06-05 15:11 UTC, AleCandido commented on tests/runcards/test_autocalibration.yml
> +      update: False
If you want to add a routine default for some routines, define an attribute (e.g. just `update`) for the routine class itself, and check it during execution. If the key is missing, use the local default (per-routine), otherwise the global default.

2023-06-05 17:19 UTC, andrea-pasquale commented on tests/runcards/test_autocalibration.yml
> +      update: False
Thanks @AleCandido.
Indeed this is a good idea.
I think that we can do the same for the `qubits` argument, right?

2023-06-05 17:35 UTC, AleCandido commented on tests/runcards/test_autocalibration.yml
> +      update: False
Definitely.

Unfortunately, I've never reviewed the routines themselves, and I had not realized it was there.
Moreover, there was already a plan for `qubits`, so it is very relevant to have it outside (even though I thought it was something that should have been global, but if you need per routine add it, at most we can have in both places, or turn it into something like `exclude-qubits` per routine, according to the most common use case).

2023-06-05 18:11 UTC, andrea-pasquale commented on src/qibocal/auto/task.py
> +from qibocal.cli.utils import allocate_qubits
You are right. Since this function is utils by both `cli` and `auto` module I decided to put in a generic utils.py.
This should avoid circular imports. Let me know if you agree.

2023-06-05 18:17 UTC, andrea-pasquale commented on tests/runcards/test_autocalibration.yml
> +      update: False
Actually this PR originally implemented this additional argument `qubits`, this is why you never saw it.
People have asked for more flexibility when choosing on which qubits to run protocols see #301.

2023-06-05 18:20 UTC, andrea-pasquale commented on tests/runcards/test_autocalibration.yml
> +      update: False
I've just pushed the implementation that you suggested.
We could even go a step further and do the same for `nshots` and `relaxation_time` given that they are common to all the routines. I'm not too sure given that they are parameters of the routine itself. Thoughts @stavros11 @rodolfocarobene @Jacfomg?

2023-06-06 07:48 UTC, AleCandido commented on src/qibocal/auto/execute.py
> +    update: Optional[bool] = True
Second iteration: are you sure you need an `Optional[bool]` and not just a `bool` with a default?

2023-06-06 07:48 UTC, AleCandido commented on src/qibocal/auto/execute.py
> +                # - local update is True
Great, but better lifted in the docstring ;)

2023-06-06 07:48 UTC, AleCandido commented on src/qibocal/auto/runcard.py
> +    qubits: Optional[list] = Field(default_factory=list)
```suggestion
    qubits: Optional[list[QubitID]] = Field(default_factory=list)
```
maybe?

2023-06-06 07:48 UTC, AleCandido commented on src/qibocal/auto/task.py
> +        return self.action.update
Since they start to be a lot of properties following this pattern, I wonder if it would be less redundant to have a `from_action` constructor, and put all of these as regular fields.

The only advantage of the current layout is that they are *read-only* (if you do not access the internal object, of course).

It can (and probably should) be tackled in a separate PR, we can make an issue for this.

2023-06-06 07:48 UTC, AleCandido commented on src/qibocal/cli/utils.py
> +from qibolab.platform import Platform
This new import seems to be unused... (it is new, and there is no more new code)

2023-06-06 07:48 UTC, AleCandido commented on src/qibocal/cli/utils.py
> +from qibolab.platform import Platform
Since this pattern appears also in next files, I added myself #385, and I'm going to run on this PR before proceeding

2023-06-06 07:50 UTC, AleCandido commented
I changed base just to reduce the number of files changed. #385 is a very tiny PR, so (I hope) it should become soon enough `main` again.

2023-06-06 08:08 UTC, andrea-pasquale commented on src/qibocal/auto/runcard.py
> +    qubits: Optional[list] = Field(default_factory=list)
You are right

2023-06-06 08:08 UTC, andrea-pasquale commented on src/qibocal/auto/execute.py
> +    update: Optional[bool] = True
Yep,`Optional` is not needed

2023-06-06 08:10 UTC, andrea-pasquale commented on src/qibocal/auto/task.py
> +        return self.action.update
Also to me it feels like we are redundant. I've opened an issue for this (#386)

2023-06-06 08:13 UTC, andrea-pasquale commented
Thanks for the second review @AleCandido.
I've implemented your suggestions.

2023-06-06 08:38 UTC, AleCandido commented on src/qibocal/auto/execute.py
> +                # - local update is True
Since you lifted, you can also remove from here: it's just written a few lines above ;)

2023-06-06 08:38 UTC, AleCandido commented on src/qibocal/web/templates/autocalibration.html
> +        {% for qubit in report.routine_qubits(routine, iteration) %}
Even here: `(routine, iteration)` is a `task.uid`.

2023-06-06 08:38 UTC, AleCandido commented on src/qibocal/utils.py
> +    return qubit_ids
```suggestion
def allocate_qubits(platform: Platform) -> Dict[QubitId, Qubit]:
    """Convert List[QubitId] -> Dict[QubitId, Qubit] for non-trivial platform."""
    return {q: platform.qubits[q] for q in qubit_ids if q in platform.qubits}
```
Make it simpler: the `None` check you can do before calling the function, and in this way the function have one less argument and a well-defined return type.

Moreover, with the current implementation the `platform` type would be even *slightly wrong*: it should be `Optional[Platform]`.

2023-06-06 12:14 UTC, andrea-pasquale commented on src/qibocal/cli/auto_builder.py
> +    def routine_qubits(self, routine_name, iteration):
Implemented

2023-06-06 12:17 UTC, andrea-pasquale commented on src/qibocal/auto/runcard.py
> +    qubits: Optional[list] = Field(default_factory=list)
Actually with this modification the code doesn't work.
I think that it might be related to the fact that we are reading a list directly from a yaml. I need to investigate more about this.

2023-06-06 12:35 UTC, AleCandido commented on src/qibocal/auto/task.py
> +UId = tuple[Id, int]
At a second thought: maybe better `TaskId`, because it is completely unclear what it is outside this scope (and it is used outside).

2023-06-06 12:35 UTC, AleCandido commented on src/qibocal/auto/task.py
> +"""Useful type for Task."""
```suggestion
"""Unique identifier for executed tasks."""
```

2023-06-06 13:11 UTC, andrea-pasquale commented on src/qibocal/auto/runcard.py
> +    qubits: Optional[list] = Field(default_factory=list)
To reproduce the error you can just run one of the protocols in this [runcard](https://github.com/qiboteam/qibocal/blob/qubit_local/runcards/actions_qq_auto.yml)

2023-06-06 13:17 UTC, AleCandido commented on src/qibocal/auto/runcard.py
> +    qubits: Optional[list] = Field(default_factory=list)
Try with this: https://docs.pydantic.dev/latest/usage/model_config/#smart-union

2023-06-06 13:34 UTC, andrea-pasquale commented on src/qibocal/auto/runcard.py
> +    qubits: Optional[list] = Field(default_factory=list)
Thanks, now it works.

2023-06-06 15:19 UTC, andrea-pasquale commented on src/qibocal/auto/runcard.py
> +    qubits: Optional[list] = Field(default_factory=list)
I guess that it will be interesting to add it everywhere to have more control in a  separate PR.

2023-06-07 09:44 UTC, maxhant requested changes

2023-06-07 09:44 UTC, maxhant commented on src/qibocal/utils.py
> +    return {q: platform.qubits[q] for q in qubit_ids if q in platform.qubits}
```suggestion
def allocate_qubits(
    platform: Optional[Platform], qubit_ids: List[QubitId]
) -> Union[List[QubitId], Dict[QubitId, Qubit]]:
    """Convert List[QubitId] -> Dict[QubitId, Qubit] for non-trivial platform."""
    qubits = {}
    for q in qubit_ids:
        if not isinstance(q, list) and q in platform.qubits:
            qubits[q] = platform.qubits[q]
        else:
            qubits[tuple(sorted(q))] = platform.pairs[tuple(sorted(q))]
    return qubits
```

2023-06-07 10:09 UTC, AleCandido commented on src/qibocal/cli/auto_builder.py
> +    def routine_qubits(self, task_uid: TaskId):
Tiny simplification: in this context (same below), you can also just call it `task`. The type is already telling you that is a `TaskId`, so that's enough :)
```suggestion
    def routine_qubits(self, task: TaskId):
```

2023-06-07 10:10 UTC, AleCandido commented on src/qibocal/utils.py
> +    platform: Optional[Platform], qubit_ids: list
```suggestion
    platform: Optional[Platform], qubit_ids: List[QubitId]
```
Keep the type as specific as possible (unless you really want to allow for a whatever list to be passed).

2023-06-07 10:16 UTC, AleCandido commented on src/qibocal/utils.py
> +    return {q: platform.qubits[q] for q in qubit_ids if q in platform.qubits}
@maxhant I believe that the hint is not exact, what you meant is not that you have a dictionary with either a single qubit or tuples, but rather:
```py
dict[Union[QubitId, Tuple[QubitId, QubitId]], Union[Qubit, QubitPair]]
```
i.e. you have a dict with both type of keys and values allowed.

I know it is unpleasant, because you would like to specify that a certain type of key is only associated to a certain type of value, but this is not possible with dictionaries (it is not something that you can guarantee at compile time).

However, exactly because of this, I'd rather propose to have two dictionaries, so to have something closer to your type:
```py
Tuple[dict[QubitId, Qubit], dict[Tuple[QubitId,QubitId], QubitPair]]
```
Even better if this could be done in two separate functions ^^

2023-06-07 10:42 UTC, maxhant commented
@andrea-pasquale 

I've re-merged this branch to #384 and it is crashing again:

```
  File "pydantic/dataclasses.py", line 325, in pydantic.dataclasses._add_pydantic_validation_attributes.new_init
    # had __set_name__ called on it at the right time.
  File "pydantic/dataclasses.py", line 425, in pydantic.dataclasses._dataclass_validate_values
    
pydantic.error_wrappers.ValidationError: 2 validation errors for Runcard
actions -> 0 -> qubits -> 0
  str type expected (type=type_error.str)
actions -> 0 -> qubits -> 0
  value is not a valid integer (type=type_error.integer)
```

2023-06-07 11:14 UTC, AleCandido commented
> @andrea-pasquale
> 
> I've re-merged this branch to #384 and it is crashing again:

Thanks @maxhant to report this.

We definitely need `qubits` in the autocalibration tests, not only to remove `Optional`[*], but actually to check that the loading is properly working.

[*]: that of course I like

2023-06-07 14:17 UTC, AleCandido reviewed
For me, this PR is only missing `qubits:` key tests
https://github.com/qiboteam/qibocal/pull/351#issuecomment-1580563872

2023-06-07 14:40 UTC, andrea-pasquale commented
> For me, this PR is only missing `qubits:` key tests
> https://github.com/qiboteam/qibocal/pull/351#issuecomment-1580563872

Ok, I can do that.

2023-06-08 17:04 UTC, AleCandido commented on src/qibocal/auto/task.py
> +        self._qubits = qubits
Nice: this is a fully useless property (`self.qubits` is exactly following `self._qubits`) and the underlying attribute is even undeclared (not appearing in `__init__`, i.e. the class attributes from which `__init__` is generated)

2023-06-08 17:04 UTC, AleCandido commented on src/qibocal/auto/task.py
> +        self._qubits = qubits
Can't we just have `qubits` as a class attribute?

2023-06-08 17:04 UTC, AleCandido commented on src/qibocal/auto/task.py
> +                self.qubits = list(qubits.keys())
```suggestion
                self.qubits = list(qubits)
```
`list()` is creating a list out of an iterable. The default iteration on `dict`s return keys :)

2023-06-08 17:04 UTC, AleCandido commented on src/qibocal/auto/task.py
> +            if qubits:
Is `qubits` a boolean?

Otherwise, formulate a condition with it.
(when is `qubits` falsy?)

2023-06-08 17:06 UTC, andrea-pasquale commented on src/qibocal/auto/task.py
> +        self._qubits = qubits
Yeah, I know. I pushed this version but I'm currently working on a different approach. Thanks!

2023-06-08 17:06 UTC, andrea-pasquale commented on src/qibocal/auto/task.py
> +            if qubits:
It was just a shortcut to check if the list/dict was empty.

2023-06-08 17:28 UTC, AleCandido commented on src/qibocal/auto/task.py
> +            if qubits:
```suggestion
            if len(qubits) > 0:
```

2023-06-08 17:39 UTC, AleCandido commented on src/qibocal/auto/runcard.py
> +    update: bool = None
I guess you wanted:
```suggestion
    update: bool = False
```

2023-06-08 17:42 UTC, AleCandido commented on src/qibocal/auto/task.py
> +            self.qubits = self.action.qubits
Actually, why do we need two mechanisms for `qubits`?

I'm now wondering in which cases the `qubits` of the task are different from the `qubits` in the underlying action...

2023-06-08 17:42 UTC, AleCandido commented on src/qibocal/auto/task.py
> +            if len(qubits) != 0:
```suggestion
                if len(self.qubits) > 0:
                    qubits = allocate_qubits(platform, self.qubits)
            if len(qubits) > 0:
```

As specific as possible :)

2023-06-08 17:43 UTC, andrea-pasquale commented on src/qibocal/auto/runcard.py
> +    update: bool = None
No actually `None` is correct, since this is the local update relative to a protocol, which can be absent.

2023-06-08 17:47 UTC, andrea-pasquale commented on src/qibocal/auto/task.py
> +            self.qubits = self.action.qubits
They are not, but since action is also an attribute of the task this is a possible solution.
The reason why I'm adding a qubit attribute (or before with the property) is that I want to achieve the following:
if a local argument qubit is not passed I want it to be overwritten by the global parameter qubits. In this when I perform tests 
https://github.com/qiboteam/qibocal/blob/3b263246bd8f2d2a8e00a4e89eb9a5cb933b5fc2/tests/test_task_options.py#L44
I can check whether the task run with the global qubits or with the local qubits.
I'm sure that there is a better way to do it. This is what I came up with.

2023-06-08 17:47 UTC, andrea-pasquale commented on src/qibocal/auto/task.py
> +            if len(qubits) != 0:
Already fixed :)

2023-06-08 18:13 UTC, AleCandido commented on src/qibocal/auto/runcard.py
> +    update: bool = None
But then we are back to the wrong type hint: it is not a `bool`, that can only be `True` or `False`, not `None`.

If `update`:
- is a toggle, keep it a `bool`, and if it can be absent, just choose what is the default value (out of the two allowed)
- if it's an object, then it is not a bool, and if it can be absent, it should be `Optional[MyUpdate]`, and you can set to `None`

But `None` can't be a `bool`. And definitely, do not use an `Optional[bool]`, because this is just 3-state logic (and I believe you will end up acting as if it were one of the other two values).

2023-06-08 18:22 UTC, andrea-pasquale commented on src/qibocal/auto/runcard.py
> +    update: bool = None
I feel like we are over complicating things. It is an optional value that the user can provide.
I cannot put a default value (`True`/`False`) since by providing a value to a local parameter, the local parameter will overwrite the global option which is something that I don't want. If no local option is provided the program should choose the global option.


 

> And definitely, do not use an `Optional[bool]`, because this is just 3-states logic (and I believe you will end up acting as if it were one of the other two values).

I feel like in this case this is exactly what I want. Since my scenario should be the following:

1. if local is provided it will overwrite the global option
2. if local is not provided (`local == None`) the program should use the global option


> But `None` can't be a `bool`.

I agree with this.

2023-06-08 18:28 UTC, AleCandido commented on src/qibocal/auto/task.py
> +            self.qubits = self.action.qubits
Having considered the alternatives, this is a good idea. Sorry if I've been slow :)

2023-06-08 21:23 UTC, AleCandido commented on src/qibocal/auto/runcard.py
> +    update: bool = None
You're creating more cases than needed.

I understand the logic of locally prevailing definition (i.e. scopes), but here I believe it could be much simpler.

- by default, you run the autocalibration to update the runcard, so you can make the assumptions you're always updating
- if you want to disable this option for some routines, you can set the local `update` key to `False`, for each of them that you want to set to `False`
- the only reason to set the global one to `False` is to never update

I believe that you had in mind something like "if I have more `False`, I set the global to `False` and switch the few different ones explicitly, otherwise I do the opposite". And that's why you'd like to set an overwritable default.
But this makes all the logic more complicate, because you're allowing every time for two complementary ways of setting the same configuration (global `False` and set only local `True`s, or the opposite).

Instead, only the local key is required to have the full flexibility, so in principle you could avoid having the global one at all.
But for the special (and arguably relevant [*]) case of disabling update for all, you can provide the global key.

[*]: I actually don't know how much this is going to be used; if no one is using it, we can really avoid defining the global key

2023-06-09 06:07 UTC, andrea-pasquale commented on src/qibocal/auto/runcard.py
> +    update: bool = None
To me this is fine. Since we were discussing about this in  #366 with @vodovozovaliza and @wilkensJ. I want to make sure that they also agree.

2023-06-09 14:21 UTC, AleCandido approved these changes
There would still be bits to be cleaned up. But part of them are already addressed by #387.

I'm becoming mad with all the changes here and in the other PR. If it works, better to merge both, and at most keep optimizing in a further one (after merging both of them)

2023-06-09 14:24 UTC, andrea-pasquale commented on tests/test_niGSC_qq.py
> +    builder = ActionBuilder(str(path_to_runcard), test_folder, force=True, update=False)
Yes, exactly this will be dropped by #387.

2023-06-09 14:24 UTC, andrea-pasquale commented on src/qibocal/cli/utils.py
> +    if isinstance(card, str):
Also this should be fixed by #387.

2023-06-09 14:27 UTC, andrea-pasquale commented on src/qibocal/cli/builders.py
> +            shutil.copy(runcard, f"{self.folder}/runcard.yml")
Already addressed in #387. Let me merge it here.

2023-06-09 15:11 UTC, merged