[poc] Removing pint
qiboteam/qibocal pull request #372
Opened 2023-06-01 07:41 UTC by andrea-pasquale

A possible approach for removing pint using dataclasses, record arrays and custom dtypes.
For more info check #254.

Checklist:
- [ ] Reviewers confirm new code works as expected.
- [ ] Tests are passing.
- [ ] Coverage does not decrease.
- [ ] Documentation is updated.

2023-06-05 14:54 UTC, stavros11 reviewed
Thanks for this proposal, it looks good to me, certainly much better than the current solution. I would wait for one or two other people to confirm they like this before you propagate this to other routines, but from my side I agree, other than some small comments below.

A general suggestion since this is a [POC], maybe it will be easier for others to review if you only changed one file in this branch. If I understand correctly the only relevant file regarding the [POC] is the resonator_spectroscopy.py, the rest is just replacing `Union[str, int]` -> `QubitId`. Not very important if we know where to look, but in the future it may be better to seperate renames (which cause large file changes) from actual implementations which need to be reviewed in more detail.

2023-06-05 14:54 UTC, stavros11 commented on src/qibocal/protocols/characterization/resonator_spectroscopy.py
> +    def load_qubit(self, qubit, freq, msr, phase):
I think this function name is a bit misleading, it says `load` while it is actually saving (creating the data array that will be saved). Maybe something like `add_qubit_data`/`add_qubit_output` would be better?

Alternatively we could have a seperate function (say `create_output`) that constructs the array given `[freq, msr, phase]` and implement the `__setitem__` for `ResonatorSpectroscopyData`. In the end in the acquisition you would do
```py
for qubit in qubits:
        result = results[ro_pulses[qubit].serial]
        data[qubit] = create_output(
            msr=result.magnitude,
            phase=result.phase,
            freq=delta_frequency_range + ro_pulses[qubit].frequency,
        )
```

2023-06-05 14:54 UTC, stavros11 commented on src/qibocal/protocols/characterization/resonator_spectroscopy.py
> +    def to_csv(self, path):
Is this storing to csv? I think you are just storing to `npy` (binary format). 
I am not sure if there is a numpy method to dump the array with the custom dtype directly to csv (readable) or we need to do some kind of wrapping ourselves.

2023-06-05 15:16 UTC, AleCandido commented
Thanks @andrea-pasquale for the proposal, I'm going to take a look.

> A general suggestion since this is a [POC], maybe it will be easier for others to review if you only changed one file in this branch. If I understand correctly the only relevant file regarding the [POC] is the resonator_spectroscopy.py, the rest is just replacing `Union[str, int]` -> `QubitId`. Not very important if we know where to look, but in the future it may be better to seperate renames (which cause large file changes) from actual implementations which need to be reviewed in more detail.

And thanks @stavros11 for the comment.
In general, this kind of tiny tasks that are completely decoupled are a perfect fit for stand-alone PRs. You make them separate, it's simple, non-controversial, and thus easy to merge. And it's not going to hide the important changes in some other PRs :)

2023-06-05 15:39 UTC, andrea-pasquale commented
> A general suggestion since this is a [POC], maybe it will be easier for others to review if you only changed one file in this branch. If I understand correctly the only relevant file regarding the [POC] is the resonator_spectroscopy.py, the rest is just replacing `Union[str, int]` -> `QubitId`. Not very important if we know where to look, but in the future it may be better to seperate renames (which cause large file changes) from actual implementations which need to be reviewed in more detail.

You are totally @stavros11, sorry. I will be more careful :)





> Since it was a good idea, and it was already a separate commit, I made the PR myself :P

Thanks @AleCandido.
Now it is much better indeed.

2023-06-05 15:43 UTC, andrea-pasquale commented on src/qibocal/protocols/characterization/resonator_spectroscopy.py
> +    def to_csv(self, path):
This only a prototype. Here I had to put `to_csv` since in the executor currently I had hardcoded a `to_csv` function.
https://github.com/qiboteam/qibocal/blob/9f800393cfda17e8b79d0bd7c6c6e0c1da87f668/src/qibocal/auto/task.py#L104



> I think you are just storing to `npy` (binary format).

Indeed this is the case.

2023-06-05 18:44 UTC, andrea-pasquale commented on src/qibocal/protocols/characterization/resonator_spectroscopy.py
> +    def load_qubit(self, qubit, freq, msr, phase):
> I think this function name is a bit misleading, it says `load` while it is actually saving (creating the data array that will be saved). Maybe something like `add_qubit_data`/`add_qubit_output` would be better?

Yes, I also was not happy with `load_qubit`. It was just a placeholder for time being. `add_qubit_data` sounds good to me.



> Alternatively we could have a seperate function (say `create_output`) that constructs the array given `[freq, msr, phase]` and implement the `__setitem__` for `ResonatorSpectroscopyData`


I've also thought about this. It could an option. I don't have a strong preference between this and the option above.

2023-06-05 18:55 UTC, AleCandido commented on src/qibocal/protocols/characterization/resonator_spectroscopy.py
> +    def to_csv(self, path):
I would just drop the idea of supporting multiple formats, it is an over-head and not very useful. There are already other libraries that do this (and that you would use to implement the various formats), let's delegate this to the user.

I'd propose to go back to just `save()`.

2023-06-09 08:12 UTC, andrea-pasquale commented
> I would also keep a general data structure like `DataUnits`

`DataUnits` without pint is just a `pandas.DataFrame`. At this point I would suggest to inherit directly the `DataFrame` class.

2023-06-09 08:43 UTC, AleCandido commented
> At this point I would suggest to inherit directly the `DataFrame` class.

Or even just use `DataFrame` directly, without inheriting. But I would leave the pleasure to the user to transform a `np.ndarray` in a `pd.DataFrame` (that is a rather simple task, since it's just one call), and only keep arrays inside `qibocal`.

Once that data are saved in one format, and you can simply load them, converting it is definitely a simple task (since Numpy and Pandas are giving you the tools to do it anyhow).

I'm not against other data formats, but maintaining many options inside a single library/application is expensive. A package should focus on its core task, that can only be done by it. Then, it can always be composed with other ones to tackle specific use cases.

2023-06-13 10:50 UTC, andrea-pasquale commented
If there are no complains I would just change `load_qubit` to `add_qubit_data` and I will propagate those changes for all the routines.
I think that I would convert the global file into a json to be consistent with #395.

2023-06-13 11:40 UTC, AleCandido commented on src/qibocal/protocols/characterization/resonator_spectroscopy.py
> +    def load_qubit(self, qubit, freq, msr, phase):
I believe `_data` to be redundant, but unfortunately `add_` is a bit generic (that's why you need then `_data`).

`record_`/`register_`/`import_`/...?

2023-06-13 11:42 UTC, AleCandido commented on src/qibocal/protocols/characterization/resonator_spectroscopy.py
> +            yaml.dump(my_dict, outfile)
I know I said JSON, but it will be just the same, so I'll write for YAML because it's the current one, and the proposal will be slightly closer:
```suggestion
        (path / "conf.yml").write_text(yaml.dump(my_dict))
```
https://docs.python.org/3/library/pathlib.html#pathlib.Path.write_text

2023-06-13 11:42 UTC, andrea-pasquale commented on src/qibocal/protocols/characterization/resonator_spectroscopy.py
> +    def load_qubit(self, qubit, freq, msr, phase):
`register_qubit` sounds good to me.

2023-06-13 11:45 UTC, AleCandido commented on src/qibocal/protocols/characterization/resonator_spectroscopy.py
> +            np.save(path / f"data_q{q}.npy", self[q])
I would suggest writing all of them in a single file.

You could concatenate and make a single array, but it is slightly more annoying if you then are using them as separate arrays.
Otherwise, you just have to use a `.npz` file (despite the name, it is not compressed, it's just a single file containing multiple independent arrays).

https://numpy.org/doc/stable/reference/generated/numpy.savez.html#numpy.savez

2023-06-13 13:10 UTC, andrea-pasquale commented on src/qibocal/protocols/characterization/resonator_spectroscopy.py
> +            np.save(path / f"data_q{q}.npy", self[q])
Thanks @AleCandido. In https://github.com/qiboteam/qibocal/pull/372/commits/cd0e236a9df12dc7aa1ab3b3d2e1193112dcd62b I tried to implement the dumping to both json and npz. Let me know if see something wrong :)

2023-06-13 13:48 UTC, AleCandido commented on src/qibocal/auto/operation.py
> +    def to_json(path, data_dict: dict):
```suggestion
    def to_npz(path, data: dict):
        """Helper function to use np.savez while converting keys into strings."""
        np.savez(path / DATAFILE, **{str(i): data_dict[i] for i in data_dict})

    @staticmethod
    def to_json(path, data: dict):
```

`_dict` is redundant, it's already in the type.

Why do you want to have them as `staticmethod`? They could be just regular functions...

2023-06-13 13:53 UTC, andrea-pasquale commented on src/qibocal/auto/operation.py
> +    def to_json(path, data_dict: dict):
> `_dict` is redundant, it's already in the type.

Sure





> Why do you want to have them as `staticmethod`? They could be just regular functions...

I agree. I wanted to do it this way just to avoid to import for all the protocols these two functions.
I don't if I should call it laziness or just a strategy to avoid some imports.

2023-06-13 14:08 UTC, AleCandido commented on src/qibocal/protocols/characterization/resonator_spectroscopy.py
> +            np.save(path / f"data_q{q}.npy", self[q])
It seems great :)

Just test it ^^

2023-06-15 07:25 UTC, AleCandido commented on src/qibocal/protocols/characterization/allxy/allxy.py
> +        self.to_npz(path, self.data)
Maybe it's worth to make `.data` part of the interface, to avoid repeating these methods over and over for all the routines.

Is it possible?

2023-06-15 07:30 UTC, andrea-pasquale commented on src/qibocal/protocols/characterization/allxy/allxy.py
> +        self.to_npz(path, self.data)
I was thinking about it, also I don't like to repeat these methods every time.
The only problem in making them part of the interface is that we then force the user to use this interface (?)
In theory he can overwrite all the methods or simply not inherit from `Data`.
I was planning to clean up these methods.

2023-06-15 08:11 UTC, AleCandido commented on src/qibocal/protocols/characterization/allxy/allxy.py
> +        self.to_npz(path, self.data)
> The only problem in making them part of the interface is that we then force the user to use this interface (?)
> In theory he can overwrite all the methods or simply not inherit from `Data`.

Well, enforcing its usage is the whole point of an interface. If you can make it difference, it's not an interface any longer ^^
But the advantage is that, if you have a bunch of different objects with the same interface, you could standardize more operations on them, despite being different.

About inheriting or not, that's a separate discussion, since both nominal and structural subtyping are both possible.
However, if you do not inherit, you might have to repeat some code. But if it might be worth in certain cases (but at the moment we really rely on inheritance, even in type hints, using bounds, if we wanted to go structural, we should start defining protocols).

2023-06-15 08:14 UTC, AleCandido commented on src/qibocal/protocols/characterization/allxy/allxy.py
> +        self.to_npz(path, self.data)
> Btw, `qubits` and `__getitem__` are different for some routines. See for example

Well, this is not really different:
```py
    def __getitem__(self, qubit_state: tuple):
        qubit, state = qubit_state
        return self.data[qubit, state]
```
is equivalent to:
```py
    def __getitem__(self, qubit_state: tuple):
        return self.data[qubit_state]
```
Names do not matter, and if you do not specify the type (i.e. make the type a union) then the two things are still compatible.

2023-06-15 08:15 UTC, AleCandido commented on src/qibocal/protocols/characterization/allxy/allxy.py
> +        self.to_npz(path, self.data)
> Finally, also `save` is not completely standardized given that in some routines a json is not needed since all the data are just arrays.

Well, if not needed we can leave it empty :)

2023-06-15 08:35 UTC, AleCandido commented on tests/runcards/single_routines.yml
> +      relaxation_time:
Without a value is an empty string, not 0

2023-06-15 08:43 UTC, andrea-pasquale commented on src/qibocal/protocols/characterization/allxy/allxy.py
> +        self.to_npz(path, self.data)
> Well, if not needed, we can leave it empty :)

Another option would be to check if the dict that it going to be dumped to json is empty.

2023-06-15 08:47 UTC, andrea-pasquale commented on src/qibocal/protocols/characterization/allxy/allxy.py
> +        self.to_npz(path, self.data)
Also about the `save` method is using the `data` attribute which is defined in the child class (which will make pylint complain).
I could put in the `Data` class but then I will lose the specific type hint that I define in each child class...

2023-06-15 08:50 UTC, andrea-pasquale commented on src/qibocal/protocols/characterization/allxy/allxy.py
> +        self.to_npz(path, self.data)
Or I could just put something like `data: dict` and then it will be overwritten in the child class actually.

2023-06-15 09:07 UTC, andrea-pasquale commented on src/qibocal/auto/operation.py
> +        (path / JSONFILE).write_text(json.dumps(data_dict, indent=4))
If I understood correctly here, your suggestion is just to remove the indentation and if the user wants a readable format you suggest to use a json formatter.
At least for now this json are very short (just a few keys), I think that the indentation should not hurt as much for now.
If these files will increase we always turn off the indentation.

2023-06-15 09:15 UTC, andrea-pasquale commented
I've added a `deploy on hardware` label given that this PR has changed a lot of things in the protocols.
Apart from that it is ready to review, currently I'm testing everything with the dummy and tests seem to pass.

2023-06-15 10:28 UTC, AleCandido commented on src/qibocal/auto/operation.py
> +        (path / JSONFILE).write_text(json.dumps(data_dict, indent=4))
Not immediately, it was not even my proposal, just keep that in mind, since it could save a relevant bunch of bytes (every whitespace is one ASCII character, so 1 byte in UTF-8, and indentation uses a bunch of them).

2023-06-15 10:30 UTC, AleCandido commented on src/qibocal/protocols/characterization/allxy/allxy.py
> +        self.to_npz(path, self.data)
> The `save` method is using the `data` attribute which is defined in the child class (which will make pylint complain). I could put in the `Data` class but then I will lose the specific type hint that I define in each child class...

In case of doubt, make it `Any` (if you have too, otherwise leave it empty, that is the same), you could also overwrite in the child (for as long as it is compatible). I believe there might be a suitable (and not too complex) type hint that is more specific, but we can see later on.

2023-06-15 10:33 UTC, AleCandido commented on src/qibocal/protocols/characterization/allxy/allxy.py
> +        self.to_npz(path, self.data)
> Another option would be to check if the dict that it going to be dumped to json is empty.

This is possible, but it's a more special case wrt to the empty file. Every special case is more code to handle, every time you have to.
However, the two of them are simple enough, so they might be both good (in this case the trade-off is not so clear, even because it's not so crucial), you decide your favorite.

2023-06-15 11:04 UTC, andrea-pasquale commented on src/qibocal/protocols/characterization/allxy/allxy.py
> +        self.to_npz(path, self.data)
> Another option would be to check if the dict that it going to be dumped to json is empty.

Lets stick with this for time being.

2023-06-16 09:22 UTC, Edoardo-Pedicillo commented
Thank @andrea-pasquale, I have only one doubt concerning the dumping: with your implementation the global data are saved in separate files, since most of them are parameters that can be found in the runcards, there is a duplication of information in the report folder. From my point of view, the users should not move or touch directly the files in the report and when they want to load a `Data` class, Qibocal should be able to take what it needs from the runcards and the .npz. 

About the attribute `data`, I am not sure that we need a dictionary, it could be a suitable ndarray where the first axis runs on the qubits. If we want the qubit ID, we could evaluate it from the runcards.

2023-06-16 09:23 UTC, rodolfocarobene requested changes
Thanks for the nice PR @andrea-pasquale! 

I have added a couple of minor comments. In particular, I didn't write it every time, but:
* would be nice to have the conversion constants in a shared file
* would be nice to use the built-in types when possible

In any case, these are minor things, I'll try to run some routine to check everything works :-)

2023-06-16 09:23 UTC, rodolfocarobene commented on src/qibocal/protocols/characterization/allxy/drag_pulse_tuning.py
> +        voltages = qubit_data.msr * 1e6
I would define a constant instead of using `1e6`  so that is a bit clearer what you are doing (`UV_TO_V` or whatever)

2023-06-16 09:23 UTC, rodolfocarobene commented on src/qibocal/protocols/characterization/coherence/t1.py
> +            y=qubit_data.msr * 1e6,
Same constant than before... I don't know how many other times it appears, but maybe could be interesting to have it stored in a common place?

2023-06-16 09:23 UTC, rodolfocarobene commented on src/qibocal/protocols/characterization/dispersive_shift.py
> +        frequencies = q_data.freq / 1e9
better a constant

2023-06-16 09:23 UTC, rodolfocarobene commented on src/qibocal/protocols/characterization/dispersive_shift.py
> +        col=1,
I didn't try this routine, but this change seems a bit weird...
Was it wrong before?

2023-06-16 09:23 UTC, rodolfocarobene commented on src/qibocal/protocols/characterization/flux_depedence/utils.py
> +            z=qubit_data.msr * 1e4,
what unit of measure is this? Elsewhere we had 1e6

2023-06-16 09:23 UTC, rodolfocarobene commented on src/qibocal/protocols/characterization/ramsey.py
> +        shape = (1,) if np.isscalar(wait) else wait.shape
Not sure what's happening here, maybe a comment would be nice

2023-06-16 12:59 UTC, AleCandido commented on pyproject.toml
> -Pint-Pandas = "^0.3"
:tada:

2023-06-16 14:51 UTC, andrea-pasquale commented on src/qibocal/auto/task.py
>  TaskId = tuple[Id, int]
I think that it will be more clear once we have also a validation step. Basically the `int` should be the amount of time that you repeat a routine (if the fit `fails`).

2023-06-16 14:52 UTC, andrea-pasquale commented on src/qibocal/protocols/characterization/allxy/allxy.py
> +            z_proj = 2 * results[ro_pulses[qubit].serial].probability(0) - 1
In the literature for the allXY plot usually on the y axis it is shown the expectation value of Z.

2023-06-16 14:52 UTC, andrea-pasquale commented on src/qibocal/protocols/characterization/allxy/drag_pulse_tuning.py
Done, thanks.

2023-06-16 14:52 UTC, andrea-pasquale commented on src/qibocal/protocols/characterization/allxy/drag_pulse_tuning.py
> +        voltages = qubit_data.msr * 1e6
Done

2023-06-16 14:52 UTC, andrea-pasquale commented on src/qibocal/protocols/characterization/ramsey.py
> +        shape = (1,) if np.isscalar(wait) else wait.shape
Done

2023-06-16 14:55 UTC, AleCandido commented on src/qibocal/auto/task.py
>  TaskId = tuple[Id, int]
As @andrea-pasquale said, it is part of the *exceptional flow*, in which you may have loops (even when you do not fail, you might iterate to improve, or even go back to a previous step, if you remember Sergi's diagram).

2023-06-19 07:31 UTC, rodolfocarobene commented on src/qibocal/protocols/characterization/dispersive_shift.py
> +        col=1,
Indeed it was wrong before :-)

2023-06-19 07:32 UTC, rodolfocarobene approved these changes

2023-06-19 07:32 UTC, andrea-pasquale commented on src/qibocal/protocols/characterization/dispersive_shift.py
> +        col=1,
Yes, sorry I forgot to reply to this point. Indeed it was wrong before.

2023-06-19 11:03 UTC, stavros11 approved these changes
Thanks @andrea-pasquale, this is certainly an important simplifcation.

2023-06-19 11:03 UTC, stavros11 commented on src/qibocal/auto/operation.py
> +    def to_json(path, data_dict: dict):
I am also not sure why these need to be `@staticmethod`. Is there any routine where you use them with a `data_dict` that is not `self.data` and `self.global_params_dict`?

2023-06-19 13:37 UTC, andrea-pasquale commented
Thanks @stavros11.
You are right. Before, I had to do something like this because `global_params_dict` and `data` were defined only in the child classes. Now it doesn't make sense to have these methods as `staticmethods`.

2023-06-19 13:44 UTC, merged