Two qubits gates routines
qiboteam/qibocal pull request #381
Opened 2023-06-05 07:21 UTC by rodolfocarobene

Converting Maxime routines for two qubits gates (chevron and landscape/virtual z) to the new layout.

This is still a work in progress and I just started with the chevron, however I already have a question @andrea-pasquale, @Edoardo-Pedicillo: to the `_acquisition` function by default gets passed a `qubits` object and, for `_plot` I suppose that the function gets called separately for every qubit. 
This is a bit weird for two qubits routine since the important things are the pairs (parameter of the routine), not the single qubits. 
I don't know what to do, for example, in the plotting function where for every row I need to draw plots for two qubits.

Checklist:
- [ ] Reviewers confirm new code works as expected.
- [ ] Tests are passing.
- [ ] Coverage does not decrease.
- [ ] Documentation is updated.

2023-06-05 07:29 UTC, andrea-pasquale commented
> This is still a work in progress and I just started with the chevron, however I already have a question @andrea-pasquale, @Edoardo-Pedicillo: to the `_acquisition` function by default gets passed a `qubits` object and, for `_plot` I suppose that the function gets called separately for every qubit.

Thanks @rodolfocarobene.
Yes, this is something that we should need to address. Here the plotting function takes a pair of qubits, right?
Actually after we merge #351 the report will look at each element of the arguments qubits.
https://github.com/qiboteam/qibocal/blob/85e03d981368fcb5a3c20aec03354fe23abb4982/src/qibocal/web/templates/autocalibration.html#L155
If for the two qubit gates you specify that the qubits inputs is a list of pairs it could work I think...
Maybe we just need to rename qubit to something else.

2023-06-05 07:29 UTC, andrea-pasquale commented
You can give it a try by merging #351 which should be ready to merge here.

2023-06-05 07:32 UTC, andrea-pasquale commented on src/qibocal/protocols/characterization/two_qubit_interaction/chevron.py
> +    """Pair(s) of qubit to probe."""
Following my suggestion this should be:

```suggestion
    qubits: List[List[QubitId,QubitId]]
    """Pair(s) of qubit to probe."""
```
where you can import `QubitId` from qibolab.qubits

2023-06-05 07:32 UTC, rodolfocarobene commented
Thanks @andrea-pasquale, I'll proceed merging #351. 
The only problem is that I will not be able to test it with actual hardware, but ok

2023-06-05 07:33 UTC, andrea-pasquale commented
If it works with dummy you can try with that.

2023-06-07 05:34 UTC, rodolfocarobene commented
@andrea-pasquale, @Edoardo-Pedicillo What should I do to add tests for the routine? I saw that there are several "runcards" in the tests directory, but I am not sure which I should modify

2023-06-07 06:03 UTC, andrea-pasquale commented
A simple way to test this routine is to add it in [here](https://github.com/qiboteam/qibocal/blob/two-qubit-gates/tests/runcards/single_routines.yml) and [here](https://github.com/qiboteam/qibocal/blob/two-qubit-gates/tests/runcards/test_autocalibration.yml).

2023-06-07 10:29 UTC, maxhant requested changes
I personally don't like the functions but don't worry.  
I would also use the `iq_distance` like I've done in the SNZ PR to be able to discriminate the second state. 
Also, you can have a look at the fitting done by @aorgazf. I tried to find it in the branches that I know but couldn't find it...
It is pretty simple. Take the FFT for every amplitude, get the main frequency of oscillation, from all the smallest one (center chevron) is the one you want, fit it with a sin/cos and the period is your duration. 
Anyway, it is not strickly necessary for now. Just the few comments, and it's good to me

2023-06-07 10:29 UTC, maxhant commented on src/qibocal/protocols/characterization/two_qubit_interaction/chevron.py
> +        + 8,
The +8 here was to avoid any timing problems when using the bias tee. I have kept it because it does not hurt. However, as it is a bit arbitrary, I would remove it, or create a parameter 
Now that we are not using bias-tee pulses should arrive at the scheduled time exactly.

2023-06-07 10:29 UTC, maxhant commented on src/qibocal/protocols/characterization/two_qubit_interaction/chevron.py
> +    )
same comment for 8 here

2023-06-07 10:29 UTC, maxhant commented on src/qibocal/protocols/characterization/two_qubit_interaction/chevron.py
> +        params.qubits = platform.settings["topology"]
Why that line?

2023-06-07 10:53 UTC, rodolfocarobene commented on src/qibocal/protocols/characterization/two_qubit_interaction/chevron.py
> +        params.qubits = platform.settings["topology"]
I would like that, if I don't define the qubit parameter, the topology is used... But in any case I have to wait for the local qubit to fully work

2023-06-12 13:58 UTC, Jacfomg commented on src/qibocal/protocols/characterization/two_qubit_interaction/chevron.py
> +        prob = result.statistical_frequency
```suggestion
        result = results[measure_target.serial].serialize
        prob = result["0"]
```
Same here I might take a look into the results.py as well

2023-06-12 13:58 UTC, Jacfomg commented on src/qibocal/protocols/characterization/two_qubit_interaction/cz_virtualz.py
> +                prob = result.statistical_frequency
```suggestion
                result = results[measure_target.serial].serialize
                prob = result["0"]
```
This should save probabiliies not as complex numbers

2023-06-12 14:15 UTC, Jacfomg commented
They run properly on the devices

2023-07-14 07:59 UTC, Jacfomg reviewed
Small changes to make them run on the devices.

2023-07-14 07:59 UTC, Jacfomg commented on src/qibocal/protocols/characterization/two_qubit_interaction/chevron.py
> +        fit_report += f"Period of oscillation: {fit.period[str(ordered_index)]} ns<br>"
```suggestion
       #  fit_report += f"Period of oscillation: {fit.period[str(ordered_index)]} ns<br>"
```
Comment it for now until we get the fitting

2023-07-14 07:59 UTC, Jacfomg commented on src/qibocal/protocols/characterization/two_qubit_interaction/cz_virtualz.py
> +                pulse.duration = flux_sequence[setup].duration
```suggestion
                pulse.start = flux_sequence.start
                pulse.duration = flux_sequence.duration
```

2023-07-25 11:06 UTC, andrea-pasquale commented
This is ready to review and it has been tested on hardware.
A few things to be changed:
- fititng on chevron
- change from MSR to probabilities

2023-07-25 11:34 UTC, rodolfocarobene commented on src/qibocal/auto/operation.py
> +        return list({tuple(sorted(q[:2])) for q in self.data})
In which way are the qubit sorted? I would write it in the docstring for clarity

2023-07-25 11:34 UTC, rodolfocarobene commented on src/qibocal/protocols/characterization/two_qubit_interaction/chevron.py
> +    return pair
I know that is basically my code so my bad, but maybe here it would be better to use a named tuple so that it's clear (here and elsewhere) which is the high frequency qubit and which the low. Something like:
```python
from collections import namedtuple

Pair = namedtuple('Pair', 'high_freq low_freq')
mypair = Pair(qubit0, qubit1)

mypair.low_freq
> qubit0
```

2023-07-25 11:34 UTC, rodolfocarobene commented on src/qibocal/protocols/characterization/two_qubit_interaction/chevron.py
> +
I see that you removed the parking parameter, may I ask you how you manage it?

2023-07-25 11:34 UTC, rodolfocarobene commented on src/qibocal/protocols/characterization/two_qubit_interaction/chevron.py
> +            ordered_pair[0], start=initialize_lowfreq.finish + params.duration_max + 20
These 20s could be a routine parameter, something like dt set to 20 by default

2023-07-25 11:34 UTC, rodolfocarobene commented on src/qibocal/protocols/characterization/two_qubit_interaction/cz_virtualz.py
> +    cz_phase: dict[tuple[QubitId, QubitId], float]
Are these different?

2023-07-25 11:34 UTC, rodolfocarobene commented on src/qibocal/protocols/characterization/two_qubit_interaction/cz_virtualz.py
> +        start=flux_sequence.finish + 20,
I think that here the dt could be used (and it's already a parameter)

2023-07-26 06:56 UTC, andrea-pasquale commented on src/qibocal/auto/operation.py
> +        return list({tuple(sorted(q[:2])) for q in self.data})
Good point, here they are just sorted alphanumerically.

2023-07-26 07:01 UTC, andrea-pasquale commented on src/qibocal/protocols/characterization/two_qubit_interaction/chevron.py
> +            ordered_pair[0], start=initialize_lowfreq.finish + params.duration_max + 20
You are right, at this point we could add also here a `dt` parameter or maybe something more meaningful than `dt`.

2023-07-26 07:28 UTC, andrea-pasquale commented on src/qibocal/protocols/characterization/two_qubit_interaction/cz_virtualz.py
> +    cz_phase: dict[tuple[QubitId, QubitId], float]
Yes, CZ phase should be pi, while virtual_phase is the virtual_phase computed to correct the additional phase acquired during the 02 - 11 interaction. Now that you make think about it perhaps here the calculation of the virtual phase is wrong... I will double check :)

2023-07-26 08:48 UTC, andrea-pasquale commented on src/qibocal/protocols/characterization/two_qubit_interaction/chevron.py
> +    return pair
At this point I was thinking that we could move this to qibolab...
Or to already order the qubit pair in qibolab according to the drive frequency.
What do you think @rodolfocarobene @Jacfomg @stavros11 ?

2023-07-26 09:01 UTC, andrea-pasquale commented on src/qibocal/protocols/characterization/two_qubit_interaction/cz_virtualz.py
> +    cz_phase: dict[tuple[QubitId, QubitId], float]
After discussing with @igres26, I modified the result object.
Currently there is also one parameter which is the CZ angle. There is no way to detect the virtual phase through fitting.

2023-07-26 10:13 UTC, rodolfocarobene commented on src/qibocal/protocols/characterization/two_qubit_interaction/chevron.py
> +    return pair
Imho it makes sense to have them here, in qibolab they could be ordered in respect to the topology (like, for a linear chip it could become confusing)

2023-07-27 08:55 UTC, Jacfomg reviewed
Apart from the parking seems good to me. I think we should wait until they get tested on hardware, I am not aware of the situation right now.

2023-07-28 08:09 UTC, andrea-pasquale commented on src/qibocal/protocols/characterization/two_qubit_interaction/chevron.py
> +    return pair
I implemented the `namedtuple` in https://github.com/qiboteam/qibocal/pull/381/commits/35fb20383a7b4f3548420c373879a86f42f52a75, it looks much more readable now. Thanks!

2023-07-28 08:41 UTC, andrea-pasquale commented
I should have implemented all the comments. Let me know if there is something else to do, otherwise I think that we can merge @rodolfocarobene @Jacfomg

2023-07-28 08:42 UTC, andrea-pasquale commented
> Apart from the parking seems good to me. I think we should wait until they get tested on hardware, I am not aware of the situation right now.

I'm testing on hardware with qblox, the protocols seem to be working. I need to test only the parking.

2023-07-28 10:21 UTC, rodolfocarobene commented
> I'm testing on hardware with qblox, the protocols seem to be working. I need to test only the parking.

It looks good to me! (approved)

2023-07-28 10:22 UTC, andrea-pasquale approved these changes

2023-07-28 10:22 UTC, andrea-pasquale commented
> > I'm testing on hardware with qblox, the protocols seem to be working. I need to test only the parking.
> 
> It looks good to me! (approved)

I approved on your behalf ahahah

2023-07-28 10:36 UTC, Jacfomg approved these changes

2023-07-28 17:38 UTC, merged