Stream line standard rb
qiboteam/qibocal pull request #391
Opened 2023-06-07 19:00 UTC by wilkensJ

Checklist:
- [x] Reviewers confirm new code works as expected.
- [x] Tests are passing.
- [x] Coverage does not decrease.
- [x] Documentation is updated.

2023-06-08 07:52 UTC, Jacfomg requested changes
Also, can we add something saying that the `layer_gen()` allows the generation of proper random circuits to avoid confusion for the next people that will read the routines ? Just because my first thought was why were you not passing `random_clifford()` directly.

2023-06-08 07:52 UTC, Jacfomg commented on src/qibocal/protocols/characterization/randomized_benchmarking/standard_rb.py
> +    step: int
Is it there any case where you would prefer to write the list instead of the start,stop,step ?

2023-06-08 07:52 UTC, Jacfomg commented on src/qibocal/protocols/characterization/randomized_benchmarking/standard_rb.py
> +        super().to_csv(f"{path}/{self.__class__.__name__}.csv")
For now until the #372 is merged we will not get rid of the .csv and I would prefer to avoid .csv as you will not save the samples properly. As a temporal solution could you save it as .json using that function ?

2023-06-08 07:52 UTC, Jacfomg commented on src/qibocal/protocols/characterization/randomized_benchmarking/standard_rb.py
>      data = execute(scan, params.nshots, noise_model)
Maybe it's just me but I would prefer to not use the `execute()` and have it on the `_acquisition()`. It looks more like the other routines that way. @andrea-pasquale @wilkensJ what's your opinion on this ?

```suggestion
    # 2. Execute the scan.
    data_list = []
    # Iterate through the scan and execute each circuit.
    for circuit in scan:
        # The inverse and measurement gate don't count for the depth.
        depth = (circuit.depth - 2) if circuit.depth > 1 else 0
        if noise_model is not None:
            circuit = noise_model.apply(circuit)
        samples = circuit.execute(nshots=params.nshots).samples()
        # Every executed circuit gets a row where the data is stored.
        data_list.append({"depth": depth, "samples": samples})
```

2023-06-08 08:03 UTC, vodovozovaliza commented
Would it be okay to add a runcard `test_autocalibration_sim.yml` with a `numpy` backend to test RB routines with noise models? Noise models simulation will not work with `qibolab` backend.

2023-06-08 08:31 UTC, wilkensJ commented on src/qibocal/protocols/characterization/randomized_benchmarking/standard_rb.py
> +    step: int
Yes, something which gets a good approximation of the drop but then also 'checks' a point a bit more fare away. Something like [1,3,5,7,9,11,15,20,30] When the noise is bad (meaning the drop happens in the very beginning).
Or just to give an estimate if the fidelity changed a lot, making the spacing bigger the more the depth saves resources.

2023-06-08 08:33 UTC, wilkensJ commented on src/qibocal/protocols/characterization/randomized_benchmarking/standard_rb.py
> +        super().to_csv(f"{path}/{self.__class__.__name__}.csv")
You mean overwrite the .to_csv of the pandas data frame object that is actually calles .to_json? I like the idea, because in csv the samples are stores as a string and it is hard to recover the data then. But with json that would not be the case. I like the idea, thank you @Jacfomg.
What do you think @andrea-pasquale?

2023-06-08 09:12 UTC, Jacfomg requested changes
I think that for the time being if you try to specify noise_models but you have specified a platform not to have it change to a simulation backend on itself for now but check the platform and raise an error. I will look into that.

2023-06-08 09:16 UTC, Jacfomg commented
> Would it be okay to add a runcard `test_autocalibration_sim.yml` with a `numpy` backend to test RB routines with noise models? Noise models simulation will not work with `qibolab` backend.

I would say yes for now, ideally we will want to have them both on the same runcard. I am not sure if how. Maybe runcards with both a global platform and backend and the routine chooses ?

2023-06-08 09:26 UTC, wilkensJ commented on src/qibocal/protocols/characterization/randomized_benchmarking/standard_rb.py
> +    label = "Fit: y=Ap^x+B<br>A: {:.3f}\u00B1{:.3f}<br>p: {:.3f}\u00B1{:.3f}<br>B: {:.3f}\u00B1{:.3f}".format(
Why would that be useful? I think displaying too many digits give the false impression that what is measured here is very accurate. Because the longer the more arbitrary and un meaningful the last digits are.
Or are you opting in the other direction? displaying less digits, if possible?

2023-06-08 09:32 UTC, wilkensJ commented on src/qibocal/protocols/characterization/randomized_benchmarking/standard_rb.py
For what does [Sim] stand for?:)

2023-06-08 10:43 UTC, Jacfomg commented on src/qibocal/protocols/characterization/randomized_benchmarking/standard_rb.py
Simulation. Just thought of something to tell people which parameters they need for hardware and simulation, feel free to change it

2023-06-08 10:45 UTC, Jacfomg commented on src/qibocal/protocols/characterization/randomized_benchmarking/standard_rb.py
>          else None
All the routines have this for nshots and relaxation_time because they are optional parameters and have a default value. If noise_params is also optional I would like that it behaves in the same way.

2023-06-08 10:54 UTC, Jacfomg commented on src/qibocal/protocols/characterization/randomized_benchmarking/standard_rb.py
> +    label = "Fit: y=Ap^x+B<br>A: {:.3f}\u00B1{:.3f}<br>p: {:.3f}\u00B1{:.3f}<br>B: {:.3f}\u00B1{:.3f}".format(
Lets say, check how many 9s the fidelity has and display less or more digits accordingly. Ideally I would display two significant figures on the uncertainty and adjust in the value. Something like 0.992 \pm 0.023 or 0.99 \pm 0.17. What do you think of this ?

2023-06-08 11:41 UTC, wilkensJ commented on src/qibocal/protocols/characterization/randomized_benchmarking/standard_rb.py
>          else None
Alright, I did not know that! Then I agree. Thank you,

2023-06-08 11:44 UTC, wilkensJ commented on src/qibocal/protocols/characterization/randomized_benchmarking/standard_rb.py
> +    label = "Fit: y=Ap^x+B<br>A: {:.3f}\u00B1{:.3f}<br>p: {:.3f}\u00B1{:.3f}<br>B: {:.3f}\u00B1{:.3f}".format(
But I thought the choice of significant digits is a choice how meaningful and trustworthy a value is? So even when the fidelity is 0.990, the zero has a meaning.  Then I would add that in @vodovozovaliza PR (what it already is, I guess?)?

2023-06-08 11:49 UTC, Jacfomg commented on src/qibocal/protocols/characterization/randomized_benchmarking/standard_rb.py
> +    label = "Fit: y=Ap^x+B<br>A: {:.3f}\u00B1{:.3f}<br>p: {:.3f}\u00B1{:.3f}<br>B: {:.3f}\u00B1{:.3f}".format(
They taught to choose the significant digits based on the uncertanties so that they have meaning, but yeah I am sure they are man ways to take this into account so we just need to select one

2023-06-08 11:50 UTC, wilkensJ commented on src/qibocal/protocols/characterization/randomized_benchmarking/standard_rb.py
> +    label = "Fit: y=Ap^x+B<br>A: {:.3f}\u00B1{:.3f}<br>p: {:.3f}\u00B1{:.3f}<br>B: {:.3f}\u00B1{:.3f}".format(
Yes, totally. So I would say that we do that in @vodovozovaliza PR :)

2023-06-08 11:51 UTC, wilkensJ commented on src/qibocal/protocols/characterization/randomized_benchmarking/standard_rb.py
You mean for the documentation? Yes totally! I mean the actions_qq_auto has the part already, but I totally agree, we have to add a documentation.

2023-06-08 12:07 UTC, Jacfomg commented on src/qibocal/protocols/characterization/randomized_benchmarking/standard_rb.py
I know, I am also trying to think if we have new people joining, but maybe it's redundant.

2023-06-09 06:51 UTC, andrea-pasquale reviewed
Thanks @wilkensJ @vodovozovaliza @Jacfomg for all the updates.
Generally the code looks good to me. You can find a few suggestions below.

2023-06-09 06:51 UTC, andrea-pasquale commented on src/qibocal/auto/operation.py
> +def _dummy_acquisition(pars: DummyPars, platform) -> DummyData:
```suggestion
from qibolab.platform import Platform
def _dummy_acquisition(pars: DummyPars, platform : Platform) -> DummyData:
```

2023-06-09 06:51 UTC, andrea-pasquale commented on src/qibocal/protocols/characterization/randomized_benchmarking/standard_rb.py
Uhm, I would say that the best approach here would be to define a `backend` argument and to throw an error if the noise model is used with the qibolab backend. I still don't know if this is the best approach.

In #351 I decided to used the following approach to fix tests:
https://github.com/qiboteam/qibocal/blob/8e404f83e959548bfbf6d3800f247d8d971ecd8e/tests/test_protocols.py#L21-L28

Another idea could be to define a new type for those routine that are executable also in simulation.
I would say that this is out of the scope of this PR.

2023-06-09 06:51 UTC, andrea-pasquale commented on src/qibocal/protocols/characterization/randomized_benchmarking/standard_rb.py
> +class DepthsDict(TypedDict):
I would add a docstring here

2023-06-09 06:51 UTC, andrea-pasquale commented on src/qibocal/protocols/characterization/randomized_benchmarking/standard_rb.py
> +    noise_params: Optional[list] = None
```suggestion
    noise_params: Optional[list] = field(default_factory=list)
```
In this way you can drop the lines to initialize `noise_params` in the `__post_init__`.
See comment below.

2023-06-09 06:51 UTC, andrea-pasquale commented on src/qibocal/protocols/characterization/randomized_benchmarking/standard_rb.py
> +            self.noise_params = []
Those lines can be dropped if you implement the suggestion above.

2023-06-09 06:51 UTC, andrea-pasquale commented on src/qibocal/protocols/characterization/randomized_benchmarking/standard_rb.py
> +        RBData: The depths, samples and ground state probability of each exeriment in the scan.
```suggestion
        RBData: The depths, samples and ground state probability of each experiment in the scan.
```

2023-06-09 06:51 UTC, andrea-pasquale commented on src/qibocal/protocols/characterization/randomized_benchmarking/standard_rb.py
> +        qibo.set_backend("numpy")
For now this should be fine. I would suggest to add a `TODO` or a `FIXME` to implement this check properly ( and possibly outside the acquisition)

2023-06-09 07:17 UTC, vodovozovaliza commented on src/qibocal/protocols/characterization/randomized_benchmarking/standard_rb.py
> +            self.noise_params = []
@andrea-pasquale it these lines are removed, specifying `noise_params` in the runcard as @Jacfomg proposed will not be possible:
```python
noise_model: PauliErrorOnAll
noise_params:
```
If you think it is not necessary, we can revert this change, as the implementation by @wilkensJ before was exactly what you are suggesting.

2023-06-09 13:56 UTC, ingoroth commented on src/qibocal/protocols/characterization/randomized_benchmarking/standard_rb.py
In principle, the noise model can also be applied through qibolab and is not at all restricted to simulation, or?  Technically, it is just a transpiler that is run before passing the circuit to the platform.  It is just that the current noise models will often result in circuits (with channels) that qibolab does not know how to compile, e.g. because probabilistic compilation is not implemented. A noise model with only coherent error for example, would already work.  The reason we have the noise model parameters in the run card is because it actually also makes sense to allow for 'synthetic' noise when running things on the device.  Thus, I think it might actually not be qibocal's job to catch the exception but qibolab's (in the sense it is already doing).

2023-06-09 14:20 UTC, andrea-pasquale commented on src/qibocal/protocols/characterization/randomized_benchmarking/standard_rb.py
Thanks for the explanation @ingoroth.
I also agree that this should be addressed in qibolab (and perhaps even in qibo).
Until we solve the issue at least for qibocal we need to always use simulation to run a noise model.
We can merge this PR without this feature for the time being.

2023-06-09 14:27 UTC, Jacfomg commented
Found an issue when ussing dummy that the probabilities get divided based on how many qubits you put on the parameters for the RB. Dummy seemed working properly, we may want to check what's happening next week with that.

2023-06-12 06:52 UTC, wilkensJ commented on src/qibocal/protocols/characterization/randomized_benchmarking/standard_rb.py
@andrea-pasquale can you show me what should be changed now for this PR? I am a bit lost in what should stay/be changed, sorry of the confusion.

2023-06-12 08:43 UTC, Jacfomg approved these changes

2023-06-12 08:59 UTC, Jacfomg commented
Also, now that we have the platform on the routine we can remove the nqubits as a parameter as @andrea-pasquale suggested

2023-06-12 11:37 UTC, andrea-pasquale commented on src/qibocal/protocols/characterization/randomized_benchmarking/standard_rb.py
Regarding this point you can open an issue if you want.
All the rest looks good to me.

2023-06-12 11:41 UTC, andrea-pasquale commented on src/qibocal/auto/runcard.py
>          return construct_backend(self.backend, self.platform)
@stavros11 this is a temporary solution.
I don't know if there is a better way to do it. Currently it was not working since for the RB when executing circuits we don't pass the backend and by doing `circuit()` we will fall back to the default backend.
Currently I feel like this approach is a bit redundant. Do you have any suggestions?

2023-06-13 08:47 UTC, andrea-pasquale approved these changes
Thanks @vodovozovaliza @wilkensJ @Jacfomg.
Feel free to merge this PR.

2023-06-13 09:15 UTC, merged