ro_optimization in autocalibration
qiboteam/qibocal pull request #392
Opened 2023-06-08 15:15 UTC by Edoardo-Pedicillo

Checklist:
- [ ] Reviewers confirm new code works as expected.
- [ ] Tests are passing.
- [ ] Coverage does not decrease.
- [ ] Documentation is updated.

2023-07-05 13:26 UTC, Jacfomg commented
Can we try to have this working, or if you have to work on something else can I take it ?

2023-07-06 09:05 UTC, andrea-pasquale commented
We might need this also to fix #337 given that when optimizing the freq we can clearly see in which direction the clouds are rotating.

2023-07-09 07:29 UTC, Edoardo-Pedicillo commented
Sorry for the number of commits, but I had some troubles with the stash.
Now the PR is ready, I tested it on hardware only with one qubit, when I tried with multiple ones I lost the connection with the instruments and I am not able to reconnect to iqm5q for the time being. These days I have to attend a school, @andrea-pasquale @Jacfomg could you please test the routine with multiple qubit?

2023-07-09 13:42 UTC, Jacfomg commented
> Sorry for the number of commits, but I had some troubles with the stash. Now the PR is ready, I tested it on hardware only with one qubit, when I tried with multiple ones I lost the connection with the instruments and I am not able to reconnect to iqm5q for the time being. These days I have to attend a school, @andrea-pasquale @Jacfomg could you please test the routine with multiple qubit?

The iqm5q LO seems dead or off for some reason, I will check when I get on the lab. For the code we could skip saving msr and phase as we are not using them right ?

2023-07-09 13:53 UTC, Jacfomg requested changes

2023-07-09 13:53 UTC, Jacfomg commented on src/qibocal/protocols/characterization/__init__.py
> +from .readout_optimization.ro_frequency import ro_frequency
Can we name it resonator_frequency and leave ro_frequency for the qubit ?

2023-07-09 13:53 UTC, Jacfomg commented on src/qibocal/protocols/characterization/readout_optimization/ro_frequency.py
> +        ("phase", np.float64),
```suggestion
```

2023-07-09 13:53 UTC, Jacfomg commented on src/qibocal/protocols/characterization/readout_optimization/ro_frequency.py
> +        ar["q"] = q
```suggestion
```

2023-07-09 13:53 UTC, Jacfomg commented on src/qibocal/protocols/characterization/readout_optimization/ro_frequency.py
> +                phase=result.phase,
```suggestion
```

2023-07-09 13:53 UTC, Jacfomg commented on src/qibocal/protocols/characterization/readout_optimization/ro_frequency.py
> +def _acquisition(
I think we try something like I did for the fast_reset or integration_weights acquisition to avoid repeating code for each state ?
```py

data = RoFrequencyData(platform.resonator_type)
sweeper = Sweeper(
    Parameter.frequency,
    delta_frequency_range,
    pulses=[ro_pulses[qubit] for qubit in qubits],
    type=SweeperType.OFFSET,
)

for state in [0, 1]:
  if state == 1:
      RX_pulses = {}
  ro_pulses = {}
  sequence = PulseSequence()
  for qubit in qubits:
      if state == 1:
          RX_pulses[qubit] = platform.create_RX_pulse(qubit, start=0)
          ro_pulses[qubit] = platform.create_qubit_readout_pulse(
              qubit, start=RX_pulses[qubit].finish
          )
          sequence.add(RX_pulses[qubit])
      else:
          ro_pulses[qubit] = platform.create_qubit_readout_pulse(qubit, start=0)
          sequence.add(ro_pulses[qubit])
      sequence.add(ro_pulses[qubit])
  # execute pulse sequence

  results = platform.sweep(
          sequence,
          ExecutionParameters(
              nshots=params.nshots,
              relaxation_time=params.relaxation_time,
              acquisition_type=AcquisitionType.INTEGRATION,
          ),
          sweeper,
      )


    # retrieve and store the results for every qubit
    for qubit in qubits:
          result = results[ro_pulses[qubit].serial]
          # store the results
          data.register_qubit(
              qubit=qubit,
              state=state,
              freq=ro_pulses[qubit].frequency + delta_frequency_range,
              i=result.voltage_i,
              q=result.voltage_q,
          )
```

2023-07-09 13:53 UTC, Jacfomg commented on src/qibocal/protocols/characterization/readout_optimization/ro_frequency.py
> +        xaxis_title="RO Frequencies (GHz)",
Same for the name
```suggestion
        xaxis_title="Resonator Frequencies (GHz)",
```

2023-07-09 13:53 UTC, Jacfomg commented on src/qibocal/protocols/characterization/readout_optimization/ro_frequency.py
> +        f"{qubit} | Best RO Frequency (GHz) : {fit.best_freq[qubit]*HZ_TO_GHZ:,.4f} Hz.<br>"
```suggestion
        f"{qubit} | Best Resonator Frequency (GHz) : {fit.best_freq[qubit]*HZ_TO_GHZ:,.4f} Hz.<br>"
```

2023-07-10 06:27 UTC, andrea-pasquale reviewed
Thanks @Edoardo-Pedicillo.
I still need to test the routine on hardware, generally looks good to me.
Please find below some suggestions.

2023-07-10 06:27 UTC, andrea-pasquale commented on src/qibocal/protocols/characterization/utils.py
> +    input_data = np.sort(input_data)
Technically these are already sorted, so probably we can drop this line.

2023-07-10 06:27 UTC, andrea-pasquale commented on src/qibocal/protocols/characterization/readout_optimization/ro_frequency.py
> +class RoFrequencyData(Data):
I would rename `RoF` in `ResonatorFrequency` in all classes.

2023-07-10 06:27 UTC, andrea-pasquale commented on src/qibocal/protocols/characterization/readout_optimization/ro_frequency.py
> +        ar["q"] = q
+1

2023-07-10 06:27 UTC, andrea-pasquale commented on src/qibocal/protocols/characterization/readout_optimization/ro_frequency.py
> +        ("phase", np.float64),
+1

2023-07-10 06:27 UTC, andrea-pasquale commented on src/qibocal/protocols/characterization/readout_optimization/ro_frequency.py
> +                phase=result.phase,
+1

2023-07-10 06:49 UTC, Jacfomg commented
> Sorry for the number of commits, but I had some troubles with the stash. Now the PR is ready, I tested it on hardware only with one qubit, when I tried with multiple ones I lost the connection with the instruments and I am not able to reconnect to iqm5q for the time being. These days I have to attend a school, @andrea-pasquale @Jacfomg could you please test the routine with multiple qubit?

I was testing it and the cumulative takes the times we measured. Now all the time the routine takes is on the execution. As there usually short time-scale noise going on that can be seen on weird blobs that decrease fidelity I suppose we should set a high default value for nshots if we want to avoid to do software averages. Also, checking if just using a high number of shots would help could be measured running a calibrate qubit states with many points using now the new cumulative function.

2023-07-10 17:07 UTC, Edoardo-Pedicillo commented
> I suppose we should set a high default value for nshots if we want to avoid to do software averages.

Yes indeed, I have not implemented the software average for this reason. Maybe I can add this as a suggestion somewhere.

2023-07-10 17:49 UTC, Edoardo-Pedicillo commented on src/qibocal/protocols/characterization/utils.py
> +    input_data = np.sort(input_data)
I prefer deleting the sorting in the _fit method.

2023-07-10 19:48 UTC, Edoardo-Pedicillo commented on src/qibocal/protocols/characterization/readout_optimization/ro_frequency.py
> +        ar["q"] = q
If I delete `i` and `q`, How can I classify the points?

2023-07-10 20:05 UTC, Edoardo-Pedicillo commented on src/qibocal/protocols/characterization/readout_optimization/ro_frequency.py
> +def _acquisition(
Although your code is good, I fail to see the benefit of a for loop. Since the acquisition function is small and we have only two cases, readability and maintenance are not an issue here. Additionally, your example contains a for loop with two if statements, which in my opinion makes it harder to read and I don't see any benefits in the performances.

2023-07-11 05:52 UTC, Jacfomg approved these changes

2023-07-11 07:19 UTC, andrea-pasquale reviewed
Thanks @Edoardo-Pedicillo.
I tested it on hardware and it seems to work as expected.
Just a few minor comments than we can merge.
Could you also have a look at the coverage?

2023-07-11 08:33 UTC, Jacfomg commented on src/qibocal/protocols/characterization/readout_optimization/ro_frequency.py
> +        ar["q"] = q
Yeah my bad, it was only for magnitude and phase

2023-07-11 08:34 UTC, Jacfomg commented on src/qibocal/protocols/characterization/readout_optimization/resonator_frequency.py
> +    """ "Optimization RO frequency outputs."""
```suggestion
    """Optimization Resonator frequency outputs."""
```

2023-07-17 13:49 UTC, Edoardo-Pedicillo commented on src/qibocal/protocols/characterization/readout_optimization/resonator_frequency.py
> +            fidelities.append((errors_state1 + errors_state0) / nshots / 2)
> This is the same operation that we are doing for the single shot classification, right?

Yes 

> We should be able to recycle that function in one way or another.

If not strictly necessary now, I prefer to do it in the (near) future PR to port the classification models. 

> Did you speed up also the fitting in the single shot classification? 

Yes, only the cumulative part.

2023-07-20 07:08 UTC, andrea-pasquale approved these changes
Thanks @Edoardo-Pedicillo, looks good to me.

2023-07-20 07:09 UTC, merged