Fast reset testing routine
qiboteam/qibocal pull request #399
Opened 2023-06-13 13:54 UTC by Jacfomg

For now this can be used as a sanity check when playing with the fast reset capability of some devices. I'm still not sure what's the best thing for plotting or if it's needed for a good benchmark to measure both states.

Checklist:
- [ ] Reviewers confirm new code works as expected.
- [ ] Tests are passing.
- [ ] Coverage does not decrease.
- [ ] Documentation is updated.

2023-06-27 08:05 UTC, Jacfomg commented
I have a problem, I wanted to get plotty to display a heatmap with text on it to plot a matrix with the state counts, but for some reason I can't make it work. Have you ever plotted something similar ?

2023-06-27 08:19 UTC, Jacfomg commented on src/qibocal/protocols/characterization/fast_reset/fast_reset.py
> +        ar = np.empty(shape, dtype=FastResetType)
Fix the shape

2023-06-27 08:50 UTC, andrea-pasquale commented
> I have a problem, I wanted to get plotty to display a heatmap with text on it to plot a matrix with the state counts, but for some reason I can't make it work. Have you ever plotted something similar ?

Perhaps @Edoardo-Pedicillo did something similar with single shot classification, I'm not so sure.

2023-06-27 09:03 UTC, andrea-pasquale reviewed
Thanks @Jacfomg.
You can find below some suggestions.

2023-06-27 09:03 UTC, andrea-pasquale commented on src/qibocal/protocols/characterization/fast_reset/fast_reset.py
> +    data: dict[QubitId, npt.NDArray[FastResetType]] = field(default_factory=dict)
If I understood correctly each array is identified by 3 keys (qubit,state,fast_reset), right?
Potentially we could store each array by selecting these 3 keys:
```suggestion
    data: dict[tuple[QubitId,int,int], npt.NDArray[FastResetType]] = field(default_factory=dict)
```
This should also fix the issue related to the shape I think.
Moreover, you don't need to store multiple times the state and the fast_reset.

I did something similar for single_shot_classification (only using state):

https://github.com/qiboteam/qibocal/blob/8d2b63099486faab8355cc4fa92b59abc7213ab6/src/qibocal/protocols/characterization/classification.py#L35

2023-06-27 09:03 UTC, andrea-pasquale commented on src/qibocal/protocols/characterization/fast_reset/fast_reset.py
> +    results = platform.execute_pulse_sequence(
Maybe the acquisition can be simplified by doing some sort of for loop by changing state, sequence and fast_reset.

2023-06-27 09:03 UTC, andrea-pasquale commented on src/qibocal/protocols/characterization/fast_reset/fast_reset.py
> +    """Plotting function for FastReset."""
Also this function could be simplified I think. Lets try to fix first the issue related to the plotting.

2023-06-27 09:13 UTC, Jacfomg commented on src/qibocal/protocols/characterization/fast_reset/utils.py
What is this ?

2023-06-27 09:14 UTC, Jacfomg commented on src/qibocal/protocols/characterization/fast_reset/fast_reset.py
> +    data: dict[QubitId, npt.NDArray[FastResetType]] = field(default_factory=dict)
Yeah, that would be perfect I will change it the same way in #383

2023-06-27 09:27 UTC, andrea-pasquale commented on src/qibocal/protocols/characterization/fast_reset/utils.py
Probably you created an empty file and you pushed it accidentally

2023-06-27 10:46 UTC, Jacfomg commented on src/qibocal/protocols/characterization/fast_reset/utils.py
Ah the `utils.py`, yeah it's empty I just put it there to keep how the other folders looked like. For now it doesn't have a use.

2023-06-27 11:24 UTC, Jacfomg commented on src/qibocal/protocols/characterization/fast_reset/fast_reset.py
> +    """Plotting function for FastReset."""
Yeah, it will be easier for me to put it in loops as the acquisition once it's working

2023-06-27 12:18 UTC, andrea-pasquale commented on src/qibocal/protocols/characterization/fast_reset/fast_reset.py
> +        else:
Unless you are going to append things more than once for a given combination of `qubit,state,fast_reset` you could probably drop this and keep only the line in the `else` statement.

2023-06-27 12:21 UTC, Jacfomg commented on src/qibocal/protocols/characterization/fast_reset/fast_reset.py
> +        else:
True, I don't need them anymore.

2023-07-08 10:37 UTC, Edoardo-Pedicillo commented
> Perhaps @Edoardo-Pedicillo did something similar with single shot classification, I'm not so sure.

Not with plotly, I tried smething like 
```python
z=[[1, 20, 30],
    [20, 1, 60],
    [30, 60, 1]]

z_text = [[str(y) for y in x] for x in z]

fig.add_trace(

        go.Heatmap(
            z=z,
            text=z_text,
            texttemplate="%{text}",
            textfont={"size":20}
        ),
        row=1,
        col=1,
    )
```
it works locally (in a Jupyter Notebook), but not in the report, maybe you will find the error in the function that generate the reports.

2023-07-08 10:44 UTC, Edoardo-Pedicillo requested changes
I suggest plotting the confusion matrix with the relative values, in this way you can also use a single color legend.

2023-07-10 08:12 UTC, andrea-pasquale reviewed
Tested on hardware and it works.
Some other suggestions very similar to #435

2023-07-10 08:12 UTC, andrea-pasquale commented on src/qibocal/protocols/characterization/fast_reset/fast_reset.py
> +    error_nfr0 = (nshots - state0_count_0nfr) / nshots
This can be moved to fit and we can replace `np.unique` with `np.count_nonzero`.

2023-07-10 08:12 UTC, andrea-pasquale commented on src/qibocal/protocols/characterization/fast_reset/fast_reset.py
> +    )
```suggestion
    fitting_report += f"{qubit} | Error FR0: {error_fr0:.6f}<br>"
    fitting_report += f"{qubit} | Error FR1: {error_fr1:.6f}<br>"
    fitting_report += (
        f"{qubit} | Fidelity FR: {(1 - (error_fr0 + error_fr1)/2):.6f}<br>"
    )
    fitting_report += f"{qubit} | Error NFR0: {error_nfr0:.6f}<br>"
    fitting_report += f"{qubit} | Error NFR1: {error_nfr1:.6f}<br>"
    fitting_report += (
        f"{qubit} | Fidelity NFR: {(1 - (error_nfr0 + error_nfr1)/2):.6f}<br>"
    )
```
Here it would be better to write more explicitly in the table what are the errors.

2023-07-24 12:28 UTC, andrea-pasquale approved these changes
Thanks @Jacfomg, just a very small suggestion.
Btw, I had to merge main both in https://github.com/qiboteam/qibolab/pull/506 and https://github.com/qiboteam/qibolab_platforms_qrc/pull/28 to make it work.

2023-07-24 12:28 UTC, andrea-pasquale commented on src/qibocal/protocols/characterization/fast_reset/fast_reset.py
> +        f"q{qubit}/r | Fidelity [Fast Reset]: {fit.fidelity_fr[qubit]:.6f}<br>"
```suggestion
        f"{qubit} | Fidelity [Fast Reset]: {fit.fidelity_fr[qubit]:.6f}<br>"
```

2023-07-24 12:28 UTC, andrea-pasquale commented on src/qibocal/protocols/characterization/fast_reset/fast_reset.py
> +        f"q{qubit}/r | Fidelity [Relaxation Time]: {fit.fidelity_nfr[qubit]:.6f}<br>"
```suggestion
        f"{qubit}| Fidelity [Relaxation Time]: {fit.fidelity_nfr[qubit]:.6f}<br>"
```

2023-07-24 13:35 UTC, merged