Clifford simultaneous filtered rb
qiboteam/qibocal pull request #412
Opened 2023-06-20 13:27 UTC by vodovozovaliza

(Juan): This will need https://github.com/qiboteam/qibo/pull/1015 to save and load circuits properly

Checklist:
- [ ] Reviewers confirm new code works as expected.
- [ ] Tests are passing.
- [ ] Coverage does not decrease.
- [ ] Documentation is updated.

2023-08-21 10:54 UTC, andrea-pasquale commented
@vodovozovaliza @wilkensJ what is the status of this PR?

2023-09-11 07:37 UTC, andrea-pasquale commented
@ingoroth is someone going to work on this?

2023-09-13 05:39 UTC, ingoroth commented
At the moment nobody is actively working on this anymore.  @vodovozovaliza might find some time to push this again at some point in the future.  Maybe @Jacfomg has capacities to take over.

2023-09-13 08:08 UTC, Jacfomg commented
> At the moment nobody is actively working on this anymore. @vodovozovaliza might find some time to push this again at some point in the future. Maybe @Jacfomg has capacities to take over.

We can talk about it next week if it's ok

2023-09-28 08:39 UTC, Jacfomg commented
@andrea-pasquale this still has the meta_data mess on both routines, apart from that test should pass. Data saving and loading may need to be revised as it's a bit of a mess, but for now it works.

2023-09-28 13:04 UTC, Jacfomg commented
@andrea-pasquale Ramsey tests are crashing here as well ?

2023-09-28 13:50 UTC, andrea-pasquale commented
> @andrea-pasquale Ramsey tests are crashing here as well ?

This is weird. I relaunched the CI. Let's see what happens.

2023-09-29 08:44 UTC, andrea-pasquale reviewed
Thanks @Jacfomg you can find below some comments.

I think that the new protocols only works using `qq auto`.
If I run `qq acquire` I don't see anything which is expected I think (?)
Running `qq fit` doesn't produce the correct html report. I guess that the results are not loaded properly.
Apart from the point above, the code looks already in a good shape.

2023-09-29 08:44 UTC, andrea-pasquale commented on pyproject.toml
> +qibo =  { git = "https://github.com/qiboteam/qibo.git", branch = "master", develop = true}
Remember to change this before merging. I have a `do not merge` tag and also a `require qibo release` tag.

2023-09-29 08:44 UTC, andrea-pasquale commented on src/qibocal/protocols/characterization/randomized_benchmarking/clifford_filtered_rb.py
> +    Every irrep has a projector charactarized with a bit string
```suggestion
    Every irrep has a projector characterized with a bitstring
```

2023-09-29 08:44 UTC, andrea-pasquale commented on src/qibocal/protocols/characterization/randomized_benchmarking/clifford_filtered_rb.py
> +        # FIXME implement this check outside acquisition
```suggestion
        #FIXME: implement this check outside acquisition
```

2023-09-29 08:44 UTC, andrea-pasquale commented on src/qibocal/protocols/characterization/randomized_benchmarking/data.py
> +    return new_circuit
Are these still necessary or are they now implemented in qibo?

2023-09-29 08:44 UTC, andrea-pasquale commented on src/qibocal/protocols/characterization/randomized_benchmarking/clifford_filtered_rb.py
> +    fit_results: pd.DataFrame
This is fine for now. However, for the future can we please trying to get rid of pd.DataFrame if they are not strictly necessary?

2023-09-29 08:44 UTC, andrea-pasquale commented on src/qibocal/protocols/characterization/randomized_benchmarking/clifford_filtered_rb.py
> +                        )
I'm not sure about this performance wise... do we really need 3 for loops? It would be nice to try to vectorize some of these operations.

2023-09-29 08:44 UTC, andrea-pasquale commented on src/qibocal/protocols/characterization/randomized_benchmarking/clifford_filtered_rb.py
> +    # TODO: fit doesn't get loaded on acquisition tests
I think this is expected

2023-09-29 08:44 UTC, andrea-pasquale commented on src/qibocal/protocols/characterization/randomized_benchmarking/clifford_filtered_rb.py
> +        return p01 / (p0 * p1)
It should be better to move this function out of this scope and document it properly

2023-09-29 08:44 UTC, andrea-pasquale commented on src/qibocal/protocols/characterization/randomized_benchmarking/utils.py
> +        return "+" if float(val) > -PRECISION_TOL else "-"
Missing docstring

2023-09-29 08:44 UTC, andrea-pasquale commented on src/qibocal/protocols/characterization/randomized_benchmarking/utils.py
> +        # inf uncertainty
Here as well

2023-10-02 06:36 UTC, Jacfomg commented on src/qibocal/protocols/characterization/randomized_benchmarking/data.py
> +    return new_circuit
Yes, this just uses the small serialize I made for the gates and I think we should keep until the circuit gets a proper serialize.

2023-10-02 06:37 UTC, Jacfomg commented on src/qibocal/protocols/characterization/randomized_benchmarking/clifford_filtered_rb.py
> +    # TODO: fit doesn't get loaded on acquisition tests
I know, but they always want the fit in the plotting

2023-10-02 06:51 UTC, Jacfomg commented on src/qibocal/protocols/characterization/randomized_benchmarking/clifford_filtered_rb.py
> +                        )
I'm not sure if that would be simple to do

2023-10-02 07:08 UTC, Jacfomg commented on pyproject.toml
> +qibo =  { git = "https://github.com/qiboteam/qibo.git", branch = "master", develop = true}
Should I ask @stavros11 for a release or something ?

2023-10-02 07:29 UTC, andrea-pasquale commented on pyproject.toml
> +qibo =  { git = "https://github.com/qiboteam/qibo.git", branch = "master", develop = true}
I think we are planning to make a new release of qibo soon, right @scarrazza?

2023-10-05 08:15 UTC, andrea-pasquale commented
@Jacfomg feel free to merge main and update the qibo dep in `pyproject.toml`.

2023-10-05 10:09 UTC, andrea-pasquale commented
> @Jacfomg feel free to merge main and update the qibo dep in `pyproject.toml`.

I believe that there is an issue with latest release of qibolab. I'm having troubles also here #539 :(

2023-10-05 10:58 UTC, Jacfomg commented
I think those tests should pass once we merge #499 that has the coupler changes needed.

2023-10-12 08:23 UTC, andrea-pasquale reviewed
Thanks for the updates @Jacfomg.
A few more comments.
I tried to run the protocol using simulation
![image](https://github.com/qiboteam/qibocal/assets/49183315/b93b20f2-5be9-4197-92b0-6a95ec634f49)
Perhaps it is better to move the legend under the plot with a horizontal layout.
Moreover, I'm seeing that in the matrix a color is shown as `nan` is it normal or am I doing something wrong?

2023-10-12 08:23 UTC, andrea-pasquale commented on src/qibocal/protocols/characterization/randomized_benchmarking/clifford_filtered_rb.py
> +    # data = pd.DataFrame(data_list)
Can this be removed? Or is it part of the comment above?

2023-10-12 08:23 UTC, andrea-pasquale commented on src/qibocal/protocols/characterization/randomized_benchmarking/clifford_filtered_rb.py
> +    """Builds the table for the qq pipe, calls the plot function of the result object
Here you will probably need to update the table given that we merged #546.

2023-10-20 13:25 UTC, andrea-pasquale commented
@Jacfomg I believe that if we manage to run at least once on hardware without errors we should be ready to merge this PR.

2023-10-25 12:50 UTC, andrea-pasquale commented on src/qibocal/protocols/characterization/randomized_benchmarking/clifford_filtered_rb.py
Just a quick comment here.
Even if the parameters/data/results are the same as the `StandardRB` could you please add a separate class for each just for readability?

2023-10-25 12:51 UTC, andrea-pasquale commented
Executed on hardware: http://login.qrccluster.com:9000/JdmSqP64RrG-t4WRSd9zhw==/

2023-10-25 12:51 UTC, andrea-pasquale commented
Could you also fix conflicts?

2023-11-06 17:13 UTC, Edoardo-Pedicillo requested changes
Documentation is missing for some functions; it would be great to add it.

2023-11-06 17:49 UTC, Edoardo-Pedicillo commented on src/qibocal/protocols/characterization/randomized_benchmarking/clifford_filtered_rb.py
> +            ) + 0.1
Why is 0.1 added to sigma?

2023-11-07 07:48 UTC, ingoroth commented on src/qibocal/protocols/characterization/randomized_benchmarking/circuit_tools.py
> +    else:
I agree.  I think the original functionality of passing either a single `Gate` or a `Circuit` is sufficient.  I guess the motivation was to be able to pass a layer of parallel single qubit gates. But this can also be cast to `Circuit` when passed.

2023-11-07 07:51 UTC, ingoroth commented on src/qibocal/protocols/characterization/randomized_benchmarking/circuit_tools.py
> +    # Generate a layer to get nqubits.
In principle there is no need to pass nqubits as it is implicit in the output of `layer_gen.__call__()`.  But I don't like that now the first call of the generator is not added to the circuit.  This makes it harder when one actually has  to reproduce the result of a generator, say by restoring the rng state.

2024-03-29 09:12 UTC, Edoardo-Pedicillo commented
This PR is outdated with the main, and it seems it will not be concluded, btw the protocol is interesting so I have opened #779

2024-03-29 09:12 UTC, Edoardo-Pedicillo commented
This PR is outdated with the main, and it seems it will not be concluded, btw the protocol is interesting so I have opened #779

2024-03-29 09:12 UTC, closed without merging