Readout characterization
qiboteam/qibocal pull request #435
Opened 2023-07-07 07:34 UTC by Jacfomg

As per https://arxiv.org/abs/2106.06173. Calculate Fidelity and QND-ness of our readout.

Checklist:
- [ ] Reviewers confirm new code works as expected.
- [ ] Tests are passing.
- [ ] Coverage does not decrease.
- [ ] Documentation is updated.

2023-07-10 08:04 UTC, andrea-pasquale requested changes
Thanks @Jacfomg. I tested the routine on hardware and it works.
I have some suggestions, mainly moving the computation of the fidelity and QNDness from the plot to the fit and some general improvements.

2023-07-10 08:04 UTC, andrea-pasquale commented on src/qibocal/protocols/characterization/readout_characterization.py
> +                    ro_pulses[qubit].append(ro_pulse)
Since this block of code is repeated below you can put it out of the `if-else` statement.

2023-07-10 08:04 UTC, andrea-pasquale commented on src/qibocal/protocols/characterization/readout_characterization.py
> +        self.data[qubit, state, number_readout] = np.rec.array(ar)
As in the other PR maybe we can drop the `number_readout` considering that the `number_readout` is just the row of the array.

2023-07-24 13:04 UTC, andrea-pasquale approved these changes

2023-07-25 07:07 UTC, Edoardo-Pedicillo approved these changes

2023-07-25 08:47 UTC, merged