adapting flux routines fitting to the latest version of qibocal
qiboteam/qibocal pull request #437
Opened 2023-07-07 14:23 UTC by DavidSarlle

WIP: Checking result in real chip.

Checklist:
- [ ] Reviewers confirm new code works as expected.
- [ ] Tests are passing.
- [ ] Coverage does not decrease.
- [ ] Documentation is updated.

2023-07-11 00:21 UTC, AlejandroSopena commented
The fits for the resonator are already working. It is necessary to have a maximum and a minimum. I attach two reports with the theoretical fit obtained using a first-order approximation ([report1.pdf](https://github.com/qiboteam/qibocal/files/12009470/report1.pdf)) and with the following correction ([report2.pdf](https://github.com/qiboteam/qibocal/files/12009471/report2.pdf)), which also allows for the estimation of `Ec` and `Ej`. For the qubit, it should also work because in this case, the fit is simpler and is contained within the fit of the resonator, although I haven't tested it yet.

2023-07-11 00:50 UTC, AlejandroSopena commented
Some comments about the parameters. Ideally, the asymmetry $d$ is 0. $f_{qs}$ is an initial estimate of the qubit frequency at the sweetspot. In the transmon limit ($E_J/E_C \gg 1$), $Ec = |\alpha|$ where $\alpha$ is the anharmonicity.

2023-07-11 14:15 UTC, andrea-pasquale commented
Thanks @DavidSarlle and @AlejandroSopena, is this ready to review?

2023-07-11 20:45 UTC, DavidSarlle commented
Yes @andrea-pasquale , please review it.

2023-07-12 07:39 UTC, DavidSarlle commented
@andrea-pasquale one more thing. I noticed that we are now plotting the offset in the sweetspot instead of the sweetspot value itself in the fitting report of the flux routines. Why did you changed it? To me it is more intuitive for the user if we return the value od the sweetspot. What d you think?

2023-07-12 07:55 UTC, andrea-pasquale commented
> @andrea-pasquale one more thing. I noticed that we are now plotting the offset in the sweetspot instead of the sweetspot value itself in the fitting report of the flux routines. Why did you changed it? To me it is more intuitive for the user if we return the value od the sweetspot. What d you think?

I don't understand. You mean that we should plot relative to the sweetspot?

2023-07-12 08:09 UTC, andrea-pasquale requested changes
Thanks @DavidSarlle and @AlejandroSopena 
I think the code looks ok, I would like to have more documentation on the functions used for the fitting otherwise I cannot review properly.
Moreover, I tried to test it with Zurichs and IQM. It worked once or twice but now I cannot run anymore and the code fails with the following error.
```sh
ValueError: cannot reshape array of size 1600 into shape (84,20)
```
I think that there is a bug somewhere.

2023-07-12 08:09 UTC, andrea-pasquale commented on src/qibocal/protocols/characterization/flux_dependence/utils.py
> +def flux_dependence_plot(data, fit, qubit, label):
Instead of `label` you can check the instance of the `data` argument.
See for example here: 
https://github.com/qiboteam/qibocal/blob/a5cca612c8c167cc93a805b69a4c28796cee024c/src/qibocal/protocols/characterization/rabi/utils.py#L28-L36

2023-07-12 08:09 UTC, andrea-pasquale commented on src/qibocal/protocols/characterization/flux_dependence/utils.py
> +            if {"Ec", "Ej"}.issubset(set(params.keys())):
```suggestion
            if all(param in params for param in ['Ec', 'Ej']):
``
I think that this is more readable

2023-07-12 08:22 UTC, DavidSarlle commented
> > @andrea-pasquale one more thing. I noticed that we are now plotting the offset in the sweetspot instead of the sweetspot value itself in the fitting report of the flux routines. Why did you changed it? To me it is more intuitive for the user if we return the value od the sweetspot. What d you think?
> 
> I don't understand. You mean that we should plot relative to the sweetspot?

Forget it, I was wrong. I was thinking that the sweetspot fitted was the offset found relative to the current sweetspot, but it is not. Let me talk with @AlejandroSopena

2023-07-13 05:56 UTC, DavidSarlle commented on src/qibocal/protocols/characterization/flux_dependence/qubit_flux_dependence.py
> +        Ej = data.Ej[qubit]  # qubit_data["Ej"]
Done

2023-07-13 05:57 UTC, DavidSarlle commented on src/qibocal/protocols/characterization/flux_dependence/qubit_flux_dependence.py
> +        #         log.warning("qubit_flux_fit: the fitting was not succesful")
Done

2023-07-13 06:03 UTC, DavidSarlle commented on src/qibocal/protocols/characterization/flux_dependence/resonator_flux_dependence.py
> +    f_rh: dict[QubitId, int] = field(default_factory=dict)
replaced by bare_resonator_frequency

2023-07-13 06:04 UTC, DavidSarlle commented on src/qibocal/protocols/characterization/flux_dependence/resonator_flux_dependence.py
> +        Ej = data.Ej[qubit]  # qubit_data["Ej"]
removed comments

2023-07-13 06:04 UTC, DavidSarlle commented on src/qibocal/protocols/characterization/flux_dependence/utils.py
> +    # fitted_parameters = xi, d, g, Ec, Ej, f_rh, f_qs, f_r_offset, C_ii
Removed

2023-07-13 06:05 UTC, DavidSarlle commented on src/qibocal/protocols/characterization/flux_dependence/utils.py
> +    return dummy
Done

2023-07-13 06:13 UTC, DavidSarlle commented on src/qibocal/protocols/characterization/flux_dependence/utils.py
> +def flux_dependence_plot(data, fit, qubit, label):
Implemeented

2023-07-13 06:16 UTC, DavidSarlle commented on src/qibocal/protocols/characterization/flux_dependence/utils.py
> +            if {"Ec", "Ej"}.issubset(set(params.keys())):
Implemented

2023-07-13 06:22 UTC, DavidSarlle commented on src/qibocal/protocols/characterization/flux_dependence/utils.py
> +    return np.sqrt(G)
@AlejandroSopena could you add a line explaining each aux function of the fitting?

2023-07-13 06:25 UTC, DavidSarlle commented
> Thanks @DavidSarlle and @AlejandroSopena I think the code looks ok, I would like to have more documentation on the functions used for the fitting otherwise I cannot review properly. Moreover, I tried to test it with Zurichs and IQM. It worked once or twice but now I cannot run anymore and the code fails with the following error.
> 
> ```shell
> ValueError: cannot reshape array of size 1600 into shape (84,20)
> ```
> 
> I think that there is a bug somewhere.

I could not reproduce the problem qblox. Can you try again a see if it is a problem of the ZI driver and the results that it is returning? It is weird that it worked once and afterthat, you can not run anymore the routine. The code is not raising any error with qblox and the code is only doing postprocessing calcultations, so I do not understand why is affecting the instrument itself...

2023-07-13 22:11 UTC, AlejandroSopena commented
The qubit fits are working (see example [report_q2.pdf](https://github.com/qiboteam/qibocal/files/12044804/reports_2023-07-13_20_25_06_Alejandro_1q.pdf)) , and the documentation is updated.

2023-07-14 09:34 UTC, DavidSarlle commented on src/qibocal/protocols/characterization/flux_dependence/utils.py
> +    return np.sqrt(G)
Documentation included

2023-07-14 09:35 UTC, DavidSarlle commented
> Thanks @DavidSarlle and @AlejandroSopena I think the code looks ok, I would like to have more documentation on the functions used for the fitting otherwise I cannot review properly. Moreover, I tried to test it with Zurichs and IQM. It worked once or twice but now I cannot run anymore and the code fails with the following error.
> 
> ```shell
> ValueError: cannot reshape array of size 1600 into shape (84,20)
> ```
> 
> I think that there is a bug somewhere.

Seems that the error is not raised anymore after the changes made. At least i can not reproduce it again

2023-07-14 09:35 UTC, DavidSarlle commented on src/qibocal/protocols/characterization/flux_dependence/qubit_flux_dependence.py
> +                qubits[qubit].anharmonicity / 2
@aorgazf suggestion. I do not have the reference for this, probably Alvaro has it.

2023-07-17 10:05 UTC, Edoardo-Pedicillo commented
I tried to test the routine, but I get this error 

``` 
line 113, in _acquisition
Ec[qubit] = qubits[qubit].Ec
AttributeError: 'QubitPair' object has no attribute 'Ec' 
```
Could you please specify which `qibolab` and `qibolab_platforms_qrc` branches should I use?

2023-07-17 10:19 UTC, DavidSarlle commented
@Edoardo-Pedicillo it should work with qibolab main. Also with qiab_platforms_main. Both branches include the new qubit params needed (Ec, Ej and g) for the flux fittings.

2023-07-17 11:29 UTC, aorgazf commented
Hi @AlejandroSopena,
I've been testing your fit on qw5q_gold qubits.
It seems to work pretty good, except for these two things:
- [ ] if the range of the bias is large so that the branches of the parabola exit the frame from the left side, the fit fails:
![image](https://github.com/qiboteam/qibocal/assets/55031026/9a6b30f2-d9c6-40de-aedb-804f55b52c2f)
- [ ] the MSR values seem to have been negated, is there any reason for that?
thanks!

2023-07-17 12:36 UTC, Edoardo-Pedicillo reviewed
Thanks @DavidSarlle @AlejandroSopena

2023-07-17 12:36 UTC, Edoardo-Pedicillo commented on src/qibocal/protocols/characterization/flux_dependence/qubit_flux_dependence.py
> +        else:
According to 
https://github.com/qiboteam/qibolab/blob/6dbf188be4f19e279547400bbfd862a2995e85bf/src/qibolab/qubits.py#L37-L38C1 there are no other possibilities, so you can drop this and replace the `elif` with an `else`.

2023-07-17 12:36 UTC, Edoardo-Pedicillo commented on src/qibocal/protocols/characterization/flux_dependence/utils.py
> +        msr = -msr
Maybe it is better to move this part in each routine

2023-07-17 15:45 UTC, DavidSarlle commented on src/qibocal/protocols/characterization/flux_dependence/qubit_flux_dependence.py
> +    """Flux spectroscopy transition type ("0->1" or "0->2")."""
Added default va;ue and modified values to "01" or "02"

2023-07-17 15:58 UTC, DavidSarlle commented on src/qibocal/protocols/characterization/flux_dependence/qubit_flux_dependence.py
> +        else:
modified

2023-07-17 16:06 UTC, DavidSarlle commented on src/qibocal/protocols/characterization/flux_dependence/qubit_flux_dependence.py
> +        type=SweeperType.OFFSET,
ok, thanks

2023-07-17 16:09 UTC, DavidSarlle commented on src/qibocal/protocols/characterization/flux_dependence/qubit_flux_dependence.py
> +        scaler = 10**9
Done

2023-07-17 16:10 UTC, DavidSarlle commented on src/qibocal/protocols/characterization/flux_dependence/resonator_flux_dependence.py
> +        scaler = 10**9
done

2023-07-17 16:10 UTC, DavidSarlle commented on src/qibocal/protocols/characterization/flux_dependence/resonator_flux_dependence.py
> +                    # p0=[max_c, xi, 0, f_q_0 / bare_resonator_frequency, g, bare_resonator_frequency],
done

2023-07-17 16:11 UTC, DavidSarlle commented on src/qibocal/protocols/characterization/flux_dependence/resonator_flux_dependence.py
> +                # fitted_parameters = xi, d, g, Ec, Ej, bare_resonator_frequency, f_qs, f_r_offset, C_ii
done

2023-07-17 16:50 UTC, DavidSarlle commented
> Hi @AlejandroSopena, I've been testing your fit on qw5q_gold qubits. It seems to work pretty good, except for these two things:
> 
> * [ ]  if the range of the bias is large so that the branches of the parabola exit the frame from the left side, the fit fails:
>   ![image](https://user-images.githubusercontent.com/55031026/253926996-9a6b30f2-d9c6-40de-aedb-804f55b52c2f.png)
> * [x]  the MSR values seem to have been negated, is there any reason for that?
>   thanks!

second point fixed

2023-07-17 20:57 UTC, AlejandroSopena commented
> > Thanks @DavidSarlle and @AlejandroSopena I think the code looks ok, I would like to have more documentation on the functions used for the fitting otherwise I cannot review properly. Moreover, I tried to test it with Zurichs and IQM. It worked once or twice but now I cannot run anymore and the code fails with the following error.
> > ```shell
> > ValueError: cannot reshape array of size 1600 into shape (84,20)
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > I think that there is a bug somewhere.
> 
> Seems that the error is not raised anymore after the changes made. At least i can not reproduce it again

fixed

2023-07-17 21:06 UTC, AlejandroSopena commented
> > Hi @AlejandroSopena, I've been testing your fit on qw5q_gold qubits. It seems to work pretty good, except for these two things:
> > 
> > * [ ]   if the range of the bias is large so that the branches of the parabola exit the frame from the left side, the fit fails:
> >   ![image](https://user-images.githubusercontent.com/55031026/253926996-9a6b30f2-d9c6-40de-aedb-804f55b52c2f.png)
> > * [x]   the MSR values seem to have been negated, is there any reason for that?
> >   thanks!
> 
> second point fixed

I have been able to reproduce the first point and its already fixed  [report.pdf](https://github.com/qiboteam/qibocal/files/12073853/reports_2023-07-18_00_53_42_Alejandro_1q.pdf)

2023-07-18 03:08 UTC, aorgazf commented
Thanks a lot @AlejandroSopena  and @DavidSarlle
I've tested the latest changes and it works

2023-07-18 07:28 UTC, DavidSarlle commented
@andrea-pasquale I think the Pr is ready to be merged.

2023-07-18 09:02 UTC, andrea-pasquale commented on src/qibocal/protocols/characterization/flux_dependence/resonator_flux_dependence.py
> +                # fitted_parameters = xi, d, g, Ec, Ej, bare_resonator_frequency, f_qs, f_r_offset, C_ii
This one has not been removed.

2023-07-18 09:10 UTC, andrea-pasquale commented on src/qibocal/protocols/characterization/flux_dependence/qubit_flux_dependence.py
> +        type=SweeperType.OFFSET,
We can change it to `OFFSET` I believe the behavior should be consistent for all drivers.

2023-07-19 06:20 UTC, DavidSarlle commented on src/qibocal/protocols/characterization/flux_dependence/resonator_flux_dependence.py
> +                # fitted_parameters = xi, d, g, Ec, Ej, bare_resonator_frequency, f_qs, f_r_offset, C_ii
done

2023-07-19 06:21 UTC, DavidSarlle commented on src/qibocal/protocols/characterization/flux_dependence/qubit_flux_dependence.py
> +        type=SweeperType.OFFSET,
ok, thanks

2023-07-19 06:32 UTC, DavidSarlle commented
> Thanks @DavidSarlle. Coverage is not passing, I think because dummy does not have `E_c` and `E_j` which are different from zero. Could you please add also the `02` protocol in this [file](https://github.com/qiboteam/qibocal/blob/david/flux_routines_fitting/tests/runcards/protocols.yml) so that it will be tested?

@andrea-pasquale I have included the qubit flux 02 transition in the protocols.yml
Do I have to do something with dummy for passing the coverage?

2023-07-24 13:56 UTC, andrea-pasquale commented
Thanks @DavidSarlle and @AlejandroSopena. It seems to be working as expected.
I think that this fitting could be improved (I tried to run it and sometimes the fitted sweetspot it is way different from the expected sweetspot). Maybe we need to choose the bounds more accurately, also the fitting for the 02 transition will fail if the same scan there are points of the 01 transition...
Moreover, I think that we might want to store in the runcard other parameters other than the sweetspot or the frequency, like E_c or E_j.
For now we can merge it, but I want to open an issue to remember what I just put here in this comment.

2023-07-24 13:57 UTC, merged