Chevron with coupler support
qiboteam/qibocal pull request #499
Opened 2023-08-29 10:42 UTC by Jacfomg

Using https://github.com/qiboteam/qibolab/pull/508 and https://github.com/qiboteam/qibolab_platforms_qrc/pull/49 for the couplers this add the needed coupler pulse. Also, it won't break non-coupler platforms.

Checklist:
- [ ] Reviewers confirm new code works as expected.
- [ ] Tests are passing.
- [ ] Coverage does not decrease.
- [ ] Documentation is updated.
- [ ] Compatibility with Qibo modules (Please edit this section if the current pull request is not compatible with the following branches).
    - [ ] Qibo: `master`
    - [ ] Qibolab:  https://github.com/qiboteam/qibolab/pull/508
    - [ ] Qibolab_platforms_qrc: `main`

2023-08-29 13:59 UTC, andrea-pasquale commented on pyproject.toml
>  qibo = "^0.1.9"
```suggestion
qibo = "^0.2.0"
```
This should fix tests @Jacfomg

2023-08-29 15:29 UTC, andrea-pasquale commented on pyproject.toml
>  qibo = "^0.1.9"
Nevermind :(

2023-09-01 14:16 UTC, andrea-pasquale commented
The fix for this has been implemented already in #501 and #406

https://github.com/qiboteam/qibocal/blob/666f533d61d69c8026ae8132f8abc0dcad5a42be/tests/test_randomized_benchmarking.py#L171

I believe that both should be merged soon

2023-09-11 07:26 UTC, andrea-pasquale requested changes
I tested the chevron using qblox and it raised the following error:

```sh
  return self.qubits[qubit].native_gates.RX.pulse(start, relative_phase)
AttributeError: 'NoneType' object has no attribute 'pulse'
```
Probably there is something wrong in the corresponding PR in qibolab.

2023-09-11 07:38 UTC, Jacfomg commented
> I tested the chevron using qblox and it raised the following error:
> 
> 
> 
> ```sh
> 
>   return self.qubits[qubit].native_gates.RX.pulse(start, relative_phase)
> 
> AttributeError: 'NoneType' object has no attribute 'pulse'
> 
> ```
> 
> Probably there is something wrong in the corresponding PR in qibolab.

Okay, I will take a look

2023-09-28 10:47 UTC, Jacfomg commented
@andrea-pasquale take a look when the asking 2q gate routines to act on `qubits: [2,3]` or `qubits: [3,2]`. I did some reordering for them to pass tests but maybe we want something different.

2023-10-05 10:31 UTC, Jacfomg commented
If cov gets fixed this should be ready now

2023-10-05 13:28 UTC, andrea-pasquale approved these changes
Thanks @Jacfomg

2023-10-09 12:23 UTC, Edoardo-Pedicillo approved these changes

2023-10-09 12:23 UTC, merged