Qutrit classifier
qiboteam/qibocal pull request #543
Opened 2023-10-03 14:38 UTC by Edoardo-Pedicillo

As the title says

Checklist:
- [ ] Reviewers confirm new code works as expected.
- [ ] Tests are passing.
- [ ] Coverage does not decrease.
- [ ] Documentation is updated.
- [ ] Compatibility with Qibo modules (Please edit this section if the current pull request is not compatible with the following branches).
    - [ ] Qibo: `master`
    - [ ] Qibolab: qiboteam/qibolab#615
    - [ ] Qibolab_platforms_qrc: `main`

2023-10-19 04:38 UTC, andrea-pasquale commented
@Edoardo-Pedicillo now that I've tested #539 you should be able to run this on hardware using qiboteam/qibolab_platforms_qrc#65 (on qubit 1 and 4).

2023-10-23 08:03 UTC, andrea-pasquale commented on src/qibocal/protocols/characterization/qutrit_classification.py
> +        )
I don't know if this will matter but this is wrong for the RX sequence.
We should measure with `start=rx_pulse.finish`, right?

2023-10-24 06:26 UTC, GabrielePalazzo requested changes

2023-10-24 06:53 UTC, GabrielePalazzo approved these changes

2023-10-24 08:11 UTC, andrea-pasquale reviewed
Thanks @Edoardo-Pedicillo for implementing this.
You can find below some comments.
I will test on hardware later and I will approve.

2023-10-24 08:11 UTC, andrea-pasquale commented on src/qibocal/protocols/characterization/qutrit_classification.py
> +    # state1_sequence: RX - MZ
Outdated comments

2023-10-24 08:11 UTC, andrea-pasquale commented on src/qibocal/protocols/characterization/qutrit_classification.py
> +    Args:
Here I would add a minimal description of the protocol

2023-10-24 08:11 UTC, andrea-pasquale commented on src/qibocal/protocols/characterization/qutrit_classification.py
> +    # create a DataUnits object to store the results
Outdated comment

2023-10-24 08:11 UTC, andrea-pasquale commented on src/qibocal/protocols/characterization/qutrit_classification.py
> +    )  # TODO: implement a qutrit classifiers hpars (?)
I think it is better to remove both qutrit and qubits classifiers hpars for now. When you actually plug them in qibolab we could re-add them easily

2023-10-24 08:11 UTC, andrea-pasquale commented on src/qibocal/protocols/characterization/qutrit_classification.py
> +qutrit_classification = Routine(_acquisition, _fit, _plot, _update)
Missing docstring for protocol object

2023-10-24 08:11 UTC, andrea-pasquale commented on src/qibocal/update.py
> +    platform.qubits[qubit].qutrit_classifiers_hpars = hpars
This can be removed for now (see comment above).

2023-10-24 13:13 UTC, andrea-pasquale commented on src/qibocal/protocols/characterization/qutrit_classification.py
> +    fitting_report = None
```suggestion
    fitting_report = ""
```
Small fix I found after running on hardware

2023-10-25 09:29 UTC, andrea-pasquale approved these changes
Thanks @Edoardo-Pedicillo, LGTM.

2023-10-25 09:29 UTC, merged