Couplers Resonator Spec
qiboteam/qibocal pull request #565
Opened 2023-10-17 14:05 UTC by Jacfomg

Draft routine, some loops missing and remove fitting from reused plots. Works with qibolab :https://github.com/qiboteam/qibolab/pull/623 and qibolab_platforms []

![image](https://github.com/qiboteam/qibocal/assets/19141117/c350d918-7eae-481c-962a-77356bbb05f8)

Checklist:
- [ ] Reviewers confirm new code works as expected.
- [ ] Tests are passing.
- [ ] Coverage does not decrease.
- [ ] Documentation is updated.
- [ ] Compatibility with Qibo modules (Please edit this section if the current pull request is not compatible with the following branches).
    - [ ] Qibo: `master`
    - [ ] Qibolab: `main`
    - [ ] Qibolab_platforms_qrc: `main`

2023-10-20 09:15 UTC, andrea-pasquale requested changes
Thanks @Jacfomg for implementing this.
You can find below some comments.
Mainly for improving the code.
I believe that there are also a lot of TODOs, are you planning to address those in this PR?

2023-10-20 09:15 UTC, andrea-pasquale commented on src/qibocal/update.py
> +        platform.couplers[qubit].flux.offset = sweetspot
I think this line is not needed (it was removed from qibolab).
Could you please also add tests for this update method?

2023-10-20 09:15 UTC, andrea-pasquale commented on src/qibocal/protocols/characterization/flux_dependence/utils.py
> +        )
I am not really a fan of this. Perhaps it is better to add the option to disable this line directly in the plot.

2023-10-20 09:15 UTC, andrea-pasquale commented on src/qibocal/protocols/characterization/flux_dependence/utils.py
> +    if fit is not None and not data.__class__.__name__ == "CouplerSpectroscopyData":
Uhm I am not sure... 
For the qubit spectroscopy we could surely add something to extract some parameters in the vicinity of the avoided crossing.

2023-10-20 09:15 UTC, andrea-pasquale commented on src/qibocal/protocols/characterization/couplers/utils.py
> +        )
Once we merge main you should probably delete this and adopt the new method that @Edoardo-Pedicillo coded in #541

2023-10-20 09:15 UTC, andrea-pasquale commented on src/qibocal/protocols/characterization/couplers/coupler_resonator_spectroscopy.py
> +    if 1 == 0:
?

2023-10-20 09:15 UTC, andrea-pasquale commented on src/qibocal/protocols/characterization/couplers/coupler_resonator_spectroscopy.py
> +    """Post-processing function for CouplerResonatorSpectroscopy."""
If you don't want to perform the fit you can also use a dummy_fit.

2023-10-20 09:15 UTC, andrea-pasquale commented on src/qibocal/protocols/characterization/couplers/coupler_resonator_spectroscopy.py
> +        )
This will not work once we merge main because of #541

2023-10-20 09:15 UTC, andrea-pasquale commented on src/qibocal/protocols/characterization/couplers/coupler_resonator_spectroscopy.py
> +    # TODO: fix loop
?

2023-10-20 09:15 UTC, andrea-pasquale commented on src/qibocal/protocols/characterization/couplers/coupler_qubit_spectroscopy.py
> +        )
See same comment for resonator routine

2023-10-20 09:50 UTC, Jacfomg commented
I will try to do as much work on new routines while this calibration lasts and I would go over them later, help is appreciated of course

2023-10-23 06:43 UTC, Jacfomg commented on src/qibocal/update.py
> +        platform.couplers[qubit].flux.offset = sweetspot
Then we should remove the same lines from `sweetspot` as this is a copy of that function.

2023-10-23 06:45 UTC, Jacfomg commented on src/qibocal/protocols/characterization/flux_dependence/utils.py
> +        )
We should define a different curve estimation, crossing the Y axis instead of the X, if we want to have a curve estimation for the avoid crossing I would say then.

2023-10-23 06:47 UTC, Jacfomg commented on src/qibocal/protocols/characterization/flux_dependence/utils.py
> +    if fit is not None and not data.__class__.__name__ == "CouplerSpectroscopyData":
Yeah, still not sure of which parameter would be the right one

2023-10-23 06:54 UTC, Jacfomg commented on src/qibocal/protocols/characterization/couplers/utils.py
> +        )
He told me it's only for 1D data for now

2023-10-23 06:55 UTC, Jacfomg commented on src/qibocal/protocols/characterization/couplers/coupler_resonator_spectroscopy.py
> +    if 1 == 0:
I forgot that `pass` was a thing. Until I figure out what to update I will leave this empty.

2023-10-23 06:56 UTC, Jacfomg commented on src/qibocal/protocols/characterization/couplers/coupler_resonator_spectroscopy.py
> +        )
Above comment, for all the other 2D routines

2023-10-23 06:57 UTC, Jacfomg commented on src/qibocal/protocols/characterization/couplers/coupler_resonator_spectroscopy.py
> +    # TODO: fix loop
To take a list of `params.measured_qubit` instead of one

2023-10-25 06:05 UTC, DavidSarlle commented
@Jacfomg  @andrea-pasquale  The missing point in this routines are the fittings. We should be able to extract information about the couplers points, at least what are the bias values where the interaction between qubits or qubit and coupler are present.

2023-10-31 12:13 UTC, GabrielePalazzo commented on src/qibocal/protocols/characterization/couplers/coupler_qubit_spectroscopy.py
> +        )
This is probably in conflict with #554, I think we should change it to something like this:
```suggestion
        data.register_qubit(
            CouplerSpecType,
            (qubit),
            dict(
                msr=result.magnitude,
                phase=result.phase,
                freq=delta_frequency_range + qd_pulses[qubit].frequency,
                bias=delta_bias_range,
            ),
        )
```

2023-10-31 12:13 UTC, GabrielePalazzo commented on src/qibocal/protocols/characterization/couplers/coupler_resonator_spectroscopy.py
> +        )
```suggestion
        data.register_qubit(
            CouplerSpecType,
            (qubit),
            dict(
                msr=result.magnitude,
                phase=result.phase,
                freq=delta_frequency_range + ro_pulses[qubit].frequency,
                bias=delta_bias_range,
            ),
        )
```

2023-10-31 12:13 UTC, GabrielePalazzo commented on src/qibocal/protocols/characterization/couplers/utils.py
> +        )
@Edoardo-Pedicillo @andrea-pasquale Should we delete this then?

2023-10-31 13:13 UTC, andrea-pasquale commented on src/qibocal/protocols/characterization/couplers/coupler_qubit_spectroscopy.py
> +        )
I'm not sure weather this will work since I believe that @Edoardo-Pedicillo 's implementation was mainly targeting 1D plots, right @Edoardo-Pedicillo ?

2023-11-01 06:30 UTC, Jacfomg commented on src/qibocal/protocols/characterization/couplers/coupler_qubit_spectroscopy.py
> +        )
As far as I know, this is missing the `.ravel()` needed for 2D plots.

2023-11-01 06:31 UTC, Jacfomg commented on src/qibocal/protocols/characterization/couplers/coupler_resonator_spectroscopy.py
> +        )
See last one

2023-11-01 06:36 UTC, Jacfomg commented on src/qibocal/update.py
> +        platform.couplers[qubit].flux.offset = sweetspot
I will remove the update for couplers

2023-11-01 06:47 UTC, Jacfomg commented on src/qibocal/protocols/characterization/flux_dependence/utils.py
> +    if fit is not None and not data.__class__.__name__ == "CouplerSpectroscopyData":
Let's take of the fitting on another routine, I think we should also coupler amplitude next to the sweetspot or another pulse.

2023-11-01 07:09 UTC, andrea-pasquale reviewed
Another small comments

2023-11-01 07:09 UTC, andrea-pasquale commented on src/qibocal/protocols/characterization/couplers/coupler_qubit_spectroscopy.py
> +        # TODO: Qubit pair patch
Are you going to implement this in this PR?

2023-11-01 07:09 UTC, andrea-pasquale commented on src/qibocal/protocols/characterization/couplers/utils.py
> +    """Qubit to readout from the pair"""
What is the criteria for choosing which qubit to readout?

2023-11-01 07:09 UTC, andrea-pasquale reviewed
Another small comments

2023-11-01 09:05 UTC, Jacfomg commented on src/qibocal/protocols/characterization/couplers/coupler_qubit_spectroscopy.py
> +        # TODO: Qubit pair patch
I will prefer to add it on a later date as improvements

2023-11-01 09:06 UTC, Jacfomg commented on src/qibocal/protocols/characterization/couplers/utils.py
> +    """Qubit to readout from the pair"""
I haven't played a lot with those, ideally you will measure both but to avoid any crosstalk I got only one and the one that was not the center qubit to ensure I was getting the coupler I wanted and not something coming from another coupler.

2023-11-01 09:58 UTC, Edoardo-Pedicillo commented on src/qibocal/protocols/characterization/couplers/coupler_qubit_spectroscopy.py
> +        )
> @Edoardo-Pedicillo 's implementation was mainly targeting 1D plots, right @Edoardo-Pedicillo ?

Yes

2023-11-01 10:01 UTC, Edoardo-Pedicillo commented
> @Edoardo-Pedicillo @andrea-pasquale Should we delete this then?
No, the default `register_qubit` does not work with routines with 2D plots

2023-11-01 12:30 UTC, GabrielePalazzo reviewed
From my side I think it's almost ready to be merged.

2023-11-01 12:30 UTC, GabrielePalazzo commented on src/qibocal/protocols/characterization/couplers/utils.py
> +    measured_qubit: list[QubitId]
If we really want to pass a `list` of `QubitID`, I think it should be better to use a plural name, i.e.: `measured_qubits`.

2023-11-01 12:42 UTC, Jacfomg commented on src/qibocal/protocols/characterization/couplers/utils.py
> +    measured_qubit: list[QubitId]
Sure I can change it, for now it would be a bit ironic as qibocal supports them but the drivers will crash with several

2023-11-02 12:42 UTC, GabrielePalazzo approved these changes
Seems ok to me.

2023-11-02 15:14 UTC, andrea-pasquale reviewed
Another bunch of comments mainly improving documentation and plotting

2023-11-02 15:14 UTC, andrea-pasquale commented on src/qibocal/protocols/characterization/couplers/coupler_qubit_spectroscopy.py
> +    """Drive pulse duration to excite the qubit before the measurament"""
```suggestion
    """Drive pulse duration to excite the qubit before the measurement"""
```

2023-11-02 15:14 UTC, andrea-pasquale commented on src/qibocal/protocols/characterization/couplers/coupler_qubit_spectroscopy.py
> +    """
This should be a TODO, right?
For Zurich I believe that it is better to report the issue in qibolab.

2023-11-02 15:14 UTC, andrea-pasquale commented on src/qibocal/protocols/characterization/couplers/coupler_resonator_spectroscopy.py
> +    """Readout delay before the measurament is done to let the flux coupler pulse act"""
```suggestion
    """Readout delay before the measurement is done to let the flux coupler pulse act"""
```

2023-11-02 15:14 UTC, andrea-pasquale commented on src/qibocal/protocols/characterization/couplers/coupler_resonator_spectroscopy.py
> +    """
See above

2023-11-02 15:14 UTC, andrea-pasquale commented on src/qibocal/protocols/characterization/couplers/coupler_resonator_spectroscopy.py
> +        # TODO: Does it need time or can it start at 0 ???
Since you added a delay can we remove the TODO?

2023-11-02 15:14 UTC, andrea-pasquale commented on src/qibocal/protocols/characterization/couplers/coupler_resonator_spectroscopy.py
> +    """This sweeper is implemented in the flux pulse amplitude and we need it to be that way. """
Convert to comment instead of docstring

2023-11-02 15:14 UTC, andrea-pasquale commented on src/qibocal/protocols/characterization/flux_dependence/utils.py
> +            "Phase [rad]_q" + str(qubit),
```suggestion
            "MSR [V] Qubit" + str(qubit),
            "Phase [rad] Qubit" + str(qubit),
```

2023-11-02 15:14 UTC, andrea-pasquale commented on src/qibocal/update.py
> +        platform.couplers[qubit].flux.offset = sweetspot
We agreed to remove this, right?

2023-11-02 15:14 UTC, andrea-pasquale commented on src/qibocal/protocols/characterization/couplers/coupler_qubit_spectroscopy.py
> +    """This sweeper is implemented in the flux pulse amplitude and we need it to be that way. """
Convert to comment

2023-11-02 16:53 UTC, andrea-pasquale approved these changes
Thanks @Jacfomg

2023-11-02 16:53 UTC, merged