Added empty page for resonator_spectroscopy
qiboteam/qibocal pull request #575
Opened 2023-10-24 07:33 UTC by GabrielePalazzo

Adding a table of contents for some protocols and pages with all details for each one of them.

Checklist:
- [ ] Reviewers confirm new code works as expected.
- [ ] Tests are passing.
- [ ] Coverage does not decrease.
- [ ] Documentation is updated.
- [ ] Compatibility with Qibo modules (Please edit this section if the current pull request is not compatible with the following branches).
    - [ ] Qibo: `master`
    - [ ] Qibolab: `main`
    - [ ] Qibolab_platforms_qrc: `main`

2023-10-27 06:13 UTC, andrea-pasquale commented on doc/source/protocols/index.rst
> +===============
```suggestion
Protocols
========
```

2023-10-31 12:38 UTC, andrea-pasquale requested changes
Thanks @GabrielePalazzo.
This is for sure a good step in the right direction.
I believe that one import thing that we should is to add images, in this way also for people trying to characterize it will more clear what we are doing.
As stated in the comment I believe we should add some references whenever we can.
You can find some comments below.

2023-10-31 12:38 UTC, andrea-pasquale commented on doc/source/protocols/resonator_spectroscopy.rst
> +* very high amplitudes could damage the components3
Some of these bullet points are not rendered correctly in the documentation

2023-10-31 12:38 UTC, andrea-pasquale commented on doc/source/protocols/resonator_spectroscopy.rst
> +after waiting for the TOF, we acquire a waveform that we average, obtaining a single
I would put directly "time of flight" here

2023-10-31 12:38 UTC, andrea-pasquale commented on doc/source/protocols/resonator_spectroscopy.rst
> +
I would not say that the duration matters a lot for this experiment.

2023-10-31 12:38 UTC, andrea-pasquale commented on doc/source/protocols/resonator_spectroscopy.rst
> +the pulse at 2 µs.
Here I would avoid to put specific numbers. I would just say that the readout duration is usually chosen to be of the order of magnitude of us or lower.

2023-10-31 12:38 UTC, andrea-pasquale commented on doc/source/protocols/resonator_spectroscopy.rst
> +* very high amplitudes could damage the components3
Moreover, this is all true, but I think that we can explain more properly by looking directly at the Hamiltonian why we see a different behavior at high and low frequency.

Here are a few references:
https://qudev.phys.ethz.ch/static/content/courses/QSIT08/pdfs/Wallraff04.pdf
https://arxiv.org/pdf/cond-mat/0402216.pdf

I think that if we include a few technicalities it should not hurt :)

2023-10-31 12:38 UTC, andrea-pasquale commented on doc/source/protocols/resonator_spectroscopy.rst
> +relaxation time.
Also some electronics might not support a relaxation time equals to 0

2023-11-06 07:38 UTC, GabrielePalazzo commented on doc/source/protocols/resonator_spectroscopy.rst
> +* very high amplitudes could damage the components3
> Some of these bullet points are not rendered correctly in the documentation

Fixed. I'll give a look at the references.

2023-11-07 07:17 UTC, GabrielePalazzo commented
I added all references suggested by @andrea-pasquale using latex-style citations.

There are still two plots missing.

2023-11-13 08:21 UTC, andrea-pasquale approved these changes
Thanks @GabrielePalazzo.
Just a couple of comments.

2023-11-13 08:21 UTC, andrea-pasquale commented on doc/source/protocols/resonator_spectroscopy.rst
> +    platform: dummy
Since now there is also the possibility to omit the platform. We can remove it I think.
Or you can just put `<platform_name>`.
Same for the other yaml snippet

2023-11-13 08:21 UTC, andrea-pasquale commented on doc/source/protocols/resonator_spectroscopy.rst
> +IMAGES
```suggestion
```

2023-11-15 05:54 UTC, GabrielePalazzo commented on doc/source/protocols/resonator_spectroscopy.rst
> +    platform: dummy
I'll leave `<platform_name>` for now.

2023-11-15 06:58 UTC, Edoardo-Pedicillo commented on doc/source/protocols/resonator_spectroscopy.rst
> +* very high amplitudes could damage the components3
```suggestion
* very high amplitudes could damage the components.
```

2023-11-15 06:58 UTC, Edoardo-Pedicillo commented on doc/source/protocols/resonator_spectroscopy.rst
> +
missing pictures ?

2023-11-15 13:21 UTC, andrea-pasquale commented
Can we merge this @GabrielePalazzo @Edoardo-Pedicillo?

2023-11-15 13:24 UTC, GabrielePalazzo commented
> Can we merge this @GabrielePalazzo @Edoardo-Pedicillo?

Yes.

2023-11-16 06:53 UTC, Edoardo-Pedicillo approved these changes

2023-11-16 06:53 UTC, merged