Error spectroscopies
qiboteam/qibocal pull request #660
Opened 2023-12-07 09:00 UTC by Edoardo-Pedicillo

This PR implements the error bars in all the spectroscopies.

Checklist:
- [ ] Reviewers confirm new code works as expected.
- [ ] Tests are passing.
- [ ] Coverage does not decrease.
- [ ] Documentation is updated.
- [ ] Compatibility with Qibo modules (Please edit this section if the current pull request is not compatible with the following branches).
    - [ ] Qibo: `master`
    - [ ] Qibolab: `main`
    - [ ] Qibolab_platforms_qrc: `main`

2023-12-27 16:35 UTC, andrea-pasquale reviewed
Thanks @Edoardo-Pedicillo, generally it looks ok.
As already mentioned in the comments we should take a look at:

1. making sure that results contains frequencies in Hz and not GHz
2. rounding correctly the chi squared and the other quantities in the html table
3. Propagate errors for phase and signal (?)

2023-12-27 16:35 UTC, andrea-pasquale commented on src/qibocal/protocols/characterization/utils.py
> +        # fit_parameters[-1] = fit_parameters[-1]*HZ_TO_GHZ
Remove commented lines

2023-12-27 16:35 UTC, andrea-pasquale commented on src/qibocal/protocols/characterization/utils.py
> +                        fit.chi2_reduced[qubit],
We should round the $\chi^2$ to make the table prettier

2023-12-27 16:35 UTC, andrea-pasquale commented on src/qibocal/protocols/characterization/resonator_spectroscopy.py
> +"""ResonatorSpectroscopyAttenuation Routine object."""
```suggestion
"""ResonatorSpectroscopy Routine object."""
```
At this point we can just call it `ResonatorSpectroscopy`.

2023-12-27 16:35 UTC, andrea-pasquale commented on src/qibocal/protocols/characterization/utils.py
> +    return model_parameters[1], model_parameters, perr
The fits needs to return `Hz` for frequencies, I believe that now it is returning `GHz.

2023-12-27 16:35 UTC, andrea-pasquale commented on src/qibocal/protocols/characterization/utils.py
> +                        fit.chi2_reduced[qubit],
I don't remember how we do it in other protocols but I would round the numbers here.

2023-12-27 16:35 UTC, andrea-pasquale commented on src/qibocal/protocols/characterization/qubit_spectroscopy.py
> +    """Errors of the fit parameters."""
We could also make fitted_parameters a tuple

2023-12-27 16:35 UTC, andrea-pasquale commented on src/qibocal/protocols/characterization/qubit_spectroscopy.py
> +                error_phase=np.std(result.phase, ddof=1),
I've noticed that the error on the phase is pretty large (at least compared to the voltage one) using `dummy`. I don't know if this is expected or not...
Instead of taking the standard deviation directly on signal and phase we could take it on `i` and `q` and then propagate the error on phase and signal. Perhaps it makes a difference.

2024-01-04 10:03 UTC, Edoardo-Pedicillo commented on src/qibocal/protocols/characterization/qubit_spectroscopy.py
> +                signal=np.abs(result.average.voltage),
Because `voltage` is a complex number, where the real and imaginary part are _i_ and _q_.

2024-01-10 16:55 UTC, GabrielePalazzo commented on src/qibocal/protocols/characterization/resonator_spectroscopy.py
> +                error_phase=np.std(result.phase, ddof=1),
```suggestion
                error_phase=np.std(result.phase, axis=0, ddof=1),
```
Wouldn't it be better to compute error bars for each data point (averaging across `nshots`)? If so, the same applies to the other routines.

2024-02-22 14:09 UTC, Edoardo-Pedicillo commented on src/qibocal/protocols/characterization/utils.py
> +                        fit.chi2_reduced[qubit],
I have added the evaluation of the $\chi^2$ error, so now the rounding is consistent with the error.

2024-02-22 14:11 UTC, Edoardo-Pedicillo commented on src/qibocal/protocols/characterization/qubit_spectroscopy.py
> +                error_phase=np.std(result.phase, ddof=1),
Statistically speaking, it should be the same.

2024-02-22 14:51 UTC, Edoardo-Pedicillo commented on src/qibocal/protocols/characterization/resonator_spectroscopy.py
> +                error_phase=np.std(result.phase, ddof=1),
You are right, Thanks!

2024-02-22 15:33 UTC, andrea-pasquale requested changes
Thanks @Edoardo-Pedicillo for the updates.
Just a few minor changes.
In particular, even if for the fit we convert everything to `Hz` at least in the report
it is nicer if we show everything in `GHz` to avoid seeing bilions on the x-axis.

2024-02-22 15:33 UTC, andrea-pasquale commented on src/qibocal/protocols/characterization/resonator_spectroscopy.py
> +
```suggestion
```

2024-02-22 15:33 UTC, andrea-pasquale commented on src/qibocal/protocols/characterization/utils.py
> +            x=np.concatenate((frequencies, frequencies[::-1])),
```suggestion
            x=np.concatenate((frequencies, frequencies[::-1]))*HZ_TO_GHZ,
```
In the report we should show `GHz` and not `Hz` to avoid having a factor 10^9 on the x-axis.

2024-02-22 15:33 UTC, andrea-pasquale commented on src/qibocal/protocols/characterization/utils.py
> +            x=np.concatenate((frequencies, frequencies[::-1])),
Same here

2024-02-22 15:33 UTC, andrea-pasquale commented on src/qibocal/protocols/characterization/resonator_spectroscopy.py
> +    frequency: dict[QubitId, float]
Change docstring to `Hz`

2024-02-22 15:33 UTC, andrea-pasquale commented on src/qibocal/protocols/characterization/resonator_spectroscopy.py
> +    """Data acquisition for resonator spectroscopy attenuation."""
```suggestion
    """Data acquisition for resonator spectroscopy."""
```
The attenuation is already described in the parameters. I would call this just `resonator_spectroscopy` at this point.

2024-02-22 15:33 UTC, andrea-pasquale commented on src/qibocal/protocols/characterization/utils.py
> +        xaxis_title="Frequency [Hz]",
```suggestion
        xaxis_title="Frequency [GHz]",
```

2024-02-22 15:33 UTC, andrea-pasquale commented on src/qibocal/protocols/characterization/utils.py
> +        xaxis2_title="Frequency [Hz]",
```suggestion
        xaxis2_title="Frequency [GHz]",
```

2024-02-23 08:37 UTC, Edoardo-Pedicillo commented on src/qibocal/protocols/characterization/qubit_spectroscopy.py
> +    """Errors of the fit parameters."""
in principle yes, but working with two lists it is easier.

2024-02-23 09:05 UTC, andrea-pasquale commented
Yesterday I merged #682, since it was getting stale and had already two approvs. Let me know if you need any help fixing conflicts here. I can also do it myself since I created them.

2024-02-23 10:30 UTC, andrea-pasquale commented on src/qibocal/protocols/characterization/utils.py
> +                            fit.error_fit_pars[qubit][1] * HZ_TO_GHZ,
```suggestion
                            freq[qubit],
                            fit.error_fit_pars[qubit][1],
```
In the table we keep `Hz` instead :)

2024-02-23 10:30 UTC, andrea-pasquale commented on src/qibocal/protocols/characterization/utils.py
> +                                fit.error_fit_pars[qubit][1] * HZ_TO_GHZ,
```suggestion
                                freq[qubit],
                                fit.error_fit_pars[qubit][1],
```
Same here

2024-02-23 10:53 UTC, Edoardo-Pedicillo commented on src/qibocal/protocols/characterization/utils.py
> +                            fit.error_fit_pars[qubit][1] * HZ_TO_GHZ,
....

I don't see the point of this, generally the plots and the table should share the same units.

2024-02-23 10:54 UTC, Edoardo-Pedicillo commented
> I tested on hardware and everything seems to work as expected. Thanks!
As soon as we fix the unit of measure in the report table we are ready to merge.

Tested, seems working

2024-02-23 11:06 UTC, Edoardo-Pedicillo commented
@GabrielePalazzo This PR is ready, please review it asap

2024-02-23 11:25 UTC, andrea-pasquale commented on src/qibocal/protocols/characterization/utils.py
> +                            fit.error_fit_pars[qubit][1] * HZ_TO_GHZ,
In all tables we show frequencies in Hz.
Seeing errors in with 3 or 5 decimals is not ideal.

2024-02-26 09:34 UTC, GabrielePalazzo approved these changes

2024-02-26 18:56 UTC, merged