TWPA calibration using SNR
qiboteam/qibocal pull request #664
Opened 2023-12-08 08:05 UTC by DavidSarlle

This Pr implements 2 routines for characterizing the TWPA frequency and power doing a resonator spectroscopy while modifying the values of frequency / power of the TWPA. 

Checklist:
- [ ] Reviewers confirm new code works as expected.
- [x] Tests are passing.
- [x] Coverage does not decrease.
- [x] Documentation is updated.
- [x] Compatibility with Qibo modules (Please edit this section if the current pull request is not compatible with the following branches).
    - [x] Qibo: `master`
    - [x] Qibolab: `main`
    - [x] Qibolab_platforms_qrc: `main`

2023-12-08 08:23 UTC, andrea-pasquale requested changes
Thanks @DavidSarlle.
The code looks more or less good to me.
The comments are mainly suggestions to have the code updated to the latest version.

Two important points:

- It would be nice to perform a fitting, let me know if you need help with that.
- Could you please add another entry for these new protocols [here](https://github.com/qiboteam/qibocal/blob/main/tests/runcards/protocols.yml)

2023-12-08 08:23 UTC, andrea-pasquale commented on src/qibocal/protocols/characterization/__init__.py
> +    twpa_frequency_SNR = twpa_frequency_SNR
```suggestion
    twpa_frequency_SNR = twpa_frequency_snr
```
I would keep the same notation as for the other protocol

2023-12-08 08:23 UTC, andrea-pasquale commented on src/qibocal/protocols/characterization/readout_optimization/twpa_calibration/frequency_SNR.py
> +    pass
This will work also without the pass

2023-12-08 08:23 UTC, andrea-pasquale commented on src/qibocal/protocols/characterization/readout_optimization/twpa_calibration/frequency_SNR.py
> +        ("msr", np.float64),
```suggestion
        ("signal", np.float64),
```
Following #611 there is no `msr` anymore in qibocal. Could you please use `signal` in this PR?

2023-12-08 08:23 UTC, andrea-pasquale commented on src/qibocal/protocols/characterization/readout_optimization/twpa_calibration/frequency_SNR.py
> +    """Resonator type."""
This attribute is not used anywhere

2023-12-08 08:23 UTC, andrea-pasquale commented on src/qibocal/protocols/characterization/readout_optimization/twpa_calibration/frequency_SNR.py
> +        )
Since you are basically running a resonator spectroscopy varying the twpa you can just call directly the resonator spectroscopy protocol here. Like we did in the twpa optimization protocols by calling directly the `classification` protocol

2023-12-08 08:23 UTC, andrea-pasquale commented on src/qibocal/protocols/characterization/readout_optimization/twpa_calibration/frequency_SNR.py
> +    return ResonatorTWPAFrequencyResults()
Do you think that it is feasible to implement a fit for this protocol.
I believe that it should be that hard. Eventually we can even put a limit on the twpa power and search the higher snr. withing that range

2023-12-08 08:23 UTC, andrea-pasquale commented on src/qibocal/protocols/characterization/readout_optimization/twpa_calibration/frequency_SNR.py
> +            z=qubit_data.msr * V_TO_UV,
Since we use `signal` we don't convert anymore to `V`.

2023-12-08 08:23 UTC, andrea-pasquale commented on src/qibocal/protocols/characterization/readout_optimization/twpa_calibration/frequency_SNR.py
> +            "phase (rad)",
```suggestion
            "phase [rad]",
```

2023-12-08 08:23 UTC, andrea-pasquale commented on src/qibocal/protocols/characterization/readout_optimization/twpa_calibration/frequency_SNR.py
> +    fig.update_xaxes(title_text=f"{qubit}: Frequency (Hz)", row=1, col=1)
```suggestion
    fig.update_xaxes(title_text=f"{qubit}: Frequency [Hz]", row=1, col=1)
```

2023-12-08 08:23 UTC, andrea-pasquale commented on src/qibocal/protocols/characterization/readout_optimization/twpa_calibration/frequency_SNR.py
> +        uirevision="0",  # ``uirevision`` allows zooming while live plotting
```suggestion
```
This is not needed

2023-12-08 08:23 UTC, andrea-pasquale commented on src/qibocal/protocols/characterization/readout_optimization/twpa_calibration/power_SNR.py
> +from dataclasses import dataclass, field
Same comments as the previous file

2023-12-08 08:30 UTC, andrea-pasquale commented on src/qibocal/protocols/characterization/readout_optimization/twpa_calibration/frequency_SNR.py
> +    step_twpa_freq: int
Also here I believe that maybe it should be better to have also `width` and `step` as parameters.

2024-01-09 06:48 UTC, DavidSarlle commented on src/qibocal/protocols/characterization/readout_optimization/twpa_calibration/frequency_SNR.py
> +    pass
Done

2024-01-09 06:49 UTC, DavidSarlle commented on src/qibocal/protocols/characterization/readout_optimization/twpa_calibration/frequency_SNR.py
> +        ("msr", np.float64),
Replaced msr by signa

2024-01-09 06:50 UTC, DavidSarlle commented on src/qibocal/protocols/characterization/readout_optimization/twpa_calibration/frequency_SNR.py
> +    """Resonator type."""
I will keep it because is going to be needed during the fitting.

2024-01-10 08:25 UTC, DavidSarlle commented on src/qibocal/protocols/characterization/readout_optimization/twpa_calibration/frequency_SNR.py
> +        )
Done

2024-01-10 08:26 UTC, DavidSarlle commented on src/qibocal/protocols/characterization/readout_optimization/twpa_calibration/frequency_SNR.py
> +    return ResonatorTWPAFrequencyResults()
Fitting implemented

2024-01-10 08:27 UTC, DavidSarlle commented on src/qibocal/protocols/characterization/readout_optimization/twpa_calibration/frequency_SNR.py
> +            "phase (rad)",
modified

2024-01-10 08:28 UTC, DavidSarlle commented on src/qibocal/protocols/characterization/readout_optimization/twpa_calibration/frequency_SNR.py
> +    fig.update_xaxes(title_text=f"{qubit}: Frequency (Hz)", row=1, col=1)
modified

2024-01-10 08:28 UTC, DavidSarlle commented on src/qibocal/protocols/characterization/readout_optimization/twpa_calibration/frequency_SNR.py
> +        uirevision="0",  # ``uirevision`` allows zooming while live plotting
removed

2024-01-10 08:29 UTC, DavidSarlle commented on src/qibocal/protocols/characterization/readout_optimization/twpa_calibration/power_SNR.py
> +from dataclasses import dataclass, field
All comments adressed

2024-01-10 08:42 UTC, DavidSarlle commented on src/qibocal/protocols/characterization/readout_optimization/twpa_calibration/frequency_SNR.py
> +    step_twpa_freq: int
Modified

2024-01-11 06:07 UTC, andrea-pasquale reviewed
Thanks @DavidSarlle for all the updates.
I have a few more suggestions.
To fix coverage could you the two new protocols in this[ runcard ](https://github.com/qiboteam/qibocal/blob/david/twpa_SNR/tests/runcards/protocols.yml)?

2024-01-11 06:07 UTC, andrea-pasquale commented on src/qibocal/protocols/characterization/readout_optimization/twpa_calibration/power_SNR.py
> +    """Bare frequency [GHz] for each qubit."""
```suggestion
    twpa_power: dict[QubitId, float] = field(default_factory=dict)
    """TWPA frequency [GHz] for each qubit."""
    frequency: Optional[dict[QubitId, float]] = field(default_factory=dict)
    """Readout frequency [GHz] for each qubit."""
    bare_frequency: Optional[dict[QubitId, float]] = field(default_factory=dict)
    """Bare frequency [GHz] for each qubit."""
```

2024-01-11 06:07 UTC, andrea-pasquale commented on src/qibocal/protocols/characterization/readout_optimization/twpa_calibration/power_SNR.py
> +            qubits[z].twpa.local_oscillator.power = _pow
```suggestion
        for qubit in qubits:
            qubits[qubit].twpa.local_oscillator.power = _pow
```

2024-01-11 06:07 UTC, andrea-pasquale commented on src/qibocal/protocols/characterization/readout_optimization/twpa_calibration/power_SNR.py
> +    fig.update_xaxes(title_text=f"{qubit}/: Frequency [Hz]", row=1, col=2)
```suggestion
    fig.update_xaxes(title_text=f"{qubit}: Frequency [Hz]", row=1, col=2)
```

2024-01-11 06:07 UTC, andrea-pasquale commented on src/qibocal/protocols/characterization/resonator_spectroscopy.py
> +resonator_spec = Routine(_acquisition, _fit, _plot, _update)
Can I ask why you renamed `resonator_spectroscopy` in `resonator_spec`?

2024-01-12 06:39 UTC, DavidSarlle commented
> Thanks @DavidSarlle for all the updates. I have a few more suggestions. To fix coverage could you the two new protocols in this[ runcard ](https://github.com/qiboteam/qibocal/blob/david/twpa_SNR/tests/runcards/protocols.yml)?

Done

2024-01-12 06:40 UTC, DavidSarlle commented on src/qibocal/protocols/characterization/readout_optimization/twpa_calibration/frequency_SNR.py
> +    """Bare frequency [GHz] for each qubit."""
Thanks for the info. Modified.

2024-01-12 06:41 UTC, DavidSarlle commented on src/qibocal/protocols/characterization/readout_optimization/twpa_calibration/frequency_SNR.py
> +            qubits[z].twpa.local_oscillator.frequency = _freq
Done.

2024-01-12 07:06 UTC, DavidSarlle commented on src/qibocal/protocols/characterization/readout_optimization/twpa_calibration/frequency_SNR.py
> +                freq=resonator_spectroscopy_data.data[qubit]["freq"],
modified and testes. Seems to work.

2024-01-12 07:16 UTC, DavidSarlle commented on src/qibocal/protocols/characterization/readout_optimization/twpa_calibration/frequency_SNR.py
> +            print("3D")
removed

2024-01-12 07:16 UTC, DavidSarlle commented on src/qibocal/protocols/characterization/readout_optimization/twpa_calibration/frequency_SNR.py
> +            print("2D")
removed

2024-01-12 07:16 UTC, DavidSarlle commented on src/qibocal/protocols/characterization/readout_optimization/twpa_calibration/frequency_SNR.py
> +            print("high")
removed

2024-01-12 07:16 UTC, DavidSarlle commented on src/qibocal/protocols/characterization/readout_optimization/twpa_calibration/frequency_SNR.py
> +            print("low")
removed

2024-01-12 19:53 UTC, DavidSarlle commented on src/qibocal/protocols/characterization/readout_optimization/twpa_calibration/frequency_SNR.py
> +    fig.update_xaxes(title_text=f"{qubit}/: Frequency [Hz]", row=1, col=2)
slash removed

2024-01-12 19:56 UTC, DavidSarlle commented on src/qibocal/protocols/characterization/readout_optimization/twpa_calibration/power_SNR.py
> +    """Bare frequency [GHz] for each qubit."""
Modified

2024-01-12 19:57 UTC, DavidSarlle commented on src/qibocal/protocols/characterization/readout_optimization/twpa_calibration/power_SNR.py
> +            qubits[z].twpa.local_oscillator.power = _pow
modified

2024-01-12 19:57 UTC, DavidSarlle commented on src/qibocal/protocols/characterization/readout_optimization/twpa_calibration/power_SNR.py
> +    fig.update_xaxes(title_text=f"{qubit}/: Frequency [Hz]", row=1, col=2)
slash removed

2024-01-12 20:09 UTC, DavidSarlle commented on src/qibocal/protocols/characterization/resonator_spectroscopy.py
> +resonator_spec = Routine(_acquisition, _fit, _plot, _update)
Sorry, I changed because vscode was not detecting properly the resonator_spectroscopy class when importing it. But after closing and open vscode again, it detected properly. Sorry, I forgot to rename it again.

2024-01-15 08:53 UTC, DavidSarlle commented
@andrea-pasquale the tests are not passing, can you help me with that?

2024-01-15 09:04 UTC, andrea-pasquale commented on src/qibocal/protocols/characterization/readout_optimization/twpa_calibration/frequency_SNR.py
> +    fitting_report = table_html(summary)
I believe the error is here. For the general execution `qq auto` the plotting functions is fine. However, since the library offers also the possibility to just perform the acquistion `qq acquire` and the plot separately `qq report` this will fail. The solution for this is to just check `if fit is not None` before putting anything in the plot function which is related to fitting. I also put it in the documentation https://qibo.science/qibocal/stable/tutorials/advanced.html#how-to-add-a-new-protocol.
Let me know if this fixes the issues.

2024-01-15 10:51 UTC, DavidSarlle commented on src/qibocal/protocols/characterization/readout_optimization/twpa_calibration/frequency_SNR.py
> +    fitting_report = table_html(summary)
@andrea-pasquale it worked. All tests are passing now. The PR is ready from my side to be merged. Thanks for your help.

2024-01-22 12:27 UTC, Edoardo-Pedicillo requested changes

2024-01-22 12:27 UTC, Edoardo-Pedicillo commented on src/qibocal/protocols/characterization/readout_optimization/twpa_calibration/power_SNR.py
> +        ar["twpa_pow"] = np.array([twpa_pow] * size)
Add an attribute

2024-01-22 12:27 UTC, Edoardo-Pedicillo commented on src/qibocal/protocols/characterization/readout_optimization/twpa_calibration/power_SNR.py
> +
See previous comment

2024-01-22 12:27 UTC, Edoardo-Pedicillo commented on src/qibocal/protocols/characterization/readout_optimization/twpa_calibration/power_SNR.py
> +    frequencies = qubit_data.freq * HZ_TO_GHZ
```suggestion
    frequencies = qubit_data.freq 
```

2024-01-22 12:27 UTC, Edoardo-Pedicillo commented on src/qibocal/protocols/characterization/readout_optimization/twpa_calibration/frequency_SNR.py
> +    resonator_frequencies = qubit_data.freq * HZ_TO_GHZ
```suggestion
    resonator_frequencies = qubit_data.freq
```

2024-01-22 12:27 UTC, Edoardo-Pedicillo commented on src/qibocal/protocols/characterization/readout_optimization/twpa_calibration/power_SNR.py
> +            twpa_power[qubit] = data_qubit["twpa_pow"][index_best_pow]
```suggestion
        if data.resonator_type == "3D":
            index_best_pow = np.argmax(data_qubit["signal"])
        else:
            index_best_pow = np.argmin(data_qubit["signal"])
        twpa_power[qubit] = data_qubit["twpa_pow"][index_best_pow]
```

2024-01-22 12:27 UTC, Edoardo-Pedicillo commented on src/qibocal/protocols/characterization/readout_optimization/twpa_calibration/frequency_SNR.py
> +            self.data[qubit] = np.rec.array(ar)
```suggestion
```
The class `Data` has a default `register_qubit` method, and it seems that it is not different from the one you implemented.

https://github.com/qiboteam/qibocal/blob/1adce17d46587c071edeb4c6d28d39ffafb1b5cd/src/qibocal/auto/operation.py#L164-L181

2024-01-22 12:27 UTC, Edoardo-Pedicillo commented on src/qibocal/protocols/characterization/readout_optimization/twpa_calibration/power_SNR.py
> +
```suggestion
```

2024-01-22 16:29 UTC, DavidSarlle commented on src/qibocal/protocols/characterization/readout_optimization/twpa_calibration/frequency_SNR.py
> +        )
all prints removed.

Regarding this. Do you want to use only one attribute (frequency) for the results class? In the plot function I need to distinguish between the high power and low power resonator freq depending on the power level in order to update the fitting report accordingly. 

>

2024-01-22 16:44 UTC, DavidSarlle commented on src/qibocal/protocols/characterization/readout_optimization/twpa_calibration/frequency_SNR.py
> +
Done

2024-01-22 16:47 UTC, DavidSarlle commented on src/qibocal/protocols/characterization/readout_optimization/twpa_calibration/power_SNR.py
> +
Done

2024-01-22 16:48 UTC, DavidSarlle commented on src/qibocal/protocols/characterization/readout_optimization/twpa_calibration/power_SNR.py
> +    frequencies = qubit_data.freq * HZ_TO_GHZ
removed conversion

2024-01-22 16:48 UTC, DavidSarlle commented on src/qibocal/protocols/characterization/readout_optimization/twpa_calibration/frequency_SNR.py
> +    resonator_frequencies = qubit_data.freq * HZ_TO_GHZ
removed conversion

2024-01-22 16:49 UTC, DavidSarlle commented on src/qibocal/protocols/characterization/readout_optimization/twpa_calibration/power_SNR.py
> +            twpa_power[qubit] = data_qubit["twpa_pow"][index_best_pow]
Implemented

2024-01-24 07:17 UTC, DavidSarlle commented on src/qibocal/protocols/characterization/readout_optimization/twpa_calibration/frequency_SNR.py
> +            self.data[qubit] = np.rec.array(ar)
Thanks. Implemented

2024-01-24 07:17 UTC, DavidSarlle commented on src/qibocal/protocols/characterization/readout_optimization/twpa_calibration/power_SNR.py
> +
thanks. Implemented

2024-01-24 07:20 UTC, DavidSarlle commented on src/qibocal/protocols/characterization/readout_optimization/twpa_calibration/frequency_SNR.py
> +        ar["twpa_freq"] = np.array([twpa_freq] * size)
Removed, since we are not using anymore the custom register_qubit

2024-01-24 07:25 UTC, DavidSarlle commented
@Edoardo-Pedicillo all your comments has been addressed. Thanks for the review.

2024-01-24 07:51 UTC, andrea-pasquale approved these changes
Thanks for all the updates @DavidSarlle.
I believe we are ready to merge. 
Just before merging...
Regarding this:
> The name of the object "Routine" created in the in the "resonator_spectroscopy" class and the class itself have the same name. This is not a problem until you import that class from a different one. Python understands that you are importing the object "Routine" instead of the class. So, we can not use the dataclasses needed from the class "resonator_spectroscopy" like "ResonatorSpectroscopyParameters" during the twpa routines. Same with the private methods like "_acquisition" (but this is a minor problem because the Routine object inherits the methods needed)
I tried to replace `resonator_spec` with `resonator_spectroscopy` and everything worked as expected. If you want I can push the change directly here.

2024-01-24 08:31 UTC, DavidSarlle commented
> Thanks for all the updates @DavidSarlle. I believe we are ready to merge. Just before merging... Regarding this:
> 
> > The name of the object "Routine" created in the in the "resonator_spectroscopy" class and the class itself have the same name. This is not a problem until you import that class from a different one. Python understands that you are importing the object "Routine" instead of the class. So, we can not use the dataclasses needed from the class "resonator_spectroscopy" like "ResonatorSpectroscopyParameters" during the twpa routines. Same with the private methods like "_acquisition" (but this is a minor problem because the Routine object inherits the methods needed)
> > I tried to replace `resonator_spec` with `resonator_spectroscopy` and everything worked as expected. If you want I can push the change directly here.

ok. push the change please.
Thanks!

2024-01-24 08:52 UTC, andrea-pasquale commented
> > Thanks for all the updates @DavidSarlle. I believe we are ready to merge. Just before merging... Regarding this:
> > > The name of the object "Routine" created in the in the "resonator_spectroscopy" class and the class itself have the same name. This is not a problem until you import that class from a different one. Python understands that you are importing the object "Routine" instead of the class. So, we can not use the dataclasses needed from the class "resonator_spectroscopy" like "ResonatorSpectroscopyParameters" during the twpa routines. Same with the private methods like "_acquisition" (but this is a minor problem because the Routine object inherits the methods needed)
> > > I tried to replace `resonator_spec` with `resonator_spectroscopy` and everything worked as expected. If you want I can push the change directly here.
> 
> ok. push the change please. Thanks!

Actually it was not as easy as I expected. Strangely only pylint complains but not pytest. I've also tested the code and it works as expected. I manage to fix it but by importing directly the `resonator_spectroscopy` routine object. In this way pylint does not complain.

2024-01-24 09:16 UTC, andrea-pasquale commented on src/qibocal/protocols/characterization/readout_optimization/twpa_calibration/frequency_SNR.py
> +    resonator_frequencies = qubit_data.freq * HZ_TO_GHZ
Here I don't understand why @Edoardo-Pedicillo asked you to remove the conversion. I suggest to perform the conversion mainly because I don't want to see bilions of Hz in the x axis. I already performed this change in https://github.com/qiboteam/qibocal/pull/664/commits/fa862008ec8ed1532dac7f757c2df1cb04127136

2024-02-01 12:20 UTC, Edoardo-Pedicillo approved these changes

2024-02-01 12:20 UTC, merged