Fix TOF routine with new sampling rate approach
qiboteam/qibocal pull request #679
Opened 2023-12-25 08:58 UTC by PiergiorgioButtarini

This PR try to put a patch on issue 

Checklist:
- [ ] Reviewers confirm new code works as expected.
- [ ] Tests are passing.
- [ ] Coverage does not decrease.
- [ ] Documentation is updated.
- [ ] Compatibility with Qibo modules (Please edit this section if the current pull request is not compatible with the following branches).
    - [ ] Qibo: `master`
    - [ ] Qibolab: `main`
    - [ ] Qibolab_platforms_qrc: `main`

2023-12-26 15:12 UTC, stavros11 reviewed
Thanks for spotting this @PiergiorgioButtarini.
Another approach is to expose the sampling rate from qibolab via the platform and do `platform.sampling_rate` here. This will require a PR in qibolab (I can do this), but it may be slightly more user friendly as the user will not need to pass the correct sampling rate via the runcard (which is in some sense is also duplicated, as the instruments already have their sampling rate).
That being said, I am not sure why this routine needs the sampling rate. From a quick look at this PR it seems to me that it is only being used to normalize the units of time, but we could also use arbitrary units and let the user interpret them according to the used instruments.

2023-12-26 15:12 UTC, stavros11 commented on src/qibocal/protocols/characterization/signal_experiments/time_of_flight_readout.py
> +    sampling_rate: Optional[int] = 1e9
```suggestion
    sampling_rate: int = 1e9
```

2023-12-27 05:16 UTC, PiergiorgioButtarini commented
Thanks @stavros11, yes it's only for normalization purpose but I think it is more user friendly to do it rather than making the user interpret the time in arbitrary units.

2023-12-27 11:08 UTC, andrea-pasquale requested changes
Thanks @PiergiorgioButtarini for this fix.
Similarly to @stavros11, I also cannot understand why the sampling rate should be a parameter.  Merely because you can pass any parameter and it will not be set in the instruments, right? If the sampling rate is needed just for normalization but it cannot be modified at runtime we should just find a way to expose it from the platform, for example as @stavros11 was suggesting here.

> Another approach is to expose the sampling rate from qibolab via the platform and do `platform.sampling_rate` here. This will require a PR in qibolab (I can do this), but it may be slightly more user friendly as the user will not need to pass the correct sampling rate via the runcard (which is in some sense is also duplicated, as the instruments already have their sampling rate).

The other solution is to completely remove it and show on the $x$ axis arbitrary units.

I slightly prefer to first solution but I am fine with both.

2024-01-03 11:21 UTC, PiergiorgioButtarini commented
The PR is now taking into account the features introduced in https://github.com/qiboteam/qibolab/pull/732.

2024-01-03 11:24 UTC, andrea-pasquale commented
> The PR is now taking into account the features introduced in [qiboteam/qibolab#732](https://github.com/qiboteam/qibolab/pull/732).

Thanks @PiergiorgioButtarini for the updates. Tests will probably fail now since in the workflows qibocal is using the stable release of qibolab (this is why I added the `require qibolab release` label). As soon we make a new release of qibolab we can merge this PR.

2024-01-03 11:24 UTC, andrea-pasquale approved these changes

2024-01-09 10:30 UTC, Edoardo-Pedicillo approved these changes

2024-01-27 08:55 UTC, merged