Added possibility to sweep over flux pulses instead of bias
qiboteam/qibocal pull request #691
Opened 2024-01-18 08:51 UTC by GabrielePalazzo

Checklist:
- [ ] Reviewers confirm new code works as expected.
- [ ] Tests are passing.
- [ ] Coverage does not decrease.
- [ ] Documentation is updated.
- [ ] Compatibility with Qibo modules (Please edit this section if the current pull request is not compatible with the following branches).
    - [ ] Qibo: `master`
    - [ ] Qibolab: `main`
    - [ ] Qibolab_platforms_qrc: `main`

2024-02-02 07:35 UTC, andrea-pasquale reviewed
Thanks @GabrielePalazzo I still to test it on hardware. 
Generally it looks fine, I have some comments mainly on how to improve the parameters.

2024-02-02 07:35 UTC, andrea-pasquale commented on src/qibocal/protocols/characterization/flux_dependence/resonator_flux_dependence.py
> +        raise ValueError
Here I would clarify better the error raised.
Also, instead of the defining an attribute which is undefined you could turn `flux_pulses` into a property.
The same could be done for `has_bias_params` and `has_flux_params`. In this way we can avoid to populate too much the `__post_init__` and encapsulate everything in documented properties

2024-02-02 07:35 UTC, andrea-pasquale commented on src/qibocal/protocols/characterization/flux_dependence/resonator_flux_dependence.py
> +    bias_step: float = None
Why `None`? Should't this be `Optional`?

2024-02-02 07:35 UTC, andrea-pasquale commented on src/qibocal/protocols/characterization/flux_dependence/qubit_flux_dependence.py
Same comments as for `resonator_flux_dependence`.
If the majority of the attributes are the same we could consider to introduce an abstract class to remove code duplication.

2024-02-15 08:13 UTC, Jacfomg requested changes

2024-02-16 06:18 UTC, Jacfomg approved these changes
Once you go over @andrea-pasquale comments we should be able to merge this.

2024-02-19 13:56 UTC, Jacfomg requested changes
I had a conversation with @GabrielePalazzo and we agreed is better to remove the `OFFSET` sweeper for an `ABSOLUTE` sweeper even if that means having a list of pulse amplitudes in the runcard if possible. What is your opinion on this @andrea-pasquale .

2024-02-21 09:10 UTC, GabrielePalazzo commented
> I had a conversation with @GabrielePalazzo and we agreed is better to remove the `OFFSET` sweeper for an `ABSOLUTE` sweeper even if that means having a list of pulse amplitudes in the runcard if possible. What is your opinion on this @andrea-pasquale .

We could do it the same way we do for other routines (e.g. `t1`), with `start`, `end`, `step` parameters in the runcard.

2024-02-21 09:40 UTC, andrea-pasquale commented
> I had a conversation with @GabrielePalazzo and we agreed is better to remove the `OFFSET` sweeper for an `ABSOLUTE` sweeper even if that means having a list of pulse amplitudes in the runcard if possible. What is your opinion on this @andrea-pasquale .

Indeed I also believe that it is better to move to `ABSOLUTE` values.

2024-02-21 12:41 UTC, Jacfomg commented on src/qibocal/protocols/characterization/flux_dependence/qubit_crosstalk.py
> +            params.flux_amplitude_end,
If we want to use this for several qubits I expect `params.flux_amplitude_start` to be a list of starts, one for each of the qubits. Same logic for the other parameters, could we do that ?

2024-03-08 08:22 UTC, Jacfomg reviewed
Thanks @GabrielePalazzo, just a couple comments

2024-03-08 08:22 UTC, Jacfomg commented on src/qibocal/protocols/characterization/flux_dependence/resonator_flux_dependence.py
> +    """Amplitude start value(s) for flux pulses sweep relative to the qubit sweetspot [a.u.]."""
Should we describe how will it behave when you pass a list or a float with several qubits ?

```suggestion
    flux_amplitude_start: Optional[Union[float, List[float]]] = None
    """Amplitude start value(s) for flux pulses sweep relative to the qubit sweetspot [a.u.]."""
```

2024-03-08 08:22 UTC, Jacfomg commented on src/qibocal/protocols/characterization/flux_dependence/resonator_flux_dependence.py
> +        """All flux params must be either all float or all lists with the same length.
@andrea-pasquale should we check here for stuff like this or just let the experiment crash ?

2024-03-08 08:22 UTC, Jacfomg commented on tests/runcards/protocols.yml
> +  - id: resonator flux dependence flux
Just to make it clearer

```suggestion
  - id: resonator flux dependence flux single value
```

2024-03-08 08:22 UTC, Jacfomg commented on tests/runcards/protocols.yml
> +  - id: resonator flux dependence flux
```suggestion
  - id: resonator flux dependence flux several values
```

2024-03-08 08:22 UTC, Jacfomg commented on src/qibocal/protocols/characterization/flux_dependence/resonator_flux_dependence.py
> +        ]
We are repeating this several times, could we create a function or something to take care of it ?

2024-03-08 08:22 UTC, Jacfomg commented on src/qibocal/protocols/characterization/flux_dependence/qubit_crosstalk.py
> +            )
I would like to test if we get nice results regarding the flux pulse starting at the same time than the sequence rather than delaying the sequence a bit for the the qubit frequency to shift properly. I would assume this would not be relevant for resonator experiments but could be for qubit ones. (Ignore the -100, but I assume that could be a nice value to delay the sequence after the flux pulse start.)

```suggestion
            pulse = platform.create_qubit_flux_pulse(
                qubit, start=-100, duration=sequence.duration
            )
```

2024-03-12 16:36 UTC, DavidSarlle commented
@GabrielePalazzo as we have commeted, I have tried this PR with the current qibolab main in a fresh venv, with all the dependencies of qibolab and qibocal installed and I get the following error when trying to execute the following action runcard:

platform: iqm5q 
targets: [2]
format: csv

actions:

  - id: qubit flux dependence
    priority: 0
    operation: qubit_flux
    parameters:
      freq_width: 300_000_000
      freq_step: 2_000_000
      flux_amplitude_start: -1.0
      flux_amplitude_end: 1.0
      flux_amplitude_step:  0.1
      drive_amplitude: 0.5
      nshots: 1024
      relaxation_time: 2000
      transition: "01"
      
      the erro is the following:
      
      [Qibo 0.2.4|INFO|2024-03-12 20:30:28]: Minimal execution time (sweep): 2.4576000000000002
Connected to: Rohde&Schwarz SGS100A (serial:1416.0505k02/113302, firmware:4.2.76.0-4.30.046.295) in 0.23s
Traceback (most recent call last):
  File "/nfs/users/david.fuentes/iqm5q/bin/qq", line 8, in <module>
    sys.exit(command())
  File "/nfs/users/david.fuentes/iqm5q/lib/python3.10/site-packages/click/core.py", line 1157, in __call__
    return self.main(*args, **kwargs)
  File "/nfs/users/david.fuentes/iqm5q/lib/python3.10/site-packages/click/core.py", line 1078, in main
    rv = self.invoke(ctx)
  File "/nfs/users/david.fuentes/iqm5q/lib/python3.10/site-packages/click/core.py", line 1688, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/nfs/users/david.fuentes/iqm5q/lib/python3.10/site-packages/click/core.py", line 1434, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/nfs/users/david.fuentes/iqm5q/lib/python3.10/site-packages/click/core.py", line 783, in invoke
    return __callback(*args, **kwargs)
  File "/nfs/users/david.fuentes/qibocal/src/qibocal/cli/_base.py", line 71, in auto
    autocalibrate(runcard, folder, force, update)
  File "/nfs/users/david.fuentes/qibocal/src/qibocal/cli/autocalibration.py", line 60, in autocalibrate
    for _ in executor.run(mode=ExecutionMode.autocalibration):
  File "/nfs/users/david.fuentes/qibocal/src/qibocal/auto/execute.py", line 137, in run
    completed = task.run(
  File "/nfs/users/david.fuentes/qibocal/src/qibocal/auto/task.py", line 165, in run
    completed.data, completed.data_time = operation.acquisition(
  File "/nfs/users/david.fuentes/qibocal/src/qibocal/auto/operation.py", line 42, in wrapper
    out = func(*args, **kwds)
  File "/nfs/users/david.fuentes/qibocal/src/qibocal/protocols/characterization/flux_dependence/qubit_flux_dependence.py", line 179, in _acquisition
    results = platform.sweep(sequence, options, bias_sweeper, freq_sweeper)
  File "/nfs/users/david.fuentes/qibolab/src/qibolab/platform.py", line 299, in sweep
    new_result = instrument.sweep(
  File "/nfs/users/david.fuentes/qibolab/src/qibolab/instruments/zhinst.py", line 1197, in sweep
    self.run_exp()
  File "/nfs/users/david.fuentes/qibolab/src/qibolab/instruments/zhinst.py", line 526, in run_exp
    self.exp = self.session.compile(
  File "/nfs/users/david.fuentes/iqm5q/lib/python3.10/site-packages/laboneq/_observability/tracing/_tracer.py", line 75, in wrapper
    return func(*args, **kwargs)
  File "/nfs/users/david.fuentes/iqm5q/lib/python3.10/site-packages/laboneq/dsl/session.py", line 337, in compile
    self._compiled_experiment = LabOneQFacade.compile(
  File "/nfs/users/david.fuentes/iqm5q/lib/python3.10/site-packages/laboneq/dsl/laboneq_facade.py", line 71, in compile
    payload = payload_builder.build_payload(
  File "/nfs/users/david.fuentes/iqm5q/lib/python3.10/site-packages/laboneq/implementation/payload_builder/payload_builder.py", line 46, in build_payload
    job = self.create_compilation_job(
  File "/nfs/users/david.fuentes/iqm5q/lib/python3.10/site-packages/laboneq/implementation/payload_builder/payload_builder.py", line 84, in create_compilation_job
    experiment_info = self._extract_experiment_info(
  File "/nfs/users/david.fuentes/iqm5q/lib/python3.10/site-packages/laboneq/implementation/payload_builder/payload_builder.py", line 75, in _extract_experiment_info
    return builder.load_experiment()
  File "/nfs/users/david.fuentes/iqm5q/lib/python3.10/site-packages/laboneq/implementation/payload_builder/experiment_info_builder/experiment_info_builder.py", line 125, in load_experiment
    self._load_section_operations(section, section_info, acquisition_type)
  File "/nfs/users/david.fuentes/iqm5q/lib/python3.10/site-packages/laboneq/implementation/payload_builder/experiment_info_builder/experiment_info_builder.py", line 765, in _load_section_operations
    self._load_ssp(
  File "/nfs/users/david.fuentes/iqm5q/lib/python3.10/site-packages/laboneq/implementation/payload_builder/experiment_info_builder/experiment_info_builder.py", line 652, in _load_ssp
    amplitude = self.opt_param(getattr(operation, "amplitude", None))
  File "/nfs/users/david.fuentes/iqm5q/lib/python3.10/site-packages/laboneq/implementation/payload_builder/experiment_info_builder/experiment_info_builder.py", line 503, in opt_param
    return self._add_parameter(value, nt_only)
  File "/nfs/users/david.fuentes/iqm5q/lib/python3.10/site-packages/laboneq/implementation/payload_builder/experiment_info_builder/experiment_info_builder.py", line 481, in _add_parameter
    raise LabOneQException(
laboneq.core.exceptions.laboneq_exception.LabOneQException: Found multiple, inconsistent values for parameter amplitude with same UID.

2024-03-13 20:57 UTC, andrea-pasquale reviewed
Thanks @GabrielePalazzo, code looks ok from my side. I still need to run on hardware.
I have a few suggestions.

2024-03-13 20:57 UTC, andrea-pasquale commented on src/qibocal/protocols/characterization/flux_dependence/qubit_flux_dependence.py
> +            qf_pulses[qubit] = pulse
Given that this is repeated between this and `qubit_crosstalk`, can you introduce a separate function to reduce code duplication?

2024-03-13 20:57 UTC, andrea-pasquale commented on src/qibocal/protocols/characterization/flux_dependence/resonator_flux_dependence.py
> +        """All flux params must be either all float or all lists with the same length.
Checking doesn't hurt, I would personally keep it.

2024-03-14 07:25 UTC, GabrielePalazzo commented on src/qibocal/protocols/characterization/flux_dependence/resonator_crosstalk.py
> +            params, platform, qubits, drive_readout_duration
Should it be like this for the crosstalk routines?
```suggestion
        sweepers = create_flux_pulse_sweepers(
            params, platform, [platform.qubits[flux_qubit] for flux_qubit in flux_qubits], drive_readout_duration
```

2024-03-14 13:27 UTC, andrea-pasquale commented
Thanks @GabrielePalazzo for the updates.
I believe tests are not passing locally. If you want feel free to make the `pyproject.toml` point to qibolab main to see direclty here on GitHub if tests are passing. We can revert it later on once we release qibolab.

2024-03-15 14:20 UTC, andrea-pasquale commented on tests/test_protocols.py
> +        pass
```suggestion
    with pytest.raises(ValueError):
        ResonatorFluxParameters(
            freq_width,
            freq_step,
            bias_width,
            bias_step,
            flux_start,
            flux_end,
            flux_step,
        )
```
Just avoid the `try-except-pass` block :)

2024-03-18 08:04 UTC, Jacfomg approved these changes
It looks good to me, I would like to test it with https://github.com/qiboteam/qibolab/pull/797 and merge it with it. Could please the conficts too ?

2024-03-20 08:20 UTC, hay-k commented on src/qibocal/protocols/characterization/flux_dependence/resonator_flux_dependence.py
> +        qf_pulses[qubit] = pulse
are these pulses ever added to the sequence?

2024-03-20 08:47 UTC, GabrielePalazzo commented on src/qibocal/protocols/characterization/flux_dependence/resonator_flux_dependence.py
> +        qf_pulses[qubit] = pulse
No, they are only added to the sweeper.

2024-03-20 08:51 UTC, hay-k commented on src/qibocal/protocols/characterization/flux_dependence/resonator_flux_dependence.py
> +        qf_pulses[qubit] = pulse
shouldn't they be in the sequence?

2024-03-20 08:52 UTC, GabrielePalazzo commented
> It looks good to me, I would like to test it with [qiboteam/qibolab#797](https://github.com/qiboteam/qibolab/pull/797) and merge it with it. Could please the conficts too ?

Sure. I just need to revert https://github.com/qiboteam/qibocal/pull/691/commits/fdbb941b653f5c50528cd010c073a93f0fac5a21

2024-03-22 08:18 UTC, Jacfomg requested changes
I just realized that we should try to change the plotting axis to display voltage[V] or pulse amplitude[a.u.] depending on what we would be sweeping. Also, we may need to handle the update differently for each case. Is that possible @andrea-pasquale ?

2024-03-22 11:44 UTC, andrea-pasquale commented
> I just realized that we should try to change the plotting axis to display voltage[V] or pulse amplitude[a.u.] depending on what we would be sweeping. Also, we may need to handle the update differently for each case. Is that possible @andrea-pasquale ?

We could give it a try. If it becomes too complicated we should have two different protocols while reducing code duplication.

2024-03-27 06:14 UTC, Jacfomg commented on src/qibocal/protocols/characterization/flux_dependence/resonator_flux_dependence.py
> +            return
We could also have cases were we have some integers. Let's say `flux_pulse_start = 0`

2024-03-27 06:32 UTC, Jacfomg commented
At least for flux_pulses routines we may want to do something different with the frequency rather than width around the qubit frequency as you are looking to move the qubit to a different frequency to the left so, all points in the right wouldn't be needed.

![image](https://github.com/qiboteam/qibocal/assets/19141117/de95deb6-d7cf-45cb-a9a6-587e51ad3a93)

2024-03-27 07:08 UTC, Jacfomg commented on src/qibocal/protocols/characterization/flux_dependence/resonator_flux_dependence.py
> +            return
Thanks @GabrielePalazzo, will this work for lists of floats and ints that could be mixed as well ?

2024-03-27 09:41 UTC, andrea-pasquale commented
> At least for flux_pulses routines we may want to do something different with the frequency rather than width around the qubit frequency as you are looking to move the qubit to a different frequency to the left so, all points in the right wouldn't be needed.
> 
> ![image](https://private-user-images.githubusercontent.com/19141117/317154827-de95deb6-d7cf-45cb-a9a6-587e51ad3a93.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTE1MzI2MDksIm5iZiI6MTcxMTUzMjMwOSwicGF0aCI6Ii8xOTE0MTExNy8zMTcxNTQ4MjctZGU5NWRlYjYtZDdjZi00NWNiLWE5YTYtNTg3ZTUxYWQzYTkzLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAzMjclMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMzI3VDA5MzgyOVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWY4NTU2ZmM2ZjU1ODhlNDFmYzFjNmQyMDBlNWExNDIzZWQxN2Y4MmM4ZjkzZDUyNDA5OThkMDcwMTM3YTIyNjcmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.W7r5wesUs4_eldgxZVq29z2ND2pIJXLVKPqH8SH_ie8)
> 
> Asking the user to provide start and stop for frequency ? Something like:
> 
> frequency_start = -200 MHz (And you would substract this from the qubit frequency; qubit frequency = qubit frequency - 200MHz )

Fine, eventually we could start by merging this and add this feature on top this change. As you prefer @GabrielePalazzo

2024-03-27 09:42 UTC, andrea-pasquale approved these changes

2024-03-27 09:42 UTC, andrea-pasquale commented on poetry.lock
is this lock change needed or does this PR work with main?

2024-03-27 11:57 UTC, Jacfomg commented on poetry.lock
I was using qibolab main to test it this morning.

2024-03-27 12:00 UTC, Jacfomg approved these changes
@GabrielePalazzo you resolved my comment, so I assume it works with list of integers as well.

2024-03-28 08:53 UTC, andrea-pasquale commented on src/qibocal/protocols/characterization/flux_dependence/qubit_flux_dependence.py
> +                qubits=targets,
```suggestion
                qubits=[platform.qubits[qubit] for qubit in targets],
```
Bias sweep is not working. Changing this line fixed the problem for me.

2024-03-28 10:24 UTC, andrea-pasquale requested changes

2024-03-28 10:26 UTC, andrea-pasquale commented
I think that it might be useful to show on the y axis always bias, even if the user provides amplitude as inputs, given that we are mainly interested in where the qubit bias is going to be. This will also help the fit. Thoughts @DavidSarlle @aorgazf?

2024-03-28 13:14 UTC, Jacfomg reviewed
is this correct ?

2024-03-28 13:14 UTC, Jacfomg commented on src/qibocal/protocols/characterization/flux_dependence/qubit_flux_dependence.py
> +        flux_pulses=params.flux_pulses,
I couldn't serialize this as it was before on the #775 as it said it was a method. This solved it for me.

```suggestion
        flux_pulses=params.has_flux_params,
```

2024-03-29 07:10 UTC, Jacfomg commented on src/qibocal/protocols/characterization/flux_dependence/resonator_flux_dependence.py
> +        """True if both biasflux_amplitude_width_width and flux_amplitude_step are set."""
Is this docstring right ?

2024-03-29 07:17 UTC, GabrielePalazzo commented on src/qibocal/protocols/characterization/flux_dependence/resonator_flux_dependence.py
> +        """True if both biasflux_amplitude_width_width and flux_amplitude_step are set."""
Definitely not.

2024-03-29 11:51 UTC, andrea-pasquale approved these changes
Thanks @GabrielePalazzo, did you test with @Jacfomg that everything on hardware works as expected, right? If so fell free to merge.

2024-03-29 12:39 UTC, andrea-pasquale commented
> I have also tested on hardware and seems to work as expected

Both bias and flux sweep, right?

2024-03-29 12:44 UTC, DavidSarlle commented
Yes, in iqm5q using Hayk's hotfix

2024-03-29 12:46 UTC, andrea-pasquale commented
> Yes, in iqm5q using Hayk's hotfix

Great, let's go ahead with the merge then. Thanks for confirming.

2024-03-29 12:46 UTC, merged