Add chevron with probabilities
qiboteam/qibocal pull request #769
Opened 2024-03-25 08:25 UTC by andrea-pasquale

Closes #767 
This PR adds the possibility to run chevron by measuring probabilities instead of "signal" (which is usually what I see in papers). 
For now I am measuring the probability of $\ket{1}$ for both qubits. 

Checklist:
- [ ] Reviewers confirm new code works as expected.
- [ ] Tests are passing.
- [ ] Coverage does not decrease.
- [ ] Documentation is updated.
- [ ] Compatibility with Qibo modules (Please edit this section if the current pull request is not compatible with the following branches).
    - [ ] Qibo: `master`
    - [ ] Qibolab: `main`
    - [ ] Qibolab_platforms_qrc: `main`

2024-03-25 09:09 UTC, andrea-pasquale commented
I just ran on hardware, the results seems to be consistent between [signal](http://login.qrccluster.com:9000/BFekyaQnRoisw1QjIyfhHQ==/) and [probability](http://login.qrccluster.com:9000/5Z12o31ZRWmJ8X18YGCifQ==/).
I would like to update the plot of the probability version to show that I am measuring the probability of measuring  $\ket{1}$.

2024-03-28 12:06 UTC, Edoardo-Pedicillo approved these changes
LGTM

2024-03-29 09:09 UTC, GabrielePalazzo requested changes

2024-03-29 09:09 UTC, GabrielePalazzo commented on src/qibocal/protocols/characterization/two_qubit_interaction/chevron/chevron_signal.py
> +        params: Experiment parameters.
```suggestion
        params: Experiment parameters.
        platform: Platform to use.
```

2024-03-29 10:29 UTC, igres26 approved these changes
Looks good. After the small changes that are requested it can be merged.

2024-03-29 11:18 UTC, GabrielePalazzo approved these changes

2024-04-04 10:35 UTC, merged