Specify different directory for `qq fit`
qiboteam/qibocal pull request #774
Opened 2024-03-28 06:33 UTC by andrea-pasquale

Closes #773 

- [ ] Add tests

Checklist:
- [ ] Reviewers confirm new code works as expected.
- [ ] Tests are passing.
- [ ] Coverage does not decrease.
- [ ] Documentation is updated.
- [ ] Compatibility with Qibo modules (Please edit this section if the current pull request is not compatible with the following branches).
    - [ ] Qibo: `master`
    - [ ] Qibolab: `main`
    - [ ] Qibolab_platforms_qrc: `main`

2024-03-28 12:01 UTC, Edoardo-Pedicillo approved these changes

2024-03-29 06:39 UTC, GabrielePalazzo requested changes

2024-03-29 06:39 UTC, GabrielePalazzo commented on src/qibocal/cli/fit.py
> +    - path: input folder.
```suggestion
    - input_path: input folder.
```

2024-03-29 06:39 UTC, GabrielePalazzo commented on tests/test_cli.py
> +DUMMY_ACTION = pathlib.Path(__file__).parent / "runcards/dummy_action.yml"
```suggestion
DUMMY_ACTION = pathlib.Path(__file__).parent / "runcards" / "dummy_action.yml"
```

2024-03-29 06:43 UTC, GabrielePalazzo commented on doc/source/getting-started/interface.rst
> +It is also possible to generate a separated folder with the output folder generated by qibocal with
Did you mean "separate folder"? Separated is an adjective too, but it has a slightly different meaning.

2024-03-29 06:48 UTC, GabrielePalazzo commented on src/qibocal/cli/fit.py
> +            path = shutil.copytree(input_path, output_path)
This should do the same things with less lines of code:
```suggestion
        if output_path.exists():
            if force is False:
                raise_error(RuntimeError, f"Directory {output_path} already exists.")
            # overwrite output_path
            log.warning(f"Deleting previous directory {output_path}.")
            shutil.rmtree(pathlib.Path.cwd() / output_path)
        path = shutil.copytree(input_path, output_path)
```

2024-03-29 07:01 UTC, GabrielePalazzo approved these changes
Apart from https://github.com/qiboteam/qibocal/pull/774/files#r1544149133, it looks good to me.

2024-03-29 07:04 UTC, andrea-pasquale commented
> Apart from https://github.com/qiboteam/qibocal/pull/774/files#r1544149133, it looks good to me.

Thanks @GabrielePalazzo. I saw the comment after asking you for the second review :)

2024-03-29 07:05 UTC, GabrielePalazzo commented
> > Apart from https://github.com/qiboteam/qibocal/pull/774/files#r1544149133, it looks good to me.
> 
> Thanks @GabrielePalazzo. I saw the comment after asking you for the second review :)

I haven't checked if `pathlib` is imported.

2024-03-29 09:01 UTC, merged