Flux pulses coupler experiments
qiboteam/qibocal pull request #775
Opened 2024-03-28 11:08 UTC by Jacfomg

Propagates #691 coupler spec routines plus some fixes/improvements

Checklist:
- [ ] Reviewers confirm new code works as expected.
- [ ] Tests are passing.
- [ ] Coverage does not decrease.
- [x] Documentation is updated.
- [x] Compatibility with Qibo modules (Please edit this section if the current pull request is not compatible with the following branches).
    - [x] Qibo: `master`
    - [x] Qibolab: `main`
    - [ ] Qibolab_platforms_qrc: `main`

2024-03-29 07:01 UTC, GabrielePalazzo commented on tests/test_protocols.py
> +    for runcard in [PATH_TO_RUNCARD_COUPLERS, PATH_TO_RUNCARD]:
Should we move the for loop to a pytest parametrize fixture? If only one of the two runcards fails the test we know which one it is.

2024-03-29 07:31 UTC, Jacfomg commented on tests/test_protocols.py
> +    for runcard in [PATH_TO_RUNCARD_COUPLERS, PATH_TO_RUNCARD]:
@andrea-pasquale any comment. I think we can tell from the name of the routine+platform now.

2024-03-29 09:21 UTC, GabrielePalazzo requested changes

2024-03-29 09:21 UTC, GabrielePalazzo commented on src/qibocal/protocols/characterization/couplers/coupler_qubit_spectroscopy.py
> +        flux_pulses=params.has_flux_params,
```suggestion
        flux_pulses=params.flux_pulses,
```

2024-03-29 09:21 UTC, GabrielePalazzo commented on src/qibocal/protocols/characterization/couplers/coupler_resonator_spectroscopy.py
> +    if params.has_flux_params:
```suggestion
    if params.flux_pulses:
```

2024-03-29 09:21 UTC, GabrielePalazzo commented on src/qibocal/protocols/characterization/couplers/coupler_qubit_spectroscopy.py
> +    if params.has_flux_params:
```suggestion
    if params.flux_pulses:
```

2024-03-29 09:21 UTC, GabrielePalazzo commented on src/qibocal/protocols/characterization/couplers/coupler_resonator_spectroscopy.py
> +        flux_pulses=params.has_flux_params,
```suggestion
        flux_pulses=params.flux_pulses,
```

2024-03-29 09:21 UTC, GabrielePalazzo commented on src/qibocal/protocols/characterization/couplers/coupler_resonator_spectroscopy.py
> +            # return [fig], fitting_report
```suggestion
```

2024-03-29 09:33 UTC, GabrielePalazzo approved these changes

2024-03-29 12:48 UTC, andrea-pasquale commented
Could you please merge `main` here @Jacfomg?

2024-04-03 10:00 UTC, Jacfomg commented on src/qibocal/protocols/characterization/flux_dependence/resonator_flux_dependence.py
> +            qubit = qubit.name
It was already there, but due to they asking for bias sweepers it needed to follow the same approach as in #691 to reproduce the initial desired behavior.

2024-04-04 06:28 UTC, andrea-pasquale approved these changes

2024-04-04 06:33 UTC, merged