Resonator depletion measuremant
qiboteam/qibocal pull request #822
Opened 2024-05-03 13:56 UTC by Jacfomg

Following https://arxiv.org/abs/1604.00916. Just to measure the resonator depletion time.

Checklist:
- [ ] Reviewers confirm new code works as expected.
- [ ] Tests are passing.
- [ ] Coverage does not decrease.
- [ ] Documentation is updated.
- [ ] Compatibility with Qibo modules (Please edit this section if the current pull request is not compatible with the following branches).
    - [ ] Qibo: `master`
    - [ ] Qibolab: `main`
    - [ ] Qibolab_platforms_qrc: `main`

2024-05-04 12:03 UTC, stavros11 commented on src/qibocal/protocols/characterization/allxy/allxy_resonator_depletion_tuning.py
> +            print(sequence)
```suggestion
```

2024-05-04 12:03 UTC, stavros11 commented on src/qibocal/protocols/characterization/allxy/allxy.py
> +    sequenceDuration = sequence.duration + sequence_delay
I know this is a leftover from the past, but we shoud probably convert to the proper naming convention at some point
```suggestion
    sequence_duration = sequence.duration + sequence_delay
```

2024-05-04 12:03 UTC, stavros11 commented on src/qibocal/protocols/characterization/allxy/allxy_resonator_depletion_tuning.py
> +                    readout_delay=996,  # becuase we already add a +4
Nothing to be done now, but these kind of manipulations will hopefully be easier using `Delay` in qibolab 0.2.

Also
```suggestion
                    sequence_delay=delay_param,
                    readout_delay=996,  # because we already add a +4
```

2024-05-06 05:49 UTC, Jacfomg commented on tests/runcards/protocols.yml
> +      delay_step: 1000.0
Yes, so we either get an error coming from QM if we use floats or from json if we use ints.

2024-05-07 06:21 UTC, andrea-pasquale requested changes

2024-05-07 06:21 UTC, andrea-pasquale commented on src/qibocal/protocols/characterization/allxy/allxy.py
> +        sequence_duration = sequence_duration + pulse_duration
```suggestion
        sequence_duration += pulse_duration
```

2024-05-07 06:21 UTC, andrea-pasquale commented on src/qibocal/protocols/characterization/allxy/allxy.py
> +        qubit, start=sequence_duration + 4 + readout_delay
I know that the 4 was already there. Is it a remnant of some qblox shenanigans?

2024-05-07 06:21 UTC, andrea-pasquale commented on src/qibocal/protocols/characterization/allxy/allxy_resonator_depletion_tuning.py
> +class AllXYDragParameters(Parameters):
Wrong class name

2024-05-07 06:21 UTC, andrea-pasquale commented on src/qibocal/protocols/characterization/allxy/allxy_resonator_depletion_tuning.py
> +class AllXYDragResults(Results):
Wrong class name

2024-05-07 06:21 UTC, andrea-pasquale commented on src/qibocal/protocols/characterization/allxy/allxy_resonator_depletion_tuning.py
> +class AllXYDragData(Data):
Wrong class name

2024-05-07 06:21 UTC, andrea-pasquale commented on src/qibocal/protocols/characterization/allxy/allxy_resonator_depletion_tuning.py
> +    in order to find the optimal drag pulse coefficient for pi pulses.
This docstring is copy and paste, you can write to refer to the allxy experiment.

2024-05-07 06:21 UTC, andrea-pasquale commented on src/qibocal/protocols/characterization/allxy/allxy_resonator_depletion_tuning.py
> +    delays = np.arange(params.delay_start, params.delay_end, params.delay_step).round(4)
At this point can we define this 4 as a top level variable (?)

2024-05-07 06:21 UTC, andrea-pasquale commented on src/qibocal/protocols/characterization/allxy/allxy_resonator_depletion_tuning.py
> +                    readout_delay=996,  # because we already add a +4
I would avoid hardcoding numbers

2024-05-07 06:21 UTC, andrea-pasquale commented on src/qibocal/protocols/characterization/allxy/allxy_resonator_depletion_tuning.py
> +    in order to find the optimal drag pulse coefficient for pi pulses.
Given that I am not familiar with the experiment an appropriate documentation should be provided, possibly referencing the paper cited in the PR.

2024-05-07 06:23 UTC, andrea-pasquale commented
Shouldn't the protocol also have an `update` function where it writes the `depletion_time` on the platform?

2024-05-08 07:09 UTC, Jacfomg commented on src/qibocal/protocols/characterization/allxy/allxy.py
> +        qubit, start=sequence_duration + 4 + readout_delay
I guess so. Can I extinguish it ?

2024-05-08 07:10 UTC, Jacfomg commented on src/qibocal/protocols/characterization/allxy/allxy_resonator_depletion_tuning.py
> +                    readout_delay=996,  # because we already add a +4
It's what they do in the paper, they wait 1ms bfore reading

2024-05-08 07:11 UTC, Jacfomg commented
> Shouldn't the protocol also have an `update` function where it writes the `depletion_time` on the platform?

How would you fit it ?

2024-05-08 07:34 UTC, Jacfomg commented on src/qibocal/protocols/characterization/allxy/allxy_resonator_depletion_tuning.py
> +    delays = np.arange(params.delay_start, params.delay_end, params.delay_step).round(4)
I will remove it came from the drag

2024-05-08 08:14 UTC, andrea-pasquale commented
> > Shouldn't the protocol also have an `update` function where it writes the `depletion_time` on the platform?
> 
> How would you fit it ?

I am not familiar with the experiment. I was just asking if this protocol is supposed to measure the depletion time.
If not forget it.

2024-05-08 09:03 UTC, Jacfomg commented
> > > Shouldn't the protocol also have an `update` function where it writes the `depletion_time` on the platform?
> > 
> > 
> > How would you fit it ?
> 
> I am not familiar with the experiment. I was just asking if this protocol is supposed to measure the depletion time. If not forget it.

It would involve comparing two allxy plots, the one coming from this routines and the one coming from the regular allxy and getting the smaller delay when they look similar enough I guess.

2024-05-08 09:08 UTC, andrea-pasquale commented
> It would involve comparing two allxy plots, the one coming from this routines and the one coming from the regular allxy and getting the smaller delay when they look similar enough I guess.

Then we should implement a protocol that does exactly this, right? (Outside this PR)

2024-05-08 09:11 UTC, andrea-pasquale commented on src/qibocal/protocols/characterization/allxy/allxy_resonator_depletion_tuning.py
> +                    readout_delay=996,  # because we already add a +4
In any case please remove the hardcoded number

2024-05-08 09:30 UTC, Jacfomg commented
> > It would involve comparing two allxy plots, the one coming from this routines and the one coming from the regular allxy and getting the smaller delay when they look similar enough I guess.
> 
> Then we should implement a protocol that does exactly this, right? (Outside this PR)

Either that or we go for the QM way of getting this for the fit.

2024-05-09 09:13 UTC, sorewachigauyo commented
The use of reset schemes should also reduce the delay between shots (`relaxation_time` runcard parameter), no? It would be good to also have this new time somewhere.

2024-05-09 09:42 UTC, Jacfomg commented
> The use of reset schemes should also reduce the delay between shots (`relaxation_time` runcard parameter), no? It would be good to also have this new time somewhere.

Yes, the active reset schemes will lower the relaxation time, but they will be somewhat limited by this resonator depletion time as you could not adress the qubit properly until the photons are depleted (They are also another schemes to active deplete the resonator to make all this faster). For now, I made this to store it in qibolab https://github.com/qiboteam/qibolab/pull/895.

2024-05-09 10:21 UTC, sorewachigauyo commented
I see. I thought this was a reset scheme, my bad.

@alecandido Should probably take note of this when conditional logic is implemented in Qibolab pulse sequencing, which is probably a necessary feature to add eventually, since QM and Zurich already supports this (and probably can have an initial implementation with `fast_reset` in `ExecutionParameters`).

@Jacfomg Have you tested the depletion time with the active reset, if it improves the fidelity?

2024-05-09 11:07 UTC, alecandido commented
Yes, conditioning pulses on measurement outcomes is currently unsupported.

Interface-wise, it shouldn't be a too complex addition. Though it is not well-fitting the idea of a pulse sequence, and it would make it closer to a program. So, it is simple only as a patch.
I have the feeling that going towards full-fledged support for flow control, it would make us rebuilding QUA (or anything like the other DSLs), since that will resemble more a program with a processor/interpreter (i.e. the sequencer), rather than a pre-compiled sequence.

2024-05-09 11:11 UTC, Jacfomg commented
> @alecandido Should probably take note of this when conditional logic is implemented in Qibolab pulse sequencing, which is probably a necessary feature to add eventually, since QM and Zurich already supports this (and probably can have an initial implementation with `fast_reset` in `ExecutionParameters`).
> 
> @Jacfomg Have you tested the depletion time with the active reset, if it improves the fidelity?

Let's just say that for now it is not supported anymore for the Zurich driver (I made a crappy implementation to try to overcome qibolab limitations a while ago, that we removed now). I tested active reset with Zurich before being aware of this so results were bad, I expect better performance after waiting the resonator relaxation time. Still, we would need to understand first how to optimize the QND of the readout as right now 1/10 states 1 measurered, when I tested this with QM, were then measured again and were 0s, so they didn't keep the state after measurement for a effective active reset scheme.

(Sorry I edited your comment instead of replying)

2024-05-09 11:13 UTC, Jacfomg commented
> @sorewachigauyo Yes, conditioning pulses on measurement outcomes is currently unsupported.
> 
> Interface-wise, it shouldn't be a too complex addition. Though it is not well-fitting the idea of a pulse sequence, and it would make it closer to a program. So, it is simple only as a patch. I have the feeling that going towards full-fledged support for flow control, it would make us rebuilding QUA (or anything like the other DSLs), since that will resemble more a program with a processor/interpreter (i.e. the sequencer), rather than a pre-compiled sequence.

At least Zurich has a way of checking if the measurement result was a 0 or a 1. So, having some pulse parameter to tell some of the pulses to be played in those situations would be enough for now.

2024-05-09 11:19 UTC, alecandido commented
> At least Zurich has a way of checking if the measurement result was a 0 or a 1. So, having some pulse parameter to tell some of the pulses to be played in those situations would be enough for now.

Yes, and that's why I said we could implement it as a patch. We could just label a pulse with the id of another measurement, and resolve the translation in the drivers.

> That would also allow for custom active reset sequences instead of just the pi_pulse I applied to the state 1 on my trials.

Point is that, for sequences, we need to label all the pulses. Feasible, but hits the boundary. If you wanted to nest two different `if`s, then we'd stop there, or we should start implementing boolean operations in the labeling ids, and that would be a mess...
At that point, much better to give up on the idea of the sequence, and switch paradigm for a program.

2024-05-09 11:44 UTC, Jacfomg commented
> > At least Zurich has a way of checking if the measurement result was a 0 or a 1. So, having some pulse parameter to tell some of the pulses to be played in those situations would be enough for now.
> 
> Yes, and that's why I said we could implement it as a patch. We could just label a pulse with the id of another measurement, and resolve the translation in the drivers.
> 
> > That would also allow for custom active reset sequences instead of just the pi_pulse I applied to the state 1 on my trials.
> 
> Point is that, for sequences, we need to label all the pulses. Feasible, but hits the boundary. If you wanted to nest two different `if`s, then we'd stop there, or we should start implementing boolean operations in the labeling ids, and that would be a mess... At that point, much better to give up on the idea of the sequence, and switch paradigm for a program.

Ah yes, but with the patch we could play with some simple active reset schemes that may cut down the relaxation time a lot or just some checks, even if it is just a conditional if you measure a 0 skip the relaxation time and just do resonator deplation and if you measure 1 wait the relaxation time. Just so maybe you could consider this for the qibolab 0.2. Also, the several mesurements seems a bit for more advanced active reset schemes or error correction.

2024-05-09 12:00 UTC, alecandido commented
Yes, definitely, I would do that (you could even add an issue in Qibolab, if not yet there, and add the milestone 0.2).

I hope the patch will be backward compatible, I have to think about that (I'm mainly worried about deserialization, since it will be an additional argument). If it is, we don't even need to do necessarily in 0.2.0 or postpone it forever, to avoid breaking, but rather release 0.2.0 asap, and then implement it in 0.2.1.

2024-05-09 13:19 UTC, Jacfomg commented
> Yes, definitely, I would do that (you could even add an issue in Qibolab, if not yet there, and add the milestone 0.2).
> 
> I hope the patch will be backward compatible, I have to think about that (I'm mainly worried about deserialization, since it will be an additional argument). If it is, we don't even need to do necessarily in 0.2.0 or postpone it forever, to avoid breaking, but rather release 0.2.0 asap, and then implement it in 0.2.1.
> 
> (The program approach is for sure breaking, and it would be 0.3 or further, no way it could land in current 0.2)
You have this already https://github.com/qiboteam/qibolab/issues/592 , so I won't create another active reset issue if this is okay for you

2024-05-10 05:39 UTC, andrea-pasquale approved these changes

2024-05-20 11:59 UTC, merged