Delay on readout characterization
qiboteam/qibocal pull request #826
Opened 2024-05-06 18:43 UTC by Jacfomg

The fidelity and QND do not seem affected when neglecting the resonator delation time as we are not applying qubit pulses during the measurements. However, there is some anomalous shift on the iq plane that goes away if you wait the resonator depletion time.

![imagen](https://github.com/qiboteam/qibocal/assets/19141117/38b63999-9e93-4426-a5b8-f6bfd3301aac)

![imagen](https://github.com/qiboteam/qibocal/assets/19141117/d7fd554b-4e3d-4a88-bd61-a55ddca85568)

Checklist:
- [ ] Reviewers confirm new code works as expected.
- [ ] Tests are passing.
- [ ] Coverage does not decrease.
- [ ] Documentation is updated.
- [ ] Compatibility with Qibo modules (Please edit this section if the current pull request is not compatible with the following branches).
    - [ ] Qibo: `master`
    - [ ] Qibolab: `main`
    - [ ] Qibolab_platforms_qrc: `main`

2024-05-07 06:36 UTC, andrea-pasquale requested changes

2024-05-07 06:36 UTC, andrea-pasquale commented on src/qibocal/protocols/characterization/readout_characterization.py
> +    delay: Optional[float] = None
```suggestion
    delay: float = 0
```

2024-05-07 06:36 UTC, andrea-pasquale commented on src/qibocal/protocols/characterization/readout_characterization.py
> +    delay: Optional[float] = None
```suggestion
    delay: float
```

2024-05-07 06:36 UTC, andrea-pasquale commented on tests/runcards/protocols.yml
> +      delay: 1000
Please introduce another entry here where `delay` is not provided, you see that the code fails without my suggestions...

2024-05-08 12:18 UTC, andrea-pasquale approved these changes

2024-05-09 09:56 UTC, igres26 commented
Could we make both plots square and display them side by side?

2024-05-09 11:12 UTC, Edoardo-Pedicillo approved these changes

2024-05-09 11:45 UTC, Jacfomg commented
> > Could we make both plots square and display them side by side?
> 
> We have three plots now, I can plot the blobs alone on top and the two matrices together below that.

![image](https://github.com/qiboteam/qibocal/assets/19141117/4a329095-4ea6-40e9-b401-53f7b80a6604)

2024-05-09 11:46 UTC, Jacfomg commented
> > Could we make both plots square and display them side by side?
> 
> We have three plots now, I can plot the blobs alone on top and the two matrices together below that.

![image](https://github.com/qiboteam/qibocal/assets/19141117/e29c0762-b8f4-476c-90b9-b4a29dce950f)

2024-05-14 09:15 UTC, merged