Qubit power spectroscopy experiment
qiboteam/qibocal pull request #856
Opened 2024-05-16 14:02 UTC by rodolfocarobene

Hi!
I'm trying to add some new experiment, at the moment I do not have available qubits. Are there qubits at TII that I could use?

Anyway, this PR implements a qubit spectroscopy where also the amplitude of the pulse is changed. We performed the experiment with qibolab some weeks ago, finding the following plot:
![immagine](https://github.com/qiboteam/qibocal/assets/74607088/6653ea0a-4f29-458e-8d6c-53692830fd2c)

For the moment I did not try to add any fitting procedure (nothing comes to my mind).

For now I've tested it with:

```
platform: dummy
targets: [0, 1, 2]

actions:
  - id: boh
    operation: qubit_power_spectroscopy
    parameters:
      freq_width: 1_000_000
      freq_step: 10_000
      min_amp_factor: 0
      max_amp_factor: 1
      step_amp_factor: 0.05
      duration: 100
      amplitude: 0.5

```

Checklist:
- [ ] Reviewers confirm new code works as expected.
- [ ] Tests are passing.
- [ ] Coverage does not decrease.
- [ ] Documentation is updated.
- [ ] Compatibility with Qibo modules (Please edit this section if the current pull request is not compatible with the following branches).
    - [ ] Qibo: `master`
    - [ ] Qibolab: `main`
    - [ ] Qibolab_platforms_qrc: `main`

2024-05-20 07:30 UTC, andrea-pasquale commented
Thanks @rodolfocarobene for opening the PR. I will have a look.

> Are there qubits at TII that I could use?
Qubit 0 and 2 in qw5q_platinum are available (3 needs recalibration) in [this](https://github.com/qiboteam/qibolab_platforms_qrc/pull/125) branch.

2024-05-20 08:01 UTC, andrea-pasquale requested changes
Thanks @rodolfocarobene.
LGTM, there is only when error related to the frequency stored.

2024-05-20 08:01 UTC, andrea-pasquale commented on src/qibocal/protocols/qubit_power_spectroscopy.py
> +            freq=delta_frequency_range + ro_pulse.frequency,
```suggestion
            freq=delta_frequency_range + qd_pulses[qubit].frequency,
``
Since you are sweeping drive amplitude

2024-05-20 08:03 UTC, rodolfocarobene commented
Thanks for the review! I will try some tests in the next days :-)

2024-05-20 08:05 UTC, andrea-pasquale approved these changes

2024-05-20 09:22 UTC, rodolfocarobene commented
Sorry @andrea-pasquale , could you send a picture of one of the scan? For some reason I cannot connect to the cluster right now

2024-05-20 09:24 UTC, andrea-pasquale commented
![image](https://github.com/qiboteam/qibocal/assets/49183315/ddedef3b-6ba7-4b02-9ce5-153bccfddc1c)

2024-05-20 09:35 UTC, rodolfocarobene commented
Thank you! It seems to be working fine, but maybe I would remove the normalization part (in the plotting). 
In this way it should be possible also to compare the depth of the different deeps

2024-05-20 17:26 UTC, rodolfocarobene commented
I can confirm this works as expected!

![immagine](https://github.com/qiboteam/qibocal/assets/74607088/8401a8d9-506d-4bd7-98d5-664aea5ca6ca)

2024-05-30 09:11 UTC, Edoardo-Pedicillo approved these changes

2024-05-30 10:21 UTC, merged