Rabi docs
qiboteam/qibocal pull request #868
Opened 2024-05-22 06:48 UTC by Edoardo-Pedicillo

Checklist:
- [ ] Reviewers confirm new code works as expected.
- [ ] Tests are passing.
- [ ] Coverage does not decrease.
- [ ] Documentation is updated.
- [ ] Compatibility with Qibo modules (Please edit this section if the current pull request is not compatible with the following branches).
    - [ ] Qibo: `master`
    - [ ] Qibolab: `main`
    - [ ] Qibolab_platforms_qrc: `main`

2024-06-13 12:06 UTC, andrea-pasquale requested changes
Thanks @Edoardo-Pedicillo, the content is good.
I believe that there are a few files missing.

2024-06-13 12:06 UTC, andrea-pasquale commented on doc/source/protocols/singleshot.rst
> +        nshots: 5000
Question: do you want to provide an example also with some ML classifiers?

2024-06-13 12:06 UTC, andrea-pasquale commented on doc/source/protocols/rabi/rabi.rst
> +	p_e(t) = \frac{1}{2} \left(1- e^{-t/\tau} cos\left(\Omega_R \frac{t}{2}\right)\right)
```suggestion
	p_e(t) = \frac{1}{2} \left(1- e^{-t/\tau} \cos\left(\Omega_R \frac{t}{2}\right)\right)
```

2024-06-13 12:06 UTC, andrea-pasquale commented on doc/source/protocols/rabi/rabi.rst
> +	p_e(t) = sin\left(\Omega_R \frac{t}{2}\right)^2
```suggestion
	p_e(t) = \sin\left(\Omega_R \frac{t}{2}\right)^2
```

2024-06-13 12:06 UTC, andrea-pasquale commented on doc/source/protocols/rabi/rabi.rst
> +.. image:: rabi_ef.png
Image is missing

2024-06-13 12:06 UTC, andrea-pasquale commented on doc/source/protocols/singleshot.rst
> +.. image:: singleshot.png
Missing image

2024-06-13 12:06 UTC, andrea-pasquale commented on doc/source/protocols/index.rst
> +    dispersive_shift
There is no `dispersive_shift` file

2024-06-14 13:16 UTC, alecandido commented on doc/source/protocols/flipping.rst
> +The first :math:`R_x(\pi/2)` is necessary to discriminate the over rotations and under rotarions of the :math:`R_x(\pi)` pulse.
Maybe you could expand a bit this comment, pointing out that oscillating around poles $\pm \Delta$ would result in the same probabilities, while doing it about the equator it would closer to 0 or 1 respectively.

I know this information was enough for us to reach this conclusion, but since it was not immediately clear, we could be slightly more explicit.

2024-06-20 14:14 UTC, Edoardo-Pedicillo commented on doc/source/protocols/singleshot.rst
> +        nshots: 5000
Done

2024-06-21 07:46 UTC, andrea-pasquale reviewed
Thanks for the updates @Edoardo-Pedicillo, generally it looks good to me. I've added
some minor comments.

Two more things:

I believe that a `rst` file for the allxy is missing.

To be consistent with #861 could you use `autoclass` from sphinx to generate the documentation for the parameters? I believe that it is more readable.

2024-06-21 07:46 UTC, andrea-pasquale commented on doc/source/protocols/rabi/rabi.rst
> +	p_e(t) = \frac{1}{2} \left(1- e^{-t/\tau} \cos\left(\Omega_R \frac{t}{2}\right)\right)
Just a small discrepancy. In one case we have $sin^2$ and in the other we have $cos$.
I know that in theory we could use one or the other but it would be better to be consistent.

2024-06-21 07:46 UTC, andrea-pasquale commented on doc/source/protocols/singleshot.rst
> +
Shall we cite Yvonne Gao here?

2024-06-21 07:46 UTC, andrea-pasquale commented on doc/source/protocols/singleshot.rst
> +all the options are explained into the details in :class:`qibocal.protocols.classification.SingleShotClassificationParameters`.
Here I would cite the proceedings :)

2024-06-21 07:46 UTC, andrea-pasquale commented on doc/source/protocols/dispersive_shift.rst
> +:math:`\ket{0}` and :math:`\ket{1}` states are evaluated. The best readout frequency is the one maximizing the distance.
```suggestion
:math:`\ket{0}` and :math:`\ket{1}` states are evaluated. The best readout frequency is the one maximizing the distance between the two blobs.
```

2024-06-21 07:46 UTC, andrea-pasquale commented on doc/source/protocols/dispersive_shift.rst
> +A detailed explanation of the parameters can be found in :class:`qibocal.protocols.dispersive_shift`.
Here the parameters are missing

2024-06-21 07:46 UTC, andrea-pasquale commented on doc/source/protocols/flipping.rst
Here we are missing something related to `flipping_signal`

2024-06-21 13:56 UTC, andrea-pasquale approved these changes
Thanks @Edoardo-Pedicillo, LGTM.

2024-06-21 13:58 UTC, andrea-pasquale commented
@rodolfocarobene @alecandido I believe that we could merge this along side #861 in main.

2024-06-21 14:49 UTC, merged