Adding a proper fit of the resonance of a notch resonator
qiboteam/qibocal pull request #917
Opened 2024-07-04 09:22 UTC by marcogobbo

Hi everyone!

This PR refers to #883. The idea is to fit a resonance of a 2D notch resonator with a proper S21 profile. The implementation on qibocal is based on [https://doi.org/10.1063/1.4907935](https://doi.org/10.1063/1.4907935) Sebastian Probst's paper and Qkit framework.

This could be very helpful since you can retrieve interesting parameters from

$$
S_{21}(f) = ae^{i\alpha}e^{-2\pi i f \tau}\left[ 1 - \frac{(Q_l/|Q_c|)e^{i\phi}}{1 + 2iQ_l(f/f_r -1)} \right]
$$

- $a$: amplitude resulting from the attenuation and gain in the measurement system
- $\alpha$: phase-shift associated with $a$
- $\tau$: is the cable delay constant depending on the length of the cables
- $Q_l$: loaded (total) quality factor
- $Q_c$: coupling (external) quality factor
- $\phi$: accounts for impedance mismatch (Fano interference)
- $f_r$: resonance frequency

I was implementing the S21 fit using a complex fit passing some initial values to help `curve_fit` converge. However, as discussed by Sebastian Probst, this approach is time-consuming and very stressful and the results may not be reliable.

The idea is to follow an algebraic fit in which, step by step, you remove the environment from your data and calibrate the data. Briefly, the routine implemented in `s21_fit` is:

1. Evaluate $\tau$ by fitting the raw phase with a first-degree polynomial, in this case, I just select the first 20 points and the last 20 points, avoiding the change of phase
2. Remove the cable delay from raw data
3. Find the coordinates of the center of the circle
4. Move the circle
5. Phase fit to get $f_r$, $Q_l$ and $\theta$
6. Retrieve $a$, $\alpha$, $\phi$

The report, using this approach, is now

![Screenshot 2024-07-04 at 11 03 57](https://github.com/qiboteam/qibocal/assets/44322256/1c45140b-d8c4-44c9-aa87-2320a81fb23f)

I also added a plot with calibrated data

![Screenshot 2024-07-04 at 11 04 09](https://github.com/qiboteam/qibocal/assets/44322256/9c6dbcc9-6207-4c20-a2bd-2ed53c9b8069)

To use this algebraic fit, the user can specify `s21` in `parameters` of the `runcard.yml`, the key `fit_function` with `s21` as a value (default is `lorentzian`).

Now, I tested this method with two sets of data taken from a 2D planar resonator. I would like to stress this approach to evaluate its stability and robustness. There are some parts of codes that I keep from the previous fit, but I would like to clean up some parts such as $\chi^2$, errors, etc. So, this is a starting point and I would like to share it with you to get some feedback and suggestions.

Checklist:
- [ ] Reviewers confirm new code works as expected.
- [ ] Tests are passing.
- [ ] Coverage does not decrease.
- [ ] Documentation is updated.
- [ ] Compatibility with Qibo modules (Please edit this section if the current pull request is not compatible with the following branches).
    - [ ] Qibo: `master`
    - [ ] Qibolab: `main`
    - [ ] Qibolab_platforms_qrc: `main`

2024-07-04 10:43 UTC, alecandido commented on src/qibocal/protocols/resonator_utils.py
> +    (https://doi.org/10.1063/1.4907935) by Sebastian Probst.
```suggestion
    (https://doi.org/10.1063/1.4907935) by S. Probst et al.
```

2024-07-05 12:31 UTC, alecandido reviewed
I'm still reviewing the bulk of the PR, i.e. the `s21_fit` and `circle_fit` functions, but here are some preliminary comments

2024-07-05 12:31 UTC, alecandido commented on src/qibocal/protocols/resonator_utils.py
> +    phases = np.unwrap(np.angle(z))
Since here you are only using phases, and never magnitudes, why not passing directly `phases`, instead of `z`?

It would make the function more modular.

2024-07-05 12:31 UTC, alecandido commented on src/qibocal/protocols/resonator_utils.py
> +def get_cable_delay(frequencies: NDArray, z: NDArray, num_points: int = 10) -> float:
```suggestion
def cable_delay(frequencies: NDArray, z: NDArray, num_points: int = 10) -> float:
```
in general, `get_` prefixes are not adding anything to the names, so you could even save characters.

2024-07-05 12:31 UTC, alecandido commented on src/qibocal/protocols/resonator_utils.py
> +            The value (float) of the cable delay τ in seconds.
Python supporting Unicode is definitely a nice feature. Though, it is very annoying to type.

However, for math symbols, we already have a more reliable alternative:
```suggestion
            The value (float) of the cable delay :math:`\tau` in seconds.
```

2024-07-05 12:31 UTC, alecandido commented on src/qibocal/protocols/resonator_utils.py
> +    """
Btw, thank you for the care in documenting everything.

However, personally I support a more concise style (no need of a structured `Args:` and `Returns:`, and the types are already in the function signature).
Just describe what the function does in plain sentences (as in Python docs, and its standard library docs), including the role of the parameters and returned values. The structured information is already contained in the signature.

2024-07-05 12:31 UTC, alecandido commented on src/qibocal/protocols/resonator_utils.py
> +    Evaluates the cable delay τ caused by the length of the cable and the finite speed of light.
The first sentence of the docstring should be an extremely concise description of what the function is doing. For sure, it should fit in a single stand-alone line, and we usually place it on the same line of the opening quotes.
```suggestion
    """Evaluates the cable delay :math:`\tau`.

     This delay is caused by the length of the cable and the finite speed of light.
```

2024-07-05 12:56 UTC, alecandido reviewed
I stop this review tranche, since I need an input from you before continuing (about the `a_*` origin)

2024-07-05 12:56 UTC, alecandido commented on src/qibocal/protocols/resonator_utils.py
> +        Polynomio for find a root of a real or complex function using the Newton-Raphson method.
```suggestion
        Polynomial for find a root of a real or complex function using the Newton-Raphson method.
```

The word *polynomio* is certainly not English...

2024-07-05 12:56 UTC, alecandido commented on src/qibocal/protocols/resonator_utils.py
> +        return a_0 + a_1 * x + a_2 * x**2 + a_3 * x**3 + a_4 * x**4
Consider using [`np.polynomial.Polynomial`](https://numpy.org/doc/stable/reference/generated/numpy.polynomial.polynomial.Polynomial.html)

I.e.:
```py
np.polynomial.Polynomial([a_0, a_1, ...])
```

2024-07-05 12:56 UTC, alecandido commented on src/qibocal/protocols/resonator_utils.py
> +        return a_1 + 2 * a_2 * x + 3 * a_3 * x**2 + 4 * a_4 * x**3
Consider using [`np.polynomial.Polynomial.deriv()`](https://numpy.org/doc/stable/reference/generated/numpy.polynomial.polynomial.Polynomial.deriv.html)

2024-07-05 12:56 UTC, alecandido commented on src/qibocal/protocols/resonator_utils.py
> +    )
```suggestion
	coords = np.stack([z, z.real, z.imag, np.ones_like(z)])
	sums = np.sum(coords, axis=1)
	m_matrix = sums * sums[:, np.newaxis]
```

2024-07-05 12:56 UTC, alecandido commented on src/qibocal/protocols/resonator_utils.py
> +    )
I'm sure we can improve even this one, and the following ones. Could you tell me where the expression is coming from?
Is it just the determinant?

2024-07-05 13:47 UTC, marcogobbo commented on src/qibocal/protocols/resonator_spectroscopy.py
> +    fit_function: Optional[str] = "lorentzian"
If I understand you want something like that?

```python
class FitFunction(str, Enum):
    LORENTZIAN = "lorentzian"
    S21 = "s21"

...

    fit_function: Optional[FitFunction] = FitFunction.LORENTZIAN
```

I can do that for the `ResonatorSpectroscopyData` dataclass, but I did not understand why I could not implement it the same way for the `ResonatorSpectroscopyParameters` dataclass.

2024-07-05 14:25 UTC, alecandido commented on src/qibocal/protocols/resonator_spectroscopy.py
> +    fit_function: Optional[str] = "lorentzian"
Actually, making it a string would work for serialization, since you will dump it with
```py
json.dump(asdict(dataclass_containing_enum))
```
and it would work, since `json` recognize it to be a string.

The problem is that parameters are read from a dictionary (the YAML), and that would be loaded as a plain string, not an enum.
But the same problem would occur while loading data.

The origin of the problem is the "load" mechanism, that is automated in Qibocal, but not in the smartest way. It will be smarter soon.
For the time being, ignore this comment.

2024-07-09 08:53 UTC, marcogobbo commented on src/qibocal/protocols/resonator_spectroscopy.py
> +                amplitudes[qubit] = fitted_parameters[qubit][0]
Now it should be fine. `s21_fit`and `fit_result` share the same
```python
if fit_result is not None:
    ...
```

I also added a `dof` variable to evaluate the degrees of freedom evaluating the difference between the length of data and the length of parameters.

The $\chi^2$ for the $S_{21}$ is computed by evaluating the real and the imaginary part
$$\chi^2 = \sum_n \left(\frac{x_n - x_\text{fit}}{\sigma_x}\right)^2 +  \left(\frac{y_n - y_\text{fit}}{\sigma_y}\right)^2$$

Let me know if you agree!

2024-07-09 09:12 UTC, marcogobbo commented on src/qibocal/protocols/utils.py
> +    tau = get_cable_delay(f_data, z_data, 20)
Now I take the 10% of the total points before and after to fit the phase with a first-degree polynomial!

2024-07-09 10:13 UTC, alecandido commented on src/qibocal/protocols/utils.py
> +    tau = get_cable_delay(f_data, z_data, 20)
That is perfectly fine, I'm just telling you to add something like:
```py
DELAY_FIT_PERCENTAGE = 20
```
outside any function (i.e. *top-level*), and use this *named* constant inside your call.

2024-07-09 13:58 UTC, marcogobbo commented on src/qibocal/protocols/utils.py
> +    return model_parameters[0], model_parameters
Actually, I am keeping the same structure of `lorentzian_fit`, since its return is 

```python
def lorentzian_fit(data, resonator_type=None, fit=None):
    ...
    return model_parameters[1] * GHZ_TO_HZ, model_parameters, perr
```

In `resonator_spectroscopy.py`, in the `_fit()` method, when you check `if fit_result is not None` you retrieve this return as
```python
(
    frequency[qubit],
    fitted_parameters[qubit],
    error_fit_pars[qubit],
) = fit_result
```

2024-07-09 14:06 UTC, marcogobbo commented on src/qibocal/protocols/utils.py
> +    tau = get_cable_delay(f_data, z_data, 20)
Should be fine now!

2024-07-09 14:07 UTC, marcogobbo commented on src/qibocal/protocols/resonator_utils.py
> +    phases = np.unwrap(np.angle(z))
Done!

2024-07-09 14:08 UTC, marcogobbo commented on src/qibocal/protocols/resonator_utils.py
> +def get_cable_delay(frequencies: NDArray, z: NDArray, num_points: int = 10) -> float:
Done!

2024-07-09 14:44 UTC, alecandido commented on src/qibocal/protocols/utils.py
> +    tau = get_cable_delay(f_data, z_data, 20)
Done in 5e8241c63

2024-07-09 15:23 UTC, marcogobbo commented
Sometimes, some devices have a minus in phase.

This is the wrong case

![wrong_phase](https://github.com/qiboteam/qibocal/assets/44322256/709c5fe9-016e-4224-b76e-5cd37ff2982a)

This is what I would expect

![right_phase](https://github.com/qiboteam/qibocal/assets/44322256/9784b537-e73e-43b0-a1ab-8e6191d204a5)

This can be solved by verifying if the absolute minimum comes before the absolute maximum and vice versa.
Nonetheless, I would like to investigate more on this before merging it on the main branch.

2024-07-09 15:45 UTC, alecandido commented on src/qibocal/protocols/resonator_utils.py
> +    """
E.g.
```py
    """Estimates the cable delay.

    The cable delay :math:`tau` is caused by the length of the cable and the finite speed of light.
    This is estimated fitting a first-grade polynomial fit of the `phases` as a function of the 
    `frequencies` (in Hz), and extracting the angular coefficient, which is then expressed
    in seconds.

    The `num_points` is used to select how many points should be fitted, from both the
    start and the end of the frequency range.
    """
```

If you can summarize more, preserving the required info, even better :)

2024-07-10 11:41 UTC, alecandido commented on src/qibocal/protocols/resonator_utils.py
> +    )
```suggestion
    coords = np.stack([np.abs(z)**2, z.real, z.imag, np.ones_like(z, dtype=np.float64)])
    m_matrix = np.einsum("in,jn->ij", coords, coords)
```

2024-07-10 13:33 UTC, marcogobbo commented on src/qibocal/protocols/resonator_utils.py
> +    )
Thank you @alecandido!

I refactored all the `circle_fit()` function and now I think it is more readable! The procedure follows **Appendix E** of the [Jiangson Gao thesis](https://thesis.library.caltech.edu/2530/1/thesismain_0610.pdf). 

Let me know if you find it more clear!

2024-07-10 13:38 UTC, alecandido commented on src/qibocal/protocols/resonator_utils.py
> +    roots = np.roots(coefficients)
![image](https://github.com/qiboteam/qibocal/assets/10830876/88b83dce-77de-4260-9430-2878ecb55135)
https://numpy.org/doc/stable/reference/generated/numpy.poly.html

It's not that complicate to translate to [`np.polynomial.Polynomial`](https://numpy.org/doc/stable/reference/generated/numpy.polynomial.polynomial.Polynomial.html#numpy.polynomial.polynomial.Polynomial)

2024-07-10 14:22 UTC, alecandido reviewed
Another tranche, just about the usage of the fit in the routine

2024-07-10 14:22 UTC, alecandido commented on src/qibocal/protocols/resonator_spectroscopy.py
> +                data[qubit], resonator_type=data.resonator_type, fit="resonator"
```suggestion
        fit = s21_fit if data.fit_function == "s21" else lorentzian_fit
        fit_result = fit(
            data[qubit], resonator_type=data.resonator_type, fit="resonator"
        )
```

2024-07-10 14:22 UTC, alecandido commented on src/qibocal/protocols/resonator_spectroscopy.py
>      return spectroscopy_plot(data, target, fit)
```suggestion
    plot = s21_spectroscopy_plot if data.fit_function == "s21" else spectroscopy_plot
    return plot(data, target, fit)
```

2024-07-10 14:22 UTC, alecandido commented on src/qibocal/protocols/resonator_spectroscopy.py
> +                    ),
Collect this as a separate `chi2_reduced_complex` function (you can put it in the same `utils` module of `chi2_reduced`), and invoke similar to the other one:
```py

                chi2[qubit] = (
                    chi2_reduced_complex(
                        (data[qubit].signal, data[qubit].phase),
                        s21(data[qubit].freq, *fitted_parameters[qubit]),
                        data[qubit].error_signal,
                    ),
                    np.sqrt(2 / dof),
                )

```

2024-07-13 08:09 UTC, marcogobbo commented on src/qibocal/protocols/resonator_utils.py
> +    roots = np.roots(coefficients)
Done!

2024-07-13 08:10 UTC, marcogobbo commented on src/qibocal/protocols/resonator_spectroscopy.py
> +                data[qubit], resonator_type=data.resonator_type, fit="resonator"
Corrected!

2024-07-13 08:10 UTC, marcogobbo commented on src/qibocal/protocols/resonator_spectroscopy.py
>      return spectroscopy_plot(data, target, fit)
Corrected!

2024-07-13 08:10 UTC, marcogobbo commented on src/qibocal/protocols/resonator_spectroscopy.py
> +                    ),
Implemented!

2024-07-15 09:40 UTC, alecandido commented on src/qibocal/protocols/resonator_spectroscopy.py
> +    fit = s21_fit if data.fit_function == "s21" else lorentzian_fit
```suggestion
    fit, chi2_, values, errors = (
        (lorentzian_fit, chi2_reduced, lambda q: q.signal, lambda q: q.error_signal)
        if data.fit_function == "lorentzian"
        else (
            s21_fit,
            chi2_reduced_complex,
            lambda q: (q.signal, q.phase),
            lambda q: (q.error_signal, q.error_phase),
        )
    )
```

After this one, you won't need any further branching :)

2024-07-15 09:40 UTC, alecandido commented on src/qibocal/protocols/resonator_spectroscopy.py
> +    fit = s21_fit if data.fit_function == "s21" else lorentzian_fit
Together with the `plot` function below, these could even be collected in a data structure, with the two tuples.

E.g. for the time being, you could define something like:
```py
@dataclass
class SpectroscopyFit:
    fit: Callable
    chi2: Callable
    values: Callable
    errors: Callable
    plot: Callable

fits = {"lorentzian": SpectroscopyFit(lorentzian_fit, ...), "s21": SpectroscopyFit(...)}
```
top-level, since the definitions do not depend on any runtime data other than the fit kind.

2024-07-16 09:58 UTC, marcogobbo commented on src/qibocal/protocols/resonator_utils.py
> +    roots = coefficients.roots()
I agree, I simplified it with

```python
coefficients = np.linalg.eigvals(np.linalg.inv(b_matrix).dot(m_matrix))

eta = np.min(
    np.real(
        [
            coefficient
            for coefficient in coefficients
            if np.isreal(coefficient) and coefficient > 0
        ]
    )
)
```

2024-07-16 09:59 UTC, marcogobbo commented on src/qibocal/protocols/resonator_utils.py
> +        a_vector = np.array(a_vector)
It wasn't necessary, I removed it

2024-07-26 09:31 UTC, alecandido commented on src/qibocal/protocols/utils.py
> +    perr = [0.0] * 7
```suggestion
    perr = [np.nan] * 7
```
If not causing issues downstream, we should consider using `NaN` (which is a valid float, but explicitly denote a value absence, rather than being a specific value).

2024-07-26 14:35 UTC, alecandido approved these changes

2024-07-27 18:01 UTC, alecandido commented
The current PR is definitely in a good state, since its main purpose is refining a protocol (introducing a new fit), even in comparison to other protocols.

However, a couple of improvements are reasonable to achieve, though slightly above the average Qibocal standard:
1. the fit could be documented in the [protocol page](https://qibo.science/qibocal/latest/protocols/resonator_spectroscopy.html)
2. since the utilities for the fit are sufficiently modular, they could be effectively tested, following two main schemes:
    - testing remarkable and ordinary values, e.g. in `periodic_boundary` and `phase_dist`
    - introducing closure tests [*], w/ and w/o (a small amount of) noise, for all the fits involved (the linear fit for cable delay, the circle, the phase fit for the off-resonant angle)

Thanks to the effort of @andrea-pasquale and @Edoardo-Pedicillo 1. is becoming more and more the standard (but not all protocols and all features are yet documented). 2. would be definitely a novelty (but a welcome one).

I'd propose to wait for @andrea-pasquale in-depth review, and if @marcogobbo will have time to implement 1. and 2. before that, so much the better. Otherwise, just turn this comment into an issue, and let's postpone for a further PR (at least we could start using circles in current Qibocal, hurrah!).

[*]: closure tests involves generating fake data from a known truth, representing exactly the model we'd like to fit, possibly adding some noise, and compare the extracted parameters with those used during the generation

2024-07-27 18:03 UTC, alecandido commented
(I mentioned explicitly @andrea-pasquale, but of course everyone is welcomed to take a look, including @Edoardo-Pedicillo, @rodolfocarobene, and @Jacfomg, if you want to)

2024-07-29 06:26 UTC, andrea-pasquale reviewed
Thanks a lot @marcogobbo for the implementation!
I have some comments down below.
One major issue is the sign of the phase. I tested it on TII chip using QM and I had to manually change the sign of the phase to make that the fit worked properly.
Here is an example of the fit with phase reversed:
![image](https://github.com/user-attachments/assets/7205e16c-29d1-47d6-b9b7-185d0cd7cec2)

I could discuss with qibolab devs (@alecandido @stavros11 @hay-k) to make sure that we unify the sign convention at least when using qibolab drivers.

Secondly, I think that if I have a frequency range which is too large the performance of the fit deteriorates. Perhaps it could be a good idea to put in the docstring some sort of reasonable range for which the fit works as expected. It could also be a function of some expected parameters.
In the example below the circle fit seems to be not the best but the feature is more or less found correctly:
![image](https://github.com/user-attachments/assets/248c2a82-c0bb-49cf-8ec9-058b6794b062)

Regarding closure tests and documentation, for the time being I would like to have the documentation updated before we merge. Closure tests can be implemented later on.

2024-07-29 08:04 UTC, marcogobbo commented on src/qibocal/protocols/resonator_utils.py
> +    if np.max(phases) - np.min(phases) <= 0.8 * 2 * np.pi:
The value 0.8 is chosen as a threshold to ensure the phase data covers a significant portion of the full $2\pi$ circle. A possible solution to satisfy this condition is to increase the frequency span around the resonance.

2024-07-29 08:24 UTC, marcogobbo commented on src/qibocal/protocols/resonator_spectroscopy.py
> +        lambda z: z.error_signal,
Could you be more specific? I think what @alecandido proposed is to unify the two fit solutions and I can't directly access `signal` and `error_signal` (or probably I am missing something).

2024-07-29 08:39 UTC, marcogobbo commented on src/qibocal/protocols/resonator_utils.py
> +    theta_guess = 0.5 * (np.mean(phases[:5]) + np.mean(phases[-5:]))
No, it is just for taking a few values to better guess `theta`. I could define a constant for this and the 0.8 if you want.

2024-07-29 11:01 UTC, alecandido commented on src/qibocal/protocols/resonator_spectroscopy.py
> +
Ok, let's make it brief. More relevant for the class, because it should explain its role.

2024-07-29 11:04 UTC, alecandido commented on src/qibocal/protocols/resonator_utils.py
> +    phases = np.unwrap(phases)
It should not, but it depends on the jump set. If you use twice with the same jump value (e.g. the default) jumps are consumed the first time, and the unwrapping algorithm should make sure that the new value is not a jump itself (if we think with $2\pi$, it will remove as many $2\pi$ as needed in order not to need any further).

Still, if it's already unwrapped no need to repeat. It's a (small) waste, and possibly confusing to debug and maintain (if you'd remove the upstream `unwrap`, you'd expect to be wrapped, and it won't).

2024-07-29 11:06 UTC, alecandido commented on src/qibocal/protocols/resonator_spectroscopy.py
> +        lambda z: z.error_signal,
I believe the answer in this case is just "no".

The reason is that the moment you specify this function, you don't know yet the arrays. And to specify the function when you know the arrays, you should make it nested (making the code more convoluted, and redefining the function at each and every evaluation).

Working with functions could be confusing, but the most effective way to think them is as "delayed evaluations".

2024-07-29 11:07 UTC, alecandido commented on src/qibocal/protocols/resonator_utils.py
> +    if np.max(phases) - np.min(phases) <= 0.8 * 2 * np.pi:
I guess the suggestion could be made more specific: move the non-trivial value top-level, give it a name, and briefly document it (possibly copying part of your comment).

2024-07-29 11:09 UTC, alecandido commented on src/qibocal/protocols/resonator_spectroscopy.py
> +    """Fit function (optional) used for the resonance."""
Above, I suggested making an enum for this purpose. But that's correct: if we're using strings, the domain should be expressed at least in the docstring.

And remove `Optional[]`: it has a default, but it will never be `None`.

2024-07-29 11:12 UTC, alecandido commented on src/qibocal/protocols/resonator_utils.py
> +        return residuals_full((resonance_guess, q_loaded, theta_guess, tau_guess))
I didn't insist myself on this point, because part of the plan for future developments is to drop all this functions.

This fit specifically has to improve, cf. #948 #947. And, in particular, there is a point in #947 about these functions.

However, using `partial` could be slightly more elegant, but that's exactly what they are doing (with no runtime difference, it'd just be a difference in how the code reads - which is relevant, but not fundamental for "temporary code" - assuming it is really temporary...).

2024-07-30 14:45 UTC, marcogobbo commented on src/qibocal/protocols/resonator_spectroscopy.py
> +
Done!

2024-07-30 14:50 UTC, marcogobbo commented on src/qibocal/protocols/resonator_utils.py
> +    phases = np.unwrap(phases)
I removed all the `np.unwrap` applied to the raw data. @andrea-pasquale if you can I would like you to test this version of the PR. Please make sure to apply a minus on the phase if you are using QM.

2024-07-30 14:50 UTC, marcogobbo commented on tests/runcards/protocols.yml
> +      freq_step: 100_000 # 500_00
Done!

2024-07-30 14:51 UTC, marcogobbo commented on src/qibocal/protocols/resonator_utils.py
> +    if np.max(phases) - np.min(phases) <= 0.8 * 2 * np.pi:
Done!

2024-07-30 14:51 UTC, marcogobbo commented on src/qibocal/protocols/resonator_spectroscopy.py
> +    """Fit function (optional) used for the resonance."""
Done!

2024-07-30 14:51 UTC, marcogobbo commented on src/qibocal/protocols/resonator_utils.py
> +    theta_guess = 0.5 * (np.mean(phases[:5]) + np.mean(phases[-5:]))
Done!

2024-07-30 18:30 UTC, alecandido commented on src/qibocal/protocols/resonator_spectroscopy.py
> +
> Done!

Good, even better if you also put the commit hash. E.g.:

> Done in 76da7eefc7735db4aa0dc323256ec771e50ff8a8!

2024-08-01 10:25 UTC, andrea-pasquale commented on src/qibocal/protocols/resonator_utils.py
> +    phases = np.unwrap(phases)
I think that it is better if you keep `np.unwrap`
![image](https://github.com/user-attachments/assets/32e8a6ef-826b-4aae-b47b-50a627b68047)
without it, as you can see above some jumps start to appear that are deteriorating the performance of the fit.
Here is the same experiment before removing `np.unwrap`.
I don't really know why this happens but since we know the "fix" alreay I would just reintroduce `np.unwrap`.

2024-08-05 13:15 UTC, marcogobbo commented on src/qibocal/protocols/resonator_utils.py
> +    phases = np.unwrap(phases)
Done! [11d7460](https://github.com/qiboteam/qibocal/pull/917/commits/11d74602f45a89e4ad9dac1c7312869d0fe37367)

2024-08-05 13:30 UTC, marcogobbo commented
Hi everyone, a few comments about the last commits:

- [11d7460](https://github.com/qiboteam/qibocal/pull/917/commits/11d74602f45a89e4ad9dac1c7312869d0fe37367): I have applied a temporary solution for the phase unwrapping, this applies only to the `ResonatorSpectroscopy` experiment, more specifically the the `s21`fit function since it exploits both magnitude and phase information. I think that applying the phase unwrapping to all the experiments is useless, since, as far as I know, they do not use phase information. I think is better to wait until the phase unwrapping is implemented on qibolab.
- [48a598d](https://github.com/qiboteam/qibocal/pull/917/commits/48a598d56e51584e7d3117ba2a3b9584dd015e54): this is another patch until a standard convention is reached for the sign of the phase for each instrument. I was investigating a non-parametrized solution, but this is non-trivial. @andrea-pasquale, @alecandido, and @rodolfocarobene agree with this temporary solution.
- [792f13c](https://github.com/qiboteam/qibocal/pull/917/commits/792f13c532447e1ec1cc043742ecabcd983cb1d9): I have done a review of the documentation for the `ResonatorSpectroscopy` experiment, implementing also the new stuff of this PR. This is almost completed, but I would like to have a good set of data (I think that @andrea-pasquale is working on it) to plot the full calibration routine for a better description.

I encourage you to do a review of this documentation to see if it fits with your standards! :)

2024-08-12 04:15 UTC, andrea-pasquale commented
> Hi everyone, a few comments about the last commits:
> 
>     * [11d7460](https://github.com/qiboteam/qibocal/pull/917/commits/11d74602f45a89e4ad9dac1c7312869d0fe37367): I have applied a temporary solution for the phase unwrapping, this applies only to the `ResonatorSpectroscopy` experiment, more specifically the the `s21`fit function since it exploits both magnitude and phase information. I think that applying the phase unwrapping to all the experiments is useless, since, as far as I know, they do not use phase information. I think is better to wait until the phase unwrapping is implemented on qibolab.
> 
>     * [48a598d](https://github.com/qiboteam/qibocal/pull/917/commits/48a598d56e51584e7d3117ba2a3b9584dd015e54): this is another patch until a standard convention is reached for the sign of the phase for each instrument. I was investigating a non-parametrized solution, but this is non-trivial. @andrea-pasquale, @alecandido, and @rodolfocarobene agree with this temporary solution.
> 
>     * [792f13c](https://github.com/qiboteam/qibocal/pull/917/commits/792f13c532447e1ec1cc043742ecabcd983cb1d9): I have done a review of the documentation for the `ResonatorSpectroscopy` experiment, implementing also the new stuff of this PR. This is almost completed, but I would like to have a good set of data (I think that @andrea-pasquale is working on it) to plot the full calibration routine for a better description.
> 
> 
> I encourage you to do a review of this documentation to see if it fits with your standards! :)

Thanks @marcogobbo for all the updates.
I will try to have a good set of data by the end of the week and we can merge :)

2024-08-12 07:13 UTC, andrea-pasquale requested changes

2024-08-12 07:13 UTC, andrea-pasquale commented on src/qibocal/protocols/resonator_spectroscopy.py
> +        )  # TODO: move phase unwrapping in qibolab
This doesn't work properly because you are manipulating `Data` inside `fit`.
This could create issues because when we plot, we plot directly from file, which in this case
will not contain the following modifications which are performed at runtime.
![image](https://github.com/user-attachments/assets/b7ca90fd-d2a8-4741-8fee-1f4afe9866e5)
http://login.qrccluster.com:9000/Z8iDVrIzTe-xiW_slLxUzQ==
At this point we could just move this manipulation directly in the acquisition or make sure that they are done properly. For example you could add a method to unwrap phase to `ResonatorSpectroscopyData`

```py
def unwrap_phase(self, qubit: QubitId):
    return np.unwrap(-data[qubit].phase if data.phase_sign else data[qubit].phase)
```
Let me know what you think

2024-08-12 07:53 UTC, andrea-pasquale commented
> * [792f13c](https://github.com/qiboteam/qibocal/pull/917/commits/792f13c532447e1ec1cc043742ecabcd983cb1d9): I have done a review of the documentation for the `ResonatorSpectroscopy` experiment, implementing also the new stuff of this PR. This is almost completed, but I would like to have a good set of data (I think that @andrea-pasquale is working on it) to plot the full calibration routine for a better description.

@marcogobbo I think I have a good set of data (I've used the code at commit https://github.com/qiboteam/qibocal/pull/917/commits/e379ec8b5c0c3059b797b0e56acd9f0c993bc3e2 to avoid the current issues):

![image](https://github.com/user-attachments/assets/ae5941f5-8ca1-4059-b3a1-21f24e326ed5)


http://login.qrccluster.com:9000/VCvMfFVGRHmil0pW0Lensg==/

Although the scan is small it shows that the fit is able to reconstruct an almost perfect circle :)

2024-08-12 13:12 UTC, andrea-pasquale approved these changes

2024-08-13 05:14 UTC, merged