run transpiled circuit in platform with generic QubitId
qiboteam/qibocal pull request #940
Opened 2024-07-17 11:21 UTC by Edoardo-Pedicillo

As the title says

Checklist:
- [ ] Reviewers confirm new code works as expected.
- [ ] Tests are passing.
- [ ] Coverage does not decrease.
- [ ] Documentation is updated.
- [ ] Compatibility with Qibo modules (Please edit this section if the current pull request is not compatible with the following branches).
    - [ ] Qibo: `master`
    - [ ] Qibolab: `main`
    - [ ] Qibolab_platforms_qrc: `main`

2024-07-18 14:04 UTC, andrea-pasquale requested changes

2024-07-18 14:04 UTC, andrea-pasquale commented on src/qibocal/auto/transpile.py
> +    qubits = list(backend.platform.qubits.keys())
```suggestion
    qubits = list(backend.platform.qubits)
```

2024-07-18 14:04 UTC, andrea-pasquale commented on src/qibocal/protocols/randomized_benchmarking/utils.py
> +    if isinstance(target, QubitId):
```suggestion
    if isinstance(target, (str,int)):
```
This should fix tests.

2024-07-23 07:00 UTC, andrea-pasquale approved these changes

2024-07-25 08:47 UTC, alecandido commented on src/qibocal/auto/transpile.py
> +    Apply the `transpiler` to the `circuits` list and pad them in
Start the docstring with a short line, that fits the same line as the initial quotes `"""`.

2024-07-25 08:51 UTC, Edoardo-Pedicillo commented
With the commit https://github.com/qiboteam/qibocal/pull/940/commits/5d5b7adc43a176cd23af92426dcf623c65152616 I tried an RB (http://login.qrccluster.com:9000/iDjz_IWTT_iLubJBKg8O0Q==/), just to show that it does not brake anything :)

Same runcard, but with https://github.com/qiboteam/qibocal/pull/940/commits/4fbfaf7d63e097f1a28023937462a9c784dac9bc : http://login.qrccluster.com:9000/tCEevodbQLOYHBq4vlLC7Q==/

2024-07-25 09:04 UTC, andrea-pasquale approved these changes

2024-07-25 09:06 UTC, andrea-pasquale commented
> With the commit [5d5b7ad](https://github.com/qiboteam/qibocal/commit/5d5b7adc43a176cd23af92426dcf623c65152616) I tried an RB (http://login.qrccluster.com:9000/iDjz_IWTT_iLubJBKg8O0Q==/), just to show that it does not brake anything :)
> 
> Same runcard, but with [4fbfaf7](https://github.com/qiboteam/qibocal/commit/4fbfaf7d63e097f1a28023937462a9c784dac9bc) : http://login.qrccluster.com:9000/tCEevodbQLOYHBq4vlLC7Q==/

Thanks @Edoardo-Pedicillo, the difference between 98 and 99 it is just related to lack of statistics, correct?

2024-07-25 09:12 UTC, Edoardo-Pedicillo commented
> Thanks @Edoardo-Pedicillo, the difference between 98 and 99 it is just related to lack of statistics, correct?

Yes, since the fidelities are consistent between the two reports.

2024-07-25 18:04 UTC, alecandido approved these changes

2024-07-25 18:04 UTC, alecandido commented on src/qibocal/auto/transpile.py
> +    if backend.name == "qibolab":
Instead, just early return
```suggestion
    if backend.name != "qibolab":
        return circuits
```

2024-07-26 05:18 UTC, andrea-pasquale commented on src/qibocal/auto/transpile.py
> +    if backend.name == "qibolab":
I thought that it was fine but this will case CI to fail https://github.com/qiboteam/qibocal/actions/runs/10106037732/job/27947515680.
I'm not sure why.

2024-07-26 12:12 UTC, merged